ENH: AudioCellのキャラクター選択ボタンをコンポーネント化
VOICEVOX/voicevox pull request #1029
Opened 2022-12-01 11:00 UTC by sabonerune

## 内容

モーフィングUIに使用するためにAudioCellからキャラクター選択ボタンを切り離してコンポーネント化しました。

## 関連 Issue

- ref #552 

## その他

AudioCellからそのまま持ってきたものが多いです。

2022-12-01 11:02 UTC, sabonerune commented on src/components/CharacterButton.vue
> +      type: Object as PropType<{ engineId: string, speakerId: string, styleId: number } | undefined>
ちゃんと型定義した方がよかったかもしれない？

2022-12-01 16:03 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      () => store.getters.USER_ORDERED_CHARACTER_INFOS ?? []
これは`USER_ORDERED_CHARACTER_INFOS`がundefinedだったときのフォールバックだと思うのですが、逆にこのフォールバック（空配列）が不具合になる可能性もあるかなぁと思います。
なのでフォールバックをやめて、逆に`userOrderedCharacterInfos`を使う側を`v-if="userOrderedCharacterInfos"`にして表示しないようにする、というのはどうでしょう。

（想定外の変数が来ること自体が良くない設計だと思っています。これはvuexのstoreを使っている限り必ず起こります。ここの設計をしたのは僕なので、申し訳ないです。。）

2022-12-01 16:38 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      return { engineId, speakerId, styleId };
CharacterButtonが`speakerId`を受け取るようになっていますね！

「声」を選ぶとき、エンジン・話者・スタイルのすべてが揃ってるべきだと思うのですが、今はエンジン・スタイルだけで声が一意に決まるようになっています。
（こちらに歴史的経緯が書いています）
https://github.com/VOICEVOX/voicevox/blob/65ad4137b8617d77da99b81085206ef54fa71517/docs/%E8%A8%AD%E8%A8%88%E6%96%B9%E9%87%9D.md#engineidspeakeridstyleid

CharacterButton以外はそのルールで動いているので、CharacterButtonだけspeakerIdが必要なようになると、足並みが崩れてしまいます。
でも、正直`{ engineId, speakerId, styleId }`を扱うほうが綺麗だと思います。

次の３つのうちどれか対応をお願いしても良いでしょうか 🙇‍♂️ 

1. speakerIdをなくして足並みを揃える
2. StyleInfoにspeakerIdが入るようにする（大体のコードはStyleInfoを取り回しているので、急変を防げると思っています）
3. 上記２つのどちらかを、僕からPR送るので、 @sabonerune さんにマージしていただく

もし対応してもOKという感じなら1か2をお願いしたいです。
お時間なければ3で行って、僕からのPRを待っていただければと思います

2022-12-01 16:58 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      return { engineId, speakerId, styleId };
すみません･･･。
２の方法だと、コンポーネント化する以上のことをやらないといけないので、１でできればと思います 🙇 

（changeStyleの引数が`{engineId, styleId}`なので、引数を変えないでおこうと思うと１の方法になりそうでした。）

2022-12-01 17:29 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      return { engineId, speakerId, styleId };
うーん！！結構変わっててどちらも難しそうでした！！

良い機会だと思うので、`{ engineId, speakerId, styleId }`をまとめた新しい型`Voice`を定義しちゃいましょう！

1. `type/preload.ts`に↑の型を追加
2. `selectedStyle`などを`selectedVoice`に変更（たぶん`computed<Voice>`などとすれば型バリデーションもできるはず）

をお願いしても良いでしょうか。

2022-12-01 17:31 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +      type: Object as PropType<{ engineId: string, speakerId: string, styleId: number } | undefined>
ですね！！
実はずっと前からこの型作りたいよねと話していたものまさしくなので、`Voice`型でどうでしょう👀

2022-12-01 17:32 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +    "update:selectedStyle"(
selectedStyleをupdateする、というのはちょっとややこしいかもと思いました。
素直に`changeVoice`でどうでしょう。

2022-12-01 17:40 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +                      "
`onSelectSpeaker`と合わせてこちらも`onSelectStyle`などとするとわかりやすいかもです。
（変更してもしなくてもどちらでもOKだと思います）

2022-12-01 17:49 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +              "
たぶん、キャラクターが居ないときに`$emit('update:selectedStyle', undefined)`が呼ばれる想定だと思うのですが、`characterInfos`が空配列なのでそもそもこのボタンが生成されていない気がします。
ここは↓にしておいて、モーフィングUIのときに修正するのが良いかも？

2022-12-01 17:50 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +              "
たぶん、キャラクターが居ないときに`$emit('update:selectedStyle', undefined)`が呼ばれる想定だと思うのですが、`characterInfos`が空配列なのでそもそもこのボタンが生成されていない気がします。
ここは↓にしておいて、モーフィングUIのときに修正するのが良いかも？
```suggestion
              @click="onSelectSpeaker(characterInfo.metas.speakerUuid)"
```

2022-12-01 17:51 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +              </div>
同上です
```suggestion
              <div>{{ characterInfo.metas.speakerName }}</div>
```

2022-12-01 17:57 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +    <div v-else class="dummy-image"></div>
`dummy-image`が設定されてなさそうです。
代わりに、EngineMangerDialogのこちらを真似て`？`を表示するのはどうでしょう。
https://github.com/VOICEVOX/voicevox/blob/65ad4137b8617d77da99b81085206ef54fa71517/src/components/EngineManageDialog.vue#L163-L167
（たぶんselectedStyleInfoがundefinedになる機会はこのPRでは無いので、いったんここは`v-if="selectedStyleInfo"`を消してあとで実装でも良いかもです）

2022-12-01 23:01 UTC, sabonerune commented on src/components/CharacterButton.vue
> +    "update:selectedStyle"(
ガイド見ながら作成したので一切使用しないにも関わらず`v-model`を使用できるように作ってしまったのですよね…
https://ja.vuejs.org/guide/components/events.html#usage-with-v-model

2022-12-02 09:52 UTC, sabonerune commented
とりあえずキャラクター選択ボタンだけはこのPRで完結させようと思います。

2022-12-02 17:23 UTC, sabonerune commented on src/components/CharacterButton.vue
> +    <div v-else class="dummy-image"></div>
`if="selectedStyleInfo"`を消去しました

2022-12-02 17:28 UTC, sabonerune commented on src/components/CharacterButton.vue
> +    "update:selectedStyle"(
`update:selectedStyle`はそのままにして`AudioCell`の方で`v-model`を使用するように変更してみました。

2022-12-02 17:46 UTC, sabonerune commented on src/components/AudioCell.vue
> -    };
`changeStyleId`を`selectedVoice`のsetterに移動

2022-12-02 17:46 UTC, sabonerune commented on src/components/AudioCell.vue
> +      },
書き込み可能な算出関数に変更しました

2022-12-02 19:29 UTC, Hiroshiba reviewed
> とりあえずキャラクター選択ボタンだけはこのPRで完結させようと思います。

了解です、よろしくお願いします！

2022-12-02 19:29 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +        if (voice == undefined) throw new Error("voice == undefined");
このコードは実行されないかも？

2022-12-03 14:15 UTC, sabonerune commented on src/components/AudioCell.vue
> +        if (voice == undefined) throw new Error("voice == undefined");
直しました

2022-12-04 15:45 UTC, Hiroshiba approved these changes
LGTM！！

修正ありがとうございました！！

@MT224244 さん、もしよかったらレビューお願いできると心強いです･･･！

2022-12-04 15:45 UTC, Hiroshiba commented on src/components/AudioCell.vue
> -    height: fit-content;
`height: fit-content;`が移動先に無いかも？

2022-12-04 16:40 UTC, MT224244 requested changes

2022-12-04 16:40 UTC, MT224244 commented on src/components/CharacterButton.vue
> +    characterInfos: { type: Array<CharacterInfo>, required: true },
このファイルだけESLintが効いていなくて、原因がここでした。
配列の型はPropTypeで指定する必要があるみたいです。

これを修正するとESLintのエラーがいくつか検出されるようになるので、 `npm run fmt` の実行もお願いします。

```suggestion
    characterInfos: { type: Array as PropType<CharacterInfo[]>, required: true },
```

2022-12-04 22:37 UTC, sabonerune commented on src/components/CharacterButton.vue
> +    characterInfos: { type: Array<CharacterInfo>, required: true },
ありがとうございます。
フォーマッターが上手く働いていないような気はしていましたがそんなところに原因があったとは…

2022-12-04 23:57 UTC, MT224244 approved these changes
LGTM！

2022-12-05 02:39 UTC, merged