VVPPアンインストール時とディレクトリ見つからない時のエラーハンドリング追加
VOICEVOX/voicevox pull request #1047
Opened 2022-12-16 18:23 UTC by Hiroshiba

## 内容

VVPPアンインストール時と、ディレクトリ見つからない時のエラーハンドリング追加しました。

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_project/issues/2

## その他

2022-12-16 18:41 UTC, Hiroshiba commented on src/background.ts
> +  try {
`installVvppEngine`側はダイアログを出していたが`uninstallVvppEngine`側はダイアログを出しておらず、エラーが出ても何も表示されない状態になってたので合わせてみました

2022-12-16 18:41 UTC, Hiroshiba commented
@sevenc-nanashi よかったらレビューお願いできると助かります･･･！

2022-12-16 21:34 UTC, sevenc-nanashi requested changes
一個バグがあったのでコメントしました。それ以外はLGTMです！

（今更なんですけど、uninstallVvppEngineという名前をしといて実際はアンインストール走ってないんですよね。
ユーザーはそんなこと気にしないので大丈夫だと思いますが）

2022-12-16 21:34 UTC, sevenc-nanashi commented on src/background.ts
> +    return false;
これでfalseがreturnされても、再起動確認ダイアログが出てしまっていました。インストール時みたいに戻り値で分岐すれば大丈夫だと思いますー。

2022-12-17 13:14 UTC, Hiroshiba commented on src/background.ts
>  async function uninstallVvppEngine(engineId: string) {
uninstallVvppEngineにドキュメントコメント書いてみました。

2022-12-17 13:14 UTC, Hiroshiba commented on src/components/EngineManageDialog.vue
> -        uiLockedState.value = null;
不要な処理だったのでついでに消去

2022-12-17 13:14 UTC, Hiroshiba commented on src/background.ts
> +    return false;
こちら修正しました！！

2022-12-17 13:22 UTC, sevenc-nanashi approved these changes
エラー時、通常時両方しっかり動いてそうでした。LGTM！

2022-12-17 13:50 UTC, Hiroshiba commented
マージします！

2022-12-17 13:50 UTC, merged