複数エンジン対応：分割されたvvppの読み込みを追加
VOICEVOX/voicevox pull request #1050
Opened 2022-12-17 14:05 UTC by sevenc-nanashi

## 内容

分割されたVVPPファイルの読み込み機能を追加します。
7zの`xxx.7z.001`とは違い、`xxx.001.vvpp`のように`名前.番号.vvpp`になっています、これはユーザーがダブルクリックで読み込めるようにするためです。

## 関連 Issue

- ref: voicevox/voicevox_project#2
- ref: https://github.com/VOICEVOX/voicevox_engine/pull/524

## スクリーンショット・動画など

（なし）

## その他

（なし）

2022-12-17 19:09 UTC, Hiroshiba requested changes

2022-12-17 19:09 UTC, Hiroshiba commented on src/background/vvppManager.ts
> +        .replace(/\\/g, "/"); // node-globはバックスラッシュを使えないので、スラッシュに置換する
これだと別のvvppも取ってきちゃいますね･･･！
prefixを取得→`/prefix.[0-9]+.vvpp`で検索とかでどうでしょう。

2022-12-17 19:09 UTC, Hiroshiba commented on src/background/vvppManager.ts
> +      for (const p of await glob(vvppPathGlob)) {
pythonの`glob`とかだとソートされていないのですが、これはソートされる感じでしょうか。

あと、しっかり考えると番号順にソートしないといけないかもです。
（1~10あると1→10→2→3になってしまう）
まあ10分割とか流石にない気がするので、FIXMEコメントでも良いかも･･･？

2022-12-17 19:09 UTC, Hiroshiba commented on src/background/vvppManager.ts
> +    const streams: fs.ReadStream[] = [];
このブロックが何をしようとしてるか若干だけ見えづらいので、一言コメント書いとくとコード見る人が心構えできるかもです。
```suggestion
    // 番号順のファイル（[prefix].001.vvpp, [prefix].002.vvpp, ...）があれば連結
    const streams: fs.ReadStream[] = [];
```

2022-12-17 19:11 UTC, Hiroshiba commented on src/background/vvppManager.ts
> +        .replace(/\\/g, "/"); // node-globはバックスラッシュを使えないので、スラッシュに置換する
あっすみません、コード読み違えてました！問題なさそう･･･！

2022-12-17 23:56 UTC, sevenc-nanashi commented
修正しました。

2022-12-18 16:35 UTC, Hiroshiba approved these changes
LGTM！！

2022-12-18 16:36 UTC, merged