Change: フォントをRounded M+ 1cに
VOICEVOX/voicevox pull request #1061
Opened 2022-12-23 13:17 UTC by sevenc-nanashi

## 内容

エディタのフォントをRounded M+ 1cにし、切り換えオプションを追加します。

## 関連 Issue

（なし）

## スクリーンショット・動画など

![image](https://user-images.githubusercontent.com/59691627/209342329-8024fb9d-00ae-4ccd-b1cb-16efe3c64a5a.png)

## その他

フォントは`default`（デフォルト）と`os`（OS標準）と言う表記になっています。もっといい表現があるとおもいます

2022-12-23 17:23 UTC, Hiroshiba approved these changes
LGTM！！

かなり吟味してみていました！
感じた良いとこと駄目なとこを列挙し、それらの判断をメモしておきます。

* 良いとこ
	* OSが違ってもフォントが同じになる
	* ちょっと柔らかい感じになる（windowsフォントに比べると）
* 駄目なとこ
	* 太字が潰れる（１つ書き出しの「書」）
	* アルファベット・数字とそれ以外の文字で雰囲気が違う（`-1c`だから。cはcode。）

太字が潰れるのは、まあ仕方ないかなという判断です。
windowsフォント優秀だなと感じました。

アルファベットの雰囲気違いは`M+ 1p`だと問題ないのですが、これはRoundedじゃありませんでした。
`Rounded M+ 1p`があると一番良さそうなのですが、少なくともnpmで手に入る者の中にはなさそうでした。

ちなみにこれくらいの差です。（両方開いてタブ切り替えすると差がわかりやすいかも）

<details>

Rounded M+ 1c
![_VOICEVOX - Ver  999 999 999 - CPU 2022_12_24 1_53_25](https://user-images.githubusercontent.com/4987327/209376201-894948cd-01a1-440a-9a48-7d321fa66a38.png)

M+ 1p
![_VOICEVOX - Ver  999 999 999 - CPU 2022_12_24 1_51_46](https://user-images.githubusercontent.com/4987327/209376204-ef8d412e-6d0e-4e15-85dd-fb27e479fd7f.png)

</details>

2022-12-23 17:23 UTC, Hiroshiba commented on src/store/type.ts
> +  };
`EditorFontType`変え忘れかも？
```suggestion
  SET_EDITOR_FONT: {
    mutation: { editorFont: EditorFontType  };
    action(payload: { editorFont: EditorFontType  }): void;
  };
```

2022-12-23 17:23 UTC, Hiroshiba requested changes
あすみません、テストが落ちていました！
https://github.com/VOICEVOX/voicevox/pull/1061/files#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291fL195

2022-12-23 23:28 UTC, sevenc-nanashi commented
https://mplusfonts.github.io/#license
M+自体はOFLなのでpublicあたりに入れてもいいかもしれません。MediumとBoldだと7MBくらい。

2022-12-24 22:27 UTC, Hiroshiba reviewed
> Rounded M+自体は再配布自由なので

本当ですね！！なんで`-1c`だけnpmにあるんだろう。
可能なら`rounded 1p`にできるととても嬉しいです･･･！！！！！

2022-12-24 22:27 UTC, Hiroshiba commented on src/background.ts
> +        },
消し忘れかも？

2022-12-24 23:00 UTC, sevenc-nanashi commented
1pにしてみましたー。

2022-12-24 23:38 UTC, Hiroshiba approved these changes
LGTM！！

良いですね！！！webの方もRounded M+ 1pに変えたいなと思いました！

<details>

![image](https://user-images.githubusercontent.com/4987327/209453298-9b068605-c3ab-4935-a34a-8fdb6dd673c4.png)

</details>

2022-12-24 23:38 UTC, Hiroshiba commented on package-lock.json
> +    "node_modules/encoding": {
package.jsonが変わってないのでlockも変更無いはず？

2022-12-25 00:46 UTC, sevenc-nanashi commented on package-lock.json
> +    "node_modules/encoding": {
変更を戻しましたー。

2022-12-25 16:04 UTC, Hiroshiba commented
CSS辺りちょっと自信なかったりするので、@MT224244 さんか @y-chan さんにもレビュー頂けると心強いです！

2023-01-02 05:59 UTC, y-chan approved these changes
LGTMです！
もう少しVueらしい書き方ができないものか調べてみましたが、良さそうな書き方が分からなかったので、とりあえずこれで良いと思いました...!

2023-01-02 17:26 UTC, merged