複数エンジン対応: テキスト読み込みを複数エンジンに対応
VOICEVOX/voicevox pull request #1119
Opened 2023-01-17 14:17 UTC by sabonerune

## 内容

テキストファイルの読み込み機能が複数エンジンに対応できていなかったので対応させました。
また、テキストファイルの読み込みに利用している`DEFAULT_STYLE_IDS`にEngineIDが追加されていませんでしたので追加しました。

## その他

とりあえず急ぎで対応させたので無駄が多いかもしれません。

2023-01-17 14:27 UTC, sabonerune commented on src/background.ts
> +      const engineId = "074fc39e-678b-4c13-8916-ffca8d505d1d";
EngineIDはハードコートした。

2023-01-17 14:27 UTC, sabonerune commented on src/type/preload.ts
> +        engineId: z.string().uuid().optional(),
マイグレーション前にバリテーションが実行されているのでoptionalにしている。

2023-01-17 20:23 UTC, Hiroshiba commented on src/background.ts
> +      const engineId = "074fc39e-678b-4c13-8916-ffca8d505d1d";
うおー･･･こんなとこにも影響が･･･なかなか辛いですね･･･。
可能ならハードコーディングを避けたくはありますが･･･。

一応`DEFAULT_ENGINE_INFOS`からuuidを得る方法があるのですが、このパースは`EngineManager`インスタンスが必要で、`EngineManager`は`store`が必要ですね･･･。
https://github.com/VOICEVOX/voicevox/blob/4a84ac75f9e19468a33d221bfdcde484d66501d1/src/background/engineManager.ts#L32-L45

雑に`DEFAULT_ENGINE_INFOS`から`uuid`取得しちゃって、本当は`EngineManager`から得たい旨をFIXMEコメント書くとか･･･どうでしょう･･･。

2023-01-17 20:37 UTC, Hiroshiba commented on src/store/audio.ts
> +      engineId: lastStyle.engineId,
あーーーなぜデフォルトスタイルIDにエンジンIDをと思っていたのですが、ここにengineIdが必要だからなんですね！！

`userOrderedCharacterInfos`の`CharacterInfo`のプロパティの`StyleInfo`にはengineIdが含まれています。
https://github.com/VOICEVOX/voicevox/blob/21ff14121d80f2c3fbb9bd215539404716f73902/src/type/preload.ts#L196-L203

とりあえずこれ使えば影響範囲をこの関数だけにできるので相当簡単になるかなと！！

2023-01-17 20:38 UTC, Hiroshiba reviewed
あ、プルリクありがとうございます！！

2023-01-17 22:35 UTC, sabonerune commented on src/background.ts
> +      const engineId = "074fc39e-678b-4c13-8916-ffca8d505d1d";
`DEFAULT_ENGINE_INFOS`から適当に取得するように変更しました。

2023-01-17 23:05 UTC, sabonerune commented on src/store/audio.ts
> +      engineId: lastStyle.engineId,
確かに`CharacterInfo`から`engineId`は取れるのですが`SpeakerID`はエンジン間でも同じIDを持つのでどちらにしろエンジンIDが必要なのデフォルトスタイルIDにエンジンIDも入れる必要があるのではと。

2023-01-18 03:19 UTC, Hiroshiba commented on src/store/audio.ts
> +      engineId: lastStyle.engineId,
デフォルトスタイルIDにエンジンIDを入れるのは賛成なのです。
PRがデフォルトスタイルIDにエンジンID追加する実装とテキスト読み込み修正の２機能になっていて、後者だけならすぐマージできるけど、前者含めるとちょっと時間かかりそうという感じです。

実際に他の箇所もちょっとコメントしてみます！

2023-01-18 03:25 UTC, Hiroshiba commented on src/type/preload.ts
> +        engineId: z.string().uuid().optional(),
なるほどです。。。これはelectron-storeの仕様がニーズに合ってないですね。。

たぶんここの影響で↓の箇所で`as DefaultStyleId[]`が必要になってると思うので気になってます。
https://github.com/VOICEVOX/voicevox/pull/1119/files#diff-6617a8982092b70693d565d280deb361a2c860ca52f2a1d23f537ce5d276023bR163

全くきれいじゃないですが、`.default("")`だとかにしてとりあえずundefinableを弾くというのはどうでしょうか。。FIXMEコメントも付けて。。
この場合おそらくmigration部分は`engineId: defaultStyle.engineId ?? engineId,`ではなく`engineId: engineId,`にしないとバグる気がします。

2023-01-18 04:38 UTC, sabonerune commented on src/type/preload.ts
> +        engineId: z.string().uuid().optional(),
`.default("")`では通りませんでした。
代わりに[Nil UUID](https://www.npmjs.com/package/uuid#uuidnil)なら大丈夫そうです。
(もしくは`.uuid()`を抜くか)

2023-01-18 13:26 UTC, Hiroshiba approved these changes
LGTM！！！

@sevenc-nanashi さんもよかったら見て頂ければ！！

2023-01-18 14:17 UTC, sevenc-nanashi requested changes
主に細かいところの指摘です。

2023-01-18 14:17 UTC, sevenc-nanashi commented on src/store/audio.ts
>      // FIXME: engineIdの追加
```suggestion
```
engineIdを追加したので消しても良さそう。

2023-01-18 14:17 UTC, sevenc-nanashi commented on src/type/preload.ts
> +        engineId: z.string().uuid().default(NIL_UUID),
```suggestion
        engineId: z.string().uuid().or(z.literal("")).default(""),
```
これでもできそうです。

2023-01-18 15:32 UTC, sevenc-nanashi approved these changes
LGTM！

2023-01-18 15:32 UTC, sevenc-nanashi commented on src/store/audio.ts
>        throw new Error(`styleId is undefined. speakerUuid: ${uuid}`);
```suggestion
      throw new Error(`style is undefined. speakerUuid: ${uuid}`);
```

2023-01-18 16:30 UTC, Hiroshiba commented
レビューありがとうございます！！！

2023-01-18 16:31 UTC, merged