EngineIdをユニークな型にする
VOICEVOX/voicevox pull request #1172
Opened 2023-02-02 18:52 UTC by Hiroshiba

## 内容

EngineIdをただのstringからユニークな型（brand型）に変更します。
これによりRecordのキーなどの変数が厳密になり、コーディングミスを失くしやすくなるはず･･･！

## 関連 Issue

- https://github.com/VOICEVOX/voicevox/issues/1148

## その他

方針としては、string型になっていたところを全てEngineIdにしています。
またzod schemaが必要なとろろはengineIdSchemaを指定しています。

一部undefinableにする必要があり、throw Errorするロジック周りがたされていたりします。

2023-02-02 18:52 UTC, Hiroshiba commented on src/type/preload.ts
> +export const EngineId = (id: string): EngineId => engineIdSchema.parse(id);
ここがEngineIdの型定義している場所です。

2023-02-02 18:55 UTC, Hiroshiba commented
型周りに強い @Segu-g さん・ @yamachu さん、あと全体的に詳しい @y-chan さん辺りにレビュー頂けるととても心強いです 🙇‍♂️ 
（影響範囲が広いため、期間が長くなれば長くなるほど苦しくなってくる系なので、何卒････････！！！！ 🙇 🙇 🙇 ）

2023-02-05 09:25 UTC, Hiroshiba commented
- https://github.com/VOICEVOX/voicevox/pull/1092

が入ったあとに修正してマージが良さそう？

2023-02-06 20:55 UTC, Hiroshiba commented
#1092 が入ったmainをマージしました･･･！

2023-02-07 15:59 UTC, yamachu requested changes
とりあえず気になった個所としてはこんなものかなぁと
Mapの箇所はおいおい変えたいなぁと思う程度で今回変更は不要かなと思いますが、characterInfos辺りが意図通りなのかが気になりました

2023-02-07 15:59 UTC, yamachu commented on src/background.ts
> +        JSON.parse(process.env.DEFAULT_ENGINE_INFOS ?? "[]")[0].uuid
このPRの変更の影響ではないのですが、これってError吐きますよね…？

2023-02-07 15:59 UTC, yamachu commented on src/background/engineManager.ts
> +    for (const engineIdStr of Object.keys(this.engineProcessContainers)) {
あーこれKeysで取得すると `string` として扱われてしまうのか…
EngineId 型に変換する箇所は極力減らした方がいいなぁと思いつつも、そのために Map とかにすると他の変更も必要になりますね…
将来的に直したいかなぁという印象を受けました

2023-02-07 15:59 UTC, yamachu commented on src/components/EngineManageDialog.vue
> +        for (const idStr of Object.keys(engineInfos.value)) {
Mapが云々の話と関係があるやつ

2023-02-07 15:59 UTC, yamachu commented on src/store/setting.ts
> +      for (const [engineIdStr, engineSetting] of Object.entries(
ここもMapが云々の話

2023-02-07 15:59 UTC, yamachu commented on src/components/LibraryPolicy.vue
>        Object.entries(store.state.characterInfos).map(
型見る感じ単純なstringとして扱ってそうに見えたけれども、ここの変更は意図通りですか？
あと実際に動かしていないのですが、symbolを付けたstring（すなわちEngineIdですが）を再度EngineIdコンストラクタみたいなのを通すとどうなるんですか？（って質問しようとしてコード見たらzodでstringとして扱ってみたいな感じだったから、単純なtoString()が呼ばれて再度symbol付け直す感じなのかな…

2023-02-07 22:26 UTC, Hiroshiba commented on src/background.ts
> +        JSON.parse(process.env.DEFAULT_ENGINE_INFOS ?? "[]")[0].uuid
ほんとですね！！
undefinedのときわかりやすいエラーを吐くようにしました。

2023-02-07 22:38 UTC, Hiroshiba commented on src/components/LibraryPolicy.vue
>        Object.entries(store.state.characterInfos).map(
> 単純なstringとして扱ってそう

これってどこのことでしょうか 👀
`engineIdStr`であれば`EngineId`でラップしてるはず･･･？

> 再度EngineIdコンストラクタみたいなのを通すと

試してみた感じ同じ型になってそうでした！！
![image](https://user-images.githubusercontent.com/4987327/217382156-f9c24fb5-eee3-4848-87fe-708471f4fee0.png)

2023-02-07 22:40 UTC, Hiroshiba commented on src/background/engineManager.ts
> +    for (const engineIdStr of Object.keys(this.engineProcessContainers)) {
そうなんですよね･･･。
Mapにするにも.getでundefinableになったり、IPC通信の検証が要りそうだったりしたので今回はパスにしています。

f3b61599475cab5e347e37054b50ffe142836555 でFIXMEコメントを書いてみました。

2023-02-07 22:40 UTC, Hiroshiba commented on src/store/setting.ts
> +      for (const [engineIdStr, engineSetting] of Object.entries(
f3b61599475cab5e347e37054b50ffe142836555 でFIXMEコメントを書いてみました。

2023-02-07 22:40 UTC, Hiroshiba commented on src/components/EngineManageDialog.vue
> +        for (const idStr of Object.keys(engineInfos.value)) {
f3b61599475cab5e347e37054b50ffe142836555 でFIXMEコメントを書いてみました。

2023-02-07 22:41 UTC, Hiroshiba commented
レビューありがとうございます！！！

2023-02-08 10:15 UTC, yamachu commented on src/components/LibraryPolicy.vue
>        Object.entries(store.state.characterInfos).map(
https://github.com/VOICEVOX/voicevox/pull/1172/files#diff-0493b4f4568a8a79680f5058a82555a336c9956bb1b8599960410e8d8f23c15eR114

characterInfosのkeyがstringとして扱われてるのですよね
EngineIdがkeyなのであれば、これは型として表現した方がいいなと思ったのでした（ということで、types.tsの方の変更requestです）
コメントを付けた箇所は、よくわからないstringをEngineIdとして扱っているわけではなさそうなので、ここに関しては変更不要です（Object.entriesの弊害がまた出てしまったみたいな顔をしながら

2023-02-08 20:06 UTC, Hiroshiba commented on src/components/LibraryPolicy.vue
>        Object.entries(store.state.characterInfos).map(
あ、なるほどです！ほんとですね！！
stringに代入できてしまうんですね･･･。
`EngineId`になってなかったRecordがいくつかあったので一緒に直してみました！！

2023-02-09 10:37 UTC, yamachu approved these changes

2023-02-09 15:46 UTC, Hiroshiba reviewed
大丈夫だと思うのでマージします！！
（大丈夫じゃなくても致命的なエラーにはならないはず）

2023-02-09 15:46 UTC, merged