選択中のキャラが一番上に表示されるようにした
VOICEVOX/voicevox pull request #1176
Opened 2023-02-04 15:33 UTC by tunamaguro

## 内容
キャラ選択ダイアログを開いた時、現在のキャラがリストの一番上に来るようにしました。
これにより、ダイアログ下側のキャラをスクロールせずにスタイル変更できるようになります。

## 関連 Issue
ref #897 

## スクリーンショット・動画など
- 例1
![image](https://user-images.githubusercontent.com/79092292/216775256-23d69196-f292-4aaf-b358-ea71f96f3fee.png)

- 例2
![image](https://user-images.githubusercontent.com/79092292/216775935-5b78789c-b2c0-4c7f-8adc-753dfb31c4a9.png)

## その他
実装やクラス名が非常に残念な感じになってしまいました。お伝えいただければ修正いたします。

クラスを出し分けしているところは下にあったものをコピペしたので変数にまとめたほうが良いかもしれません。

2023-02-04 15:38 UTC, y-chan approved these changes
LGTM！

なるほど、CSSだけで制御できるのですね、これは初耳でした...!
TS側でキャラクターリストを操作することなく実装できていて、とても綺麗だと思いました！

2023-02-04 20:56 UTC, Hiroshiba reviewed
ほぼLGTMです！！
命名とロジックに関してコメントしてみました！！

以下ちょっと蛇足です。

CSSで解決するのはとても良いアイデアだなと思いました！
でもflexを足してorderで制御するとなると、quasarの仕様が変わったときに気づかないうちにバグっていそうだなと思いました。（こういうときにUIフレームワークは不便ですね。。）

まあそれでもquasarの仕様を捻じ曲げている部分は他にいくらでもあるし、別に良いのかなと判断しました。
もし将来quasarのバージョンを上げたとき、この仕様がなくなってないかを確認したいですね･･･！

2023-02-04 20:56 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +      <q-list style="min-width: max-content" class="item-container">
このコンポーネントはキャラリスト以外にもスタイルリストがあったりします。
このままだとどちらかわからないので、`character-item-container`とするのはどうでしょう 👀

2023-02-04 20:56 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +            'selected-row'
`selected-character-item`が全く同じロジックで使われていそうなので流用できるかも？

でも`selected-character-item`はスタイルリスト側でも使われていそうでした。
ついでに選択中のスタイルも一番上に表示されるようにしても良いかも･･･？
（となると`selected-character-item`は`selected-item`になるかも？）

2023-02-05 05:27 UTC, tunamaguro commented on src/components/CharacterButton.vue
> +      <q-list style="min-width: max-content" class="item-container">
確かに今の`item-container`だけだとわからなくなってしまいそうですね...
修正します!

2023-02-05 05:31 UTC, tunamaguro commented on src/components/CharacterButton.vue
> +            'selected-row'
ご指摘のようにロジックはコピペしただけなのでいい感じにして、他の用途でも扱えるようにしたいです。

もうちょっといい感じにする方法を考えてみます。

2023-02-05 06:04 UTC, tunamaguro commented
レビューありがとうございます!

上でご指摘いただいたように流用できるように、クラス出しわけで使っていたロジックを関数にまとめました。
私の実力だとこれが限界でした💧。

冷静に考えると、選択中のキャラが一番上に来たとしても下のような場合には結局遠いままだということに気づきました😇。
![image](https://user-images.githubusercontent.com/79092292/216804356-fe136b81-ccea-4c4b-8907-38f1ac2da2e3.png)

何かしらしたほうが良いとはとは思いますが、何もアイデアがでてきません。

2023-02-05 09:16 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +
あ、ここはVue独特な記法で、`computed`でラップする必要があったりします！
（computedでラップすることで`selectedCharacter`の値が変わった際に自動で再評価されます。）

たぶんこんな感じ･･･？
```suggestion
    const isSelectedItem = computed((characterInfo: CharacterInfo) =>
      selectedCharacter.value != undefined &&
      characterInfo.metas.speakerUuid ===
        selectedCharacter.value?.metas.speakerUuid;
    )

```

2023-02-05 09:19 UTC, Hiroshiba commented on src/components/CharacterButton.vue
>      background-color: rgba(colors.$primary-rgb, 0.2);
`.selected-row`、`.selected-character-item`と役割が被ってそうだなとちょっと思いました！
良い感じに統合しちゃうか、ちょっと難しそうだったら↓みたいな感じでコメント残しても良いかもと思いました。

```suggestion
  // 選択中のキャラを上にする
  .selected-row {
    order: -1;
  }

  .selected-character-item,
  .opened-character-item {
    background-color: rgba(colors.$primary-rgb, 0.2);
```

2023-02-05 09:22 UTC, Hiroshiba commented
> 選択中のキャラが一番上に来たとしても下のような場合には結局遠いまま

これはもう仕方ない感じしますね。。。 😇 
キャラ一覧の縦幅を縮めるか、はたまたフィルタリングや可能にするか･･･。

とりあえず頂いたプルリクは今の形が良さそうで、取り組むにしても別タスクかなと思いました！

2023-02-05 11:23 UTC, tunamaguro commented on src/components/CharacterButton.vue
> +
Vueに詳しくないのでよくわかっていないのですが、
```vue
const isSelectedItem = computed(
  (charcterInfo: CharacterInfo) =>
    selectedCharacter.value != undefined &&
    charcterInfo.metas.speakerUuid ===
      selectedCharacter.value?.metas.speakerUuid
);
```
👆だと関数が返せてないので、
```vue
const isSelectedItem = computed(
  () => (charcterInfo: CharacterInfo) =>
    selectedCharacter.value != undefined &&
    charcterInfo.metas.speakerUuid ===
      selectedCharacter.value?.metas.speakerUuid
);
```
こういう感じにしてみようと思います。
ただこれで正しくキャッシュされているかどうかわかってないです。~調べた限りだとキャッシュされてない~

2023-02-05 11:25 UTC, sevenc-nanashi commented on src/components/CharacterButton.vue
> +
computedは[算出プロパティ](https://ja.vuejs.org/guide/essentials/computed.html)ですね。
多分元のままであってると思います。

2023-02-05 11:32 UTC, tunamaguro commented on src/components/CharacterButton.vue
>      background-color: rgba(colors.$primary-rgb, 0.2);
いい感じの統合案を思いつかなかったので、ご提案のようにコメントを残すようにします。

2023-02-05 11:59 UTC, tunamaguro commented on src/components/CharacterButton.vue
> +
レビューありがとうございます!

sevenc-nanashiさんの教えてくださったページを見ると、
computedで包んで上げても特に変化なさそうです。
もとのやつをpushし直しておきます。

正直Vueなんにもわかってないので、教えていただけて非常に助かります。

2023-02-05 12:06 UTC, sevenc-nanashi requested changes

2023-02-05 12:06 UTC, sevenc-nanashi commented on src/components/CharacterButton.vue
> +
```suggestion
    const isSelectedItem = (characterInfo: CharacterInfo) =>
      selectedCharacter.value != undefined &&
      characterInfo.metas.speakerUuid ===
        selectedCharacter.value?.metas.speakerUuid;

```
Typoですね

2023-02-05 12:13 UTC, tunamaguro commented on src/components/CharacterButton.vue
> +
教えていただきありがとうございます!
全然気づいてませんでした...

2023-02-05 13:07 UTC, sevenc-nanashi approved these changes

2023-02-05 23:37 UTC, Hiroshiba commented on src/components/CharacterButton.vue
> +
あ！本当ですね、関数でした！！
実行回数なども見てみましたが同じだったので、普通に関数で良さそうに思いました！！

2023-02-05 23:41 UTC, Hiroshiba approved these changes
LGTM！！

混乱させる事を言ってしまってすみませんでした！！
PRありあとうございました、またぜひお待ちしています･･･････！！！

2023-02-05 23:41 UTC, merged