READMEにDiscordへの案内などを追加
VOICEVOX/voicevox pull request #1283
Opened 2023-04-08 15:05 UTC by Hiroshiba

## 内容

READMEにて、VOICEVOX非公式Discordサーバーへの案内を行います。
ついでにバッジもいくつか付けてみました。

## その他

現在Dicordサーバー管理の方にご連絡中です。

2023-04-08 15:32 UTC, sevenc-nanashi requested changes
ここも大文字にしたら統一感が出そう？

2023-04-08 15:32 UTC, sevenc-nanashi commented on README.md
> +[![releases](https://img.shields.io/github/v/release/VOICEVOX/voicevox_engine)](https://github.com/VOICEVOX/voicevox/releases)
```suggestion
[![releases](https://img.shields.io/github/v/release/VOICEVOX/voicevox_engine?label=Release)](https://github.com/VOICEVOX/voicevox/releases)
```

2023-04-08 19:55 UTC, Hiroshiba commented on README.md
> +[![releases](https://img.shields.io/github/v/release/VOICEVOX/voicevox_engine)](https://github.com/VOICEVOX/voicevox/releases)
たしかに。そもそもこの並びだとReleaseという単語がいらなそうなので省いちゃいますか！

2023-04-08 19:57 UTC, Hiroshiba commented on README.md
> +[![releases](https://img.shields.io/github/v/release/VOICEVOX/voicevox_engine)](https://github.com/VOICEVOX/voicevox/releases)
なにを表示してるかわからなくなったのでReleaseにしました。。 c044634

2023-04-08 19:57 UTC, Hiroshiba commented
許可頂いたのでdraft外します！

2023-04-08 22:25 UTC, sevenc-nanashi approved these changes

2023-04-09 15:29 UTC, Hiroshiba commented
レビューありがとうございます！！
エンジンとコアにも足すプルリクを出そうと思います。

2023-04-09 15:29 UTC, merged