[project-library-manage] 音声ライブラリ管理画面のモックを追加
VOICEVOX/voicevox pull request #1453
Opened 2023-08-01 21:08 UTC by y-chan

## 内容

題のとおりです。音声ライブラリ管理画面のモックを追加しました。
実際に音声ライブラリのインストールはできませんが、キャラ音声の試聴はできるようにしておきました。

## 関連 Issue

- https://github.com/VOICEVOX/voicevox_project/issues/21

## スクリーンショット・動画など

<img width="1331" alt="image" src="https://github.com/VOICEVOX/voicevox/assets/34832037/e0cdbd2d-9761-446b-a0ec-64bb6cced7a8">

## その他

動作確認に、音声ライブラリ管理機能を使えるようにしたSHAREVOXエンジンを使っています。
以下からダウンロードして使えます。
https://github.com/SHAREVOX/sharevox_engine/releases/tag/0.3.0-preview.1

2023-08-03 21:42 UTC, Hiroshiba commented
おつです！　ちょっと関連issueのとこに音声ライブラリのプロジェクトのリンクを貼っときました！

最近忙しいのとプルリクエストが多いのでちょっと見るのが遅れそうに感じています 🙇 

@sevenc-nanashi さん
もしよければプルリクエストを見ていただいて、何か気になるところとかあればコメントとかお願いできるとかなり心強いです･･･！
この辺バグがありそうとか、こういう感じにすると良さそうとか･･･！

2023-08-04 01:04 UTC, sevenc-nanashi requested changes
![image](https://github.com/VOICEVOX/voicevox/assets/59691627/88131286-107e-4276-a553-edb120cc3228)
![image](https://github.com/VOICEVOX/voicevox/assets/59691627/925dd9ac-9781-43a8-a2de-3208caae2ada)

背景が置かれる場合を考えると、少しpaddingを足した方が良いように思います。
また、タイトルを横に置くと改行で読みづらいのでこんな感じのほうが良いような気がしました（デザインはよく分かっていませんが）

2023-08-04 01:04 UTC, sevenc-nanashi commented on src/components/LibraryManageDialog.vue
> +      });
```suggestion

        const toPrimaryOrder = (library: BrandedDownloadableLibrary) => {
          const localLibrary = installedLibraries.value[engineId].find(
            (l) => l.uuid === library.uuid
          );
          // アップデート > 未インストール > インストール済み の順
          if (!localLibrary) {
            return 1;
          } else if (semver.gt(library.version, localLibrary?.version)) {
            return 2;
          } else {
            return 0;
          }
        };
        libraries.sort((a, b) => {
          return toPrimaryOrder(b) - toPrimaryOrder(a);
        });
```
（自分が書いたコードですが）
toPrimaryOrderは外側で定義出来ると思います。

2023-08-04 01:34 UTC, Hiroshiba commented on src/components/LibraryManageDialog.vue
ちょっと試してみたのですが無限ローディングになっちゃいました！

![image](https://github.com/VOICEVOX/voicevox/assets/4987327/c73c3d80-5dd1-45b6-bdfd-0c30883cc59b)

最初のエンジンに失敗すると後ろのエンジンが無限待機しちゃう･･･？

2023-08-04 01:38 UTC, Hiroshiba reviewed
試聴できました！！！！　良いですねー！！！！！！

このプルリクエストのゴールとしてはどこにしましょうか？
デザインもしっかりしてからマージするか、一旦デザイン周りは後回しにペンディングしてタスクリストなどに追加しといて一旦マージするかなどの選択肢はありそうです！

とりあえず気になったところとしては @sevenc-nanashi さんがおっしゃっていたところと、あとキャラクターをクリックした時に左にキャラクター欄が出て来るので、最初から何もない空間、あるいは一番左上のキャラクターが表示されていた方がユーザーが驚かないかなと思いました！

2023-08-04 01:48 UTC, Hiroshiba commented on src/components/LibraryManageDialog.vue
> +const engineIdsWithDownloadableLibraries = computed(() => {
ここの変数名難しいですね。。
言いたいことは「ライブラリ管理機能があるエンジンIDの一覧」だと思うのですが、長い。。

`targetEngineIds`とかにして、コメントで`ライブラリ管理機能があるエンジンIDの一覧`とかと案内する手もあるかもと思いました。
（でも最高に良いアイデアでもないので、そのままでも！！）

2023-08-04 01:49 UTC, Hiroshiba commented on src/components/LibraryManageDialog.vue
> +const portraitUri = ref("");
ここもundefinedableにしといた方が個人的には安全かなと思いました！
実装はめんどくさいですが、ミスを防げるので。

2023-08-04 02:06 UTC, Hiroshiba commented on src/store/type.ts
> +  initOverrides?: Parameters<IEngineConnectorFactoryActions[K]>[1]
ちょっと全然わかってないんですがこれって何をされてる感じでしたっけ 👀

2023-08-04 02:09 UTC, Hiroshiba commented on src/components/LibraryManageDialog.vue
> +audio.onended = () => stop();
この辺り同じこと他の2つくらいのダイアログでもやってる気がするので、いつか共通化したいですね 😇 
issueだけでも作ってもいいかもしれない。。

2023-08-04 08:36 UTC, y-chan commented on src/components/CharacterTryListenCard.vue
> +      [key: string]: unknown;
なくても型エラーは出ていないのですが、一応その拡張のobjectが来ることを明示したくてこの型を拡張しておきました。
不必要というのはそうなのですが、意味的にあったほうがいいと思ったので書き足しました。
コメントは不要と思ったので書かなかったのですが、書いたほうがいいと思いますか...?

2023-08-04 08:37 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +          } as StyleInfo;
おっと！気づけませんでした！
ありがとうございます...!

2023-08-04 08:40 UTC, y-chan commented on src/components/LibraryManageDialog.vue
これなんですが、コンポーネントを分けるとplay/stopあたりでprops/emitsがとても複雑になりそうだったので、一つのコンポーネントに統合しました。
今のところOptionalはなかったと思いますがどこかありましたっけ...?

2023-08-04 08:44 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +      });
そうですね、たしかに内部に入れる必要はなさそうです。

まあでも引数が複雑化しそうなので、提案してもらった階層のままでいいかなと...!(ここ以外で使う予定はないと思うので、汎用性を上げる必要はないかなと思いました)

2023-08-04 08:45 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +const engineIdsWithDownloadableLibraries = computed(() => {
うーん、たしかに変数名が長いのは少し気になりました。
`targetEngineIds`でコメントがとりあえずはいい気がしました...!

2023-08-04 08:46 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +const portraitUri = ref("");
そうですね、そうしたいと思います...!

2023-08-04 08:48 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +  }
ここの条件は握り潰しではなく、あり得る条件ですね。
「インストールされていないが、これからインストール予定のライブラリ」がlatestではないのは自明なので、この形は問題ないはずです。

2023-08-04 08:50 UTC, y-chan commented on src/store/type.ts
> +  initOverrides?: Parameters<IEngineConnectorFactoryActions[K]>[1]
あ、これは直接的に関係のない変更を取り込んじゃっていますね....
ライブラリインストール時、zipファイルをbodyとしてpostリクエストを投げるんですが、bodyを指定するために`initOverrides`の引数が必要だったので、そこを付け足しましたが、今回のPRの中では使いませんでした。
とりあえずrevertしておきます！

2023-08-04 08:52 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +audio.onended = () => stop();
そうですね...Issue作ってみます...!

2023-08-04 08:52 UTC, sevenc-nanashi commented on src/components/LibraryManageDialog.vue
> +        .then((libraryEndpoints): [
```suggestion
        .then([fetchedDownloadableLibraries, fetchedInstalledLibraries]): [
```
こんな感じにすれば`[0]`とかをなくせて読みやすい気がします。

2023-08-04 08:55 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +audio.onended = () => stop();
そうですね、Issue作ってみました！
今回は一旦無視したいと思います...

2023-08-04 09:01 UTC, y-chan commented
デザイン、名無しさんが挙げられている形が一番すっきりしているように見えました...!

せっかくなのでこのPRでデザインまでやっちゃおうと思います...!

2023-08-04 22:57 UTC, sevenc-nanashi approved these changes
LGTM！

2023-08-04 22:57 UTC, sevenc-nanashi commented on src/components/LibraryManageDialog.vue
> +                            : `インストール`
```suggestion
                            ? "最新版です"
                            : installedLibraries[engineId].find(
                                (installedLibrary) =>
                                  installedLibrary.uuid === library.uuid
                              )
                            ? "アップデート"
                            : "インストール"
```
揃ってないのが少し変だったので。

2023-08-04 23:27 UTC, y-chan commented on src/components/LibraryManageDialog.vue
> +                            : `インストール`
あれ、なんででしょう...w
suggest取り込みます:pray:

2023-08-05 02:57 UTC, Hiroshiba commented on src/components/CharacterTryListenCard.vue
> +      [key: string]: unknown;
TypeScriptって余計なキーが含まれていても問題ないんですね･･･。
なんかそもそもTypeScriptのそこが微妙な気がしました 😇

2023-08-05 03:17 UTC, Hiroshiba commented on src/components/LibraryManageDialog.vue
> +  }
なるほどです！　良いと思います！

ただの気づきですが、状態（latest/installed/notIntalled）と可能なアクション（update/uninstall/install）があって、この2つを変換するだけの関数があると、その関数のテストが書けるんだなーと思いました。
今は状態からアクションの変換をtemplate内でやってるから、状態からレンダリングのテストを統合的に行うテストになるなーと。

2023-08-05 03:38 UTC, Hiroshiba approved these changes
LGTM！！！！

UI面に関して、今は横スクロールでいろんなキャラクターが表示されるようになっていますが、折り返して全キャラが表示されるようになってもいいかもと思いました。
ただ実際はもっともっと数が並ぶはずで、その時にどうなるかわからないので、今は一旦この形がベストなのかなと感じました！

キャラクター表示欄のところ、誰も選択されていない状態で無を表示することを提案しましたが、実際見てみるとさすがに何も表示されてないのはよくないのかもしれないとちょっと思いました。。。
最終的なデザインの調整で @y-chan さんの最初のプルリクエストの感じに戻させていただくかもしれません。すいません。。 🙇 
（一番左上のキャラクターの自動選択が可能そうだったらそっちにしたみです）

2023-08-05 03:38 UTC, merged