デフォルトスタイルページのデザイン変更
VOICEVOX/voicevox pull request #1556
Opened 2023-09-16 06:13 UTC by kebin628

## 内容
デフォルトスタイルの変更ページのレイアウトを

- 名前太字
- スタイルそのまま
- 全スタイル数縮小

で変更。

## 関連 Issue
ref #1512

## スクリーンショット・動画など
![image](https://github.com/VOICEVOX/voicevox/assets/36288369/c2333245-a656-47c7-879d-4c0f58d0aacd)

## その他

2023-09-16 07:14 UTC, sevenc-nanashi requested changes

2023-09-16 07:14 UTC, sevenc-nanashi commented on src/components/DefaultStyleListDialog.vue
> +                    style="font-weight: bold; margin-bottom: 20px"
QuasarのCSSが使えるかも知れません： https://quasar.dev/style/spacing#introduction https://quasar.dev/style/typography#font-weights

2023-09-16 07:14 UTC, sevenc-nanashi commented on src/components/DefaultStyleListDialog.vue
> +                    ><span style="font-size: 0.8rem"
同上。text-captionあたり？

2023-09-16 09:02 UTC, kebin628 commented
![image](https://github.com/VOICEVOX/voicevox/assets/36288369/ba7c7e88-1ef3-48fd-bb57-6a027f2716e1)

QUASAR？が初めてだったのですが、これで指定する形で合っていますでしょうか？
指定方法少し変わったので誤差ですがマージン等が微妙に変わっています。

2023-09-16 09:14 UTC, sevenc-nanashi approved these changes
LGTM！

2023-09-18 00:31 UTC, Hiroshiba approved these changes
LGTM！！！
プルリクエストありがとうございました！やり取り含め全く問題なかったように感じました。

ちょっとマージン幅などを変えさせていただこうと思います！
こんな感じになる予定です。
![image](https://github.com/VOICEVOX/voicevox/assets/4987327/6865e729-d924-4bcd-a740-fd035ad6a4a1)

また別のプルリクエストももしよかったら是非！！

2023-09-18 00:35 UTC, merged