undefinedとnullの厳密比較を禁止する設定を追加
VOICEVOX/voicevox pull request #1585
Opened 2023-09-25 16:03 UTC by Tksn07

## 内容

↓ こちらのissueを修正したPRになります。
- https://github.com/VOICEVOX/voicevox/issues/1513

eslintにundefinedとnullの厳密比較を禁止する設定を追加しました。

下記のコードを、main.tsなどに張り付けていただければ確認できます。
```ts
const fuga = "null";
const a = fuga != undefined; // OK
const a_1 = fuga !== undefined; // NG

const b = fuga == undefined; // OK
const b_1 = fuga === undefined; // NG

const c = fuga != null; // OK
const c_2 = fuga !== null; // NG

const d = fuga == null; // OK
const d_2 = fuga === null; // NG

const e = "fuga" == undefined; // OK
const e_2 = "fuga" === undefined; // NG

const button = { text: null };

const f = button.text == null; // OK
const f_2 = button.text === null; // NG

const g = "fuga" == null; // OK
const g_2 = "fuga" === null; // NG
```

## 関連 Issue
ref #1513

## スクリーンショット・動画など

![image](https://github.com/VOICEVOX/voicevox/assets/38491690/67ff2429-f246-4957-8541-6e43170ab976)

## その他

初めてOSSにPRを切らせていただきました。
何かやり方が間違っているなどあれば教えていただけると幸いです🙇

2023-09-25 20:47 UTC, sevenc-nanashi requested changes

2023-09-25 20:47 UTC, sevenc-nanashi commented on .eslintrc.js
> +        message: "Don't use '!== null'. Use '== null' instead.",
```suggestion
        message: "Don't use '!== null'. Use '!= null' instead.",
```
間違いかも

2023-09-25 20:47 UTC, sevenc-nanashi commented on .eslintrc.js
> +        message: "Don't use '!== undefined'. Use '== undefined' instead.",
```suggestion
        message: "Don't use '!== undefined'. Use '!= undefined' instead.",
```

2023-09-26 13:01 UTC, Tksn07 commented on .eslintrc.js
> +        message: "Don't use '!== null'. Use '== null' instead.",
指摘ありがとうございます🙇
修正完了しました！

2023-09-26 13:17 UTC, sevenc-nanashi commented
うーん、どうなんでしょう？ @Hiroshiba 

個人的にはmainのCIは全部通るようにしておきたいのでこのPRでやっちゃってもいいと思いますが、ヒホさんの判断優先でお願いします。

（ちなみに、suggestionの「Commit Suggestion」を押すといい感じにやってくれます、レビューの解決とかCo-Author登録とか）

2023-09-26 16:47 UTC, Hiroshiba commented
エラー量見てみました、確かに凄まじい数ですね･･･。
ESlintで出ているエラーをinfoあるいは警告にして、mainブランチにマージするというのはどうでしょう？

2023-09-26 16:51 UTC, Hiroshiba reviewed
ちょっと別のコメントなんですが、nullやundefinedと比較していなさそうなのにエラーになっている例がかなりあるかもしれません。

例えばこちらとか･･･。
https://github.com/VOICEVOX/voicevox/pull/1585/files#file-src-background-ts-L361
（`const COMBINATION_IS_NONE = "####";`です）

これ、なんか直感的にかなり難しい問題な気がしました 😇

2023-09-27 03:13 UTC, Tksn07 commented
@Hiroshiba @sevenc-nanashi 見てくださりありがとうございます🙇‍♂️
ESLintのerrorをinfoかwarningにするのは良いと思います！
ESLintのエラー自体は{ off, warning, error } の3つなので、`warning` を採用する形で進めようと思います🙌
https://eslint.org/docs/latest/use/configure/rules#rule-severities

また、こちらに関してですが、

> ちょっと別のコメントなんですが、nullやundefinedと比較していなさそうなのにエラーになっている例がかなりあるかもしれません。
> 
> 例えばこちらとか･･･。 https://github.com/VOICEVOX/voicevox/pull/1585/files#file-src-background-ts-L361 （`const COMBINATION_IS_NONE = "####";`です）
> 
> これ、なんか直感的にかなり難しい問題な気がしました 😇

自分の方で調べてみてもなぜこれがエラーになるのかの原因を特定することはできませんでした😇
(恐らくESLint側の内部的なバグと思われる)

その対処法として今回のissueの対応では、
`=== null`, `=== undefined` などの厳密比較に対して右辺にundefined, null 持って来るケースに対応したい。という内容なので、

```
（変更前）selector: "BinaryExpression[operator='==='][right.value=undefined]",
（変更後）selector: "BinaryExpression[operator='==='][right.name=undefined]",
```
といった、`right.value -> right.name` にして対応する方針でどうでしょうか？

nameになるので、
```
const undefined = "test"
const null = "test"
```
などもエラーになりますが、予約語であり別の制約に引っかかるのでnameにしても問題なさそうと考えています👀

2023-09-27 04:55 UTC, Hiroshiba commented
> ESLintのエラー自体は{ off, warning, error } の3つなので、warning を採用する形で進めようと思います🙌
[eslint.org/docs/latest/use/configure/rules#rule-severities](https://eslint.org/docs/latest/use/configure/rules#rule-severities)

おお、なるほどです！！良さそうに感じました！

2023-09-27 04:56 UTC, Hiroshiba commented
> といった、right.value -> right.name にして対応する方針でどうでしょうか？

これで試してみたのですが、まだ誤検知があるようでした。
ちょっと気になったのでいろいろ試してみて、これでどうだろうというのを考えてみたので別でコメントします！

便利なあれこれ見つけたのでメモです。

このツールが便利でした。 [esquery](https://estools.github.io/esquery/)

検出したい対象と、検出したくない対象のいろいろです。
```ts
// 検出対象
const a = 0 === undefined;
const aa = 0 === null;

const fuga = "null";
const a = fuga === undefined;

const b = "fuga" === undefined;

const button = { text: null };
const c = button.text === null;

const d = "fuga" === null;

const e = accentPhrase.pauseMora === null

// 非検出対象
const COMBINATION_IS_NONE = "####";
const b = 0 === COMBINATION_IS_NONE;

const c = loadedHotkey.action === defaultHotkey.action
```

2023-09-27 04:56 UTC, k-chop commented
（横から突然すみません）

![ss1](https://github.com/VOICEVOX/voicevox/assets/241973/08072404-7a44-4ebb-bb07-de9eca2e6fbc)
`[right.value=undefined]` の `undefined` を `'` でくくってないので、`right` に `value` が存在しないケースにひっかかっているんだと思います。

nullとundefinedのASTはそれぞれこんな感じなので、
nullはtype=literal, value=null、undefinedはtype=Identifier, name=identifier を見てあげるとよさそうです
![ss2](https://github.com/VOICEVOX/voicevox/assets/241973/adb70a90-e475-4cf5-80eb-4f0735334fda)
![ss3](https://github.com/VOICEVOX/voicevox/assets/241973/25b20aab-0502-4177-a959-8b0eed24c43e)

2023-09-27 05:02 UTC, Hiroshiba commented on .eslintrc.js
> +      },
誤検知がありそうだったのでこういうのでどうでしょうというのを提案してみます！

```suggestion
      {
        selector:
          "BinaryExpression[operator='==='][right.type='Literal'][right.value=null]",
        message:
          "'=== null'ではなく'== null'を使用してください。詳細 https://github.com/VOICEVOX/voicevox/issues/1513",
      },
      {
        selector:
          "BinaryExpression[operator='!=='][right.type='Literal'][right.value=null]",
        message:
          "'!== null'ではなく'!= null'を使用してください。詳細 https://github.com/VOICEVOX/voicevox/issues/1513",
      },
      {
        selector:
          "BinaryExpression[operator='==='][right.type='Identifier'][right.name=undefined]",
        message:
          "'=== undefined'ではなく'== undefined'を使用してください。詳細 https://github.com/VOICEVOX/voicevox/issues/1513",
      },
      {
        selector:
          "BinaryExpression[operator='!=='][right.type='Identifier'][right.name=undefined]",
        message:
          "'!== undefined'ではなく'!= undefined'を使用してください。詳細 https://github.com/VOICEVOX/voicevox/issues/1513",
      },
```

ちゃんとよくわかってないのですが、typeによって`.name`や`.value`プロパティがあったりなかったりするっぽく、そのプロパティがなくても`==undefined`になってしまうっぽい気がしました。
なので右辺のtypeも絞ることによって問題が起きないようにしてみた感じです！

あとメッセージから意図を辿れるよう、issueへのリンクを張ってみました。
とりあえず参考までにということで･･･！

2023-09-27 05:06 UTC, Hiroshiba commented
@k-chop おおなるほどです！！！！！詳しくありがとうございます！！！

2023-09-27 13:37 UTC, Tksn07 commented
@k-chop おぉぉぉぉ！！こんな便利ツールがあるんですね！！！
教えてくださりありがとうございます！！

2023-09-27 13:49 UTC, Tksn07 commented on .eslintrc.js
> +      },
typeも追加して絞るの良いですね！アドバイスありがとうございます🙇
追加してローカルで確認してみたところ、誤検知無く、エラーを出したい箇所にwarningを出してくれていたのでそちらに修正を進めさせていただきました🙏

2023-09-27 17:27 UTC, Hiroshiba approved these changes
LGTM！！！

プルリクエストの` Files changed`の下にワーニングが大量に出ていますが、今しばらくは無視する形で良いのかなと思いました！

まだ禁止する（エラーにする）ところまで到達していないので、元のissueはopenのままにしておこうと思います。

@Tksn07 さん
初のプルリクエストありがとうございました！！（ちなみに問題は全くなかったです！）
もしよかったらまたプルリクエストをいただけるととても嬉しいです！
ワーニングを消していくとか、是非･･･！

2023-09-27 17:27 UTC, merged