エディターのメイン画面でアップデートを通知する
VOICEVOX/voicevox pull request #1616
Opened 2023-10-22 07:55 UTC by liszt01

## 内容

エディターを起動したときに（新しいバージョンがあれば）アップデートを通知します。

## 関連 Issue

ref #235 

## スクリーンショット・動画など

https://github.com/VOICEVOX/voicevox/assets/61107001/3b56da50-a3e3-4c32-9f42-179d4585f493

## その他

アップデート通知ダイアログをコンポーネントにして `EditoHome.vue` に追加してみたのですが、わざわざコンポーネントにするのではなく `SHOW_CONFIRM_DIALOG` や `SHOW_NOTIFY_AND_NOT_SHOW_AGAIN_BUTTON` を使ったほうがいい気がしています。

また、設定でアップデートを通知するかどうか変更できるようにしたほうがいいとも思っています。

2023-10-22 18:30 UTC, Hiroshiba requested changes
（コメントしようとしたら間違えて`requested changes`にしてしまいました！）

良い感じだと思います！！！
ちょっとこちらでデザインは調整させていただくことになるかもです、ご了承いただければ！

> アップデート通知ダイアログをコンポーネントにして EditoHome.vue に追加してみたのですが、わざわざコンポーネントにするのではなく SHOW_CONFIRM_DIALOG や SHOW_NOTIFY_AND_NOT_SHOW_AGAIN_BUTTON を使ったほうがいい気がしています。

よくある「このバージョンをスキップする」ボタンや、あるいは今のバージョンから最新バージョンまででどのような変更が行われるかのリストを表示するなど、ちょっと一般的じゃないダイアログを表示したくなるような気がしています。
であれば今のうちから一般的じゃないダイアログでもいいかもと思いました。

ただまあ今の機能であれば`SHOW_CONFIRM_DIALOG`でも良いかもです。
どちらでもやりやすいように、という感じです！！

> また、設定でアップデートを通知するかどうか変更できるようにしたほうがいいとも思っています（まだ実現できていませんが）。

よくあるのは「このバージョンをスキップする」ボタンでしょうか。
スキップする＝二度と表示しないなので、一度見たTipsを二度と表示しないようにするための[`ConfirmedTips`](https://github.com/VOICEVOX/voicevox/blob/87630200ae7d2ea854210e020140753a02dcfe06/src/type/preload.ts#L506)があって、機能的には近いかもです。
ただこっちは用意されているものだけに対応しているので、どの最新バージョンが来るかわからないバージョンスキップ機能の場合はちょっと実装を変える必要があるかもです。

一旦このプルリクエスト内では最新版があったら何度もダイアログを表示するという仕様にしておいて、後のプルリクエストでスキップできるように目指してみる（あるいはやってみて難しかったら他の方に任せる）というのはどうでしょう？

2023-10-22 18:30 UTC, Hiroshiba commented on src/components/UpdateNotificationDialog.vue
> +  <q-dialog v-if="isUpdateAvailable" v-model="showDialog">
あ、ちょっとお伝えし忘れてたのですが、[`useDialogPluginComponent`](https://github.com/VOICEVOX/voicevox/blob/87630200ae7d2ea854210e020140753a02dcfe06/src/components/SaveAllResultDialog.vue#L92)が便利かもしれません。
（このままでも問題ないです！）

2023-10-22 18:30 UTC, Hiroshiba commented on src/components/UpdateNotificationDialog.vue
> +const showDialog = ref<boolean>(true);
必ず通知されるようになってるかも･･･？

2023-10-23 05:02 UTC, liszt01 commented
コメントありがとうございます！

> よくある「このバージョンをスキップする」ボタンや、あるいは今のバージョンから最新バージョンまででどのような変更が行われるかのリストを表示するなど、ちょっと一般的じゃないダイアログを表示したくなるような気がしています。

せっかくなので、どのような変更があったか表示できるようにしたいと思います！
ヘルプ / アップデート情報の変更履歴を表示しているところを参考にやってみます。
https://github.com/VOICEVOX/voicevox/blob/87630200ae7d2ea854210e020140753a02dcfe06/src/components/help/UpdateInfo.vue#L16C11-L21C22
<br />

>> また、設定でアップデートを通知するかどうか変更できるようにしたほうがいいとも思っています（まだ実現できていませんが）。

この機能は #543 のコメントにある、

> また、アップデート通知をonにするか、offにするかの機能が少しほしいなと思いました。
> background.tsで処理しており、electron-storeの情報が利用できると思うので、SettingDialog.vueの中に、その設定を盛り込んで、利用してもいいかなと思いました。
> ただ、これはあくまで拡張的な内容なので、別PRに切り分けた方が良さそうです。

を想定していました。設定 / オプションに、アップデート通知の on/off を切り替える項目を追加しようかなと。
「off にしていれば、新しいバージョンがあっても通知されない」という感じです。
以下のように変更しようと考えています。

```typescript
// components/UpdateNotificationDialog.vue
const showDialog = ref<boolean>(true);
→ const showDialog = computed(() => store.state.NotifyUpdate);
```
<br />

「このバージョンをスキップする」ボタンは私には難易度が高そうなので他の方にお願いしようと思います。。

2023-10-23 16:21 UTC, Hiroshiba commented
> > よくある「このバージョンをスキップする」ボタンや、
> 
> せっかくなので、どのような変更があったか表示できるようにしたいと思います！

了解です！！是非！！
最新の更新情報を取得する必要があると思います。こちらのURLで管理しているのでお使いいただければ！
https://raw.githubusercontent.com/VOICEVOX/voicevox_blog/master/src/data/updateInfos.json

このリポジトリをフォークして使っている方のために、このURLは`.env`ファイルなどで指定可能にするのが良さそうです。
もしよかったらここの[`VITE_APP_NAME`](https://github.com/VOICEVOX/voicevox/blob/87630200ae7d2ea854210e020140753a02dcfe06/.env.production#L1)みたいな感じで`VITE_LATEST_UPDATE_INFOS_URL`を定義するとかしていただけると嬉しいです！
（ちなみに`VITE_`をつけるのが大事です。`VITE_APP_NAME`を全体検索すればどうやったら使えるか分かりやすいかもです。難しかったらまあそのままでも！）

> 設定 / オプションに、アップデート通知の on/off を切り替える項目を追加しようかなと。
> 「off にしていれば、新しいバージョンがあっても通知されない」という感じです。

なるほどです！
「このバージョンをスキップする」機能があればあまりオフにしたくならないのかもとちょっとだけ思いましたがどうでしょうか？
（そうしてくださいという意図ではなく、あった方が良いかなかった方が良いか判断を迷っていて、ちょっとご意見聞いてみたい感じです！）

実装する場合は設定の「高度な設定」あたりに属するかなと思いました。
「音声をステレオ化」のコードがとても参考になるかもです！

2023-10-24 14:01 UTC, liszt01 commented
> https://raw.githubusercontent.com/VOICEVOX/voicevox_blog/master/src/data/updateInfos.json
> このリポジトリをフォークして使っている方のために、このURLを`.env`ファイルなどで指定可能にするのはどうでしょう？

すみません、、この文の意図が掴めなかったので具体的に教えていただきたいです。
最新の更新情報を取得する分には `GET_UPDATE_INFOS` でできるようですが、「URL」が必要になる場面があるということでしょうか？
[更新情報を取得している例 (HelpDialog.vue)](https://github.com/VOICEVOX/voicevox/blob/a80def6c0840e8617463ce13a6aafffda756e4f0/src/components/help/HelpDialog.vue#L131C1-L132C77)
<br />

> 「このバージョンをスキップする」機能があればあまりオフにしたくならないのかもとちょっとだけ思いましたがどうでしょうか？

「このバージョンをスキップする」ボタンには個人的に馴染みがなく、どういうものなのか分かっていないです。
例えば、

最新バージョン 0.14.9 が利用できます！と通知された場合に「スキップする」と以後エディタを立ち上げても再度通知されることはない。
この状態で、最新バージョン 0.14.10 が公開された場合は、再び通知する（最新バージョン 0.14.10 が利用できます！）。

ということでしょうか？
<br />

on/off 機能について改めて考えてみたのですが、以下の問題点を思いつきました。
- アップデート通知を off にしたまま、最新バージョンの存在すら忘れてしまう（更新できることを忘れてしまう）
- off にしていたアップデート通知を on にしようと思うタイミングがなさそう（アップデートする気になったのなら公式サイトに行くはず）

on/off 機能よりも「このバージョンをスキップする」ボタンのほうがアップデート通知の意義に沿っている機能な気がしてきました！

2023-10-24 17:34 UTC, Hiroshiba commented
> すみません、、この文の意図が掴めなかったので具体的に教えていただきたいです。

あ、なるほどです！
そちらのupdateInfosはアプリがビルドした時点での、そのバージョンの更新情報が入ってます。
https://github.com/VOICEVOX/voicevox/blob/aaf0576655a6d9866bfdfbb25ec27f97683d31f5/src/background.ts#L333-L337
最新の更新情報はネット上にしかないのでそれをダウンロードする必要があるかなという意図でした！ 🙇 

> > 「このバージョンをスキップする」機能があればあまりオフにしたくならないのかもとちょっとだけ思いましたがどうでしょうか？
> 
> 最新バージョン 0.14.9 が利用できます！と通知された場合に「スキップする」と以後エディタを立ち上げても再度通知されることはない。 この状態で、最新バージョン 0.14.10 が公開された場合は、再び通知する（最新バージョン 0.14.10 が利用できます！）。
> ということでしょうか？

ですです！たぶん想像している通りだと思います。

> on/off 機能よりも「このバージョンをスキップする」ボタンのほうがアップデート通知の意義に沿っている機能な気がしてきました！

実装した場合の課題点の洗い出しは手戻り防止になるのでありがたいです！！
「このバージョンをスキップする」機能も、スキップしたバージョンのリストをconfigに保存すれば完了なので、実装に興味があればお声かけいただければ！！

2023-10-26 16:15 UTC, liszt01 commented
アップデート通知ダイアログから最新バージョンの更新情報を見れるようにしました！

更新情報のURLに関してなのですが、`.env`で`VITE_LATEST_UPDATE_INFOS_URL`を定義して
```typescript
const latestUpdateInfosURL = import.meta.env.VITE_LATEST_UPDATE_INFOS_URL;
```
と書いたらundefinedになったので、仕方なくハードコードしています。。

2023-10-26 16:26 UTC, liszt01 commented on src/components/UpdateNotificationDialog.vue
> +const showDialog = ref<boolean>(true);
いまのところ、最新バージョンに更新できるのであれば毎回必ず通知するようになっています。
将来的には「このバージョンをスキップする」ボタンが押されたかどうか（の逆）をshowDialogの初期値としたいです。

2023-10-27 03:58 UTC, Hiroshiba commented
まだちょっとプルリクエスト完全に見られてないのですが、コメントだけ･･･！

> .envでVITE_LATEST_UPDATE_INFOS_URLを定義して

方針は完全に合ってそうなんですが、不思議ですね･･･。
型としてundefinedになっているということでしたら、↓ここも変えないといけないかもです！
https://github.com/VOICEVOX/voicevox/blob/0346b31020e3590a146f2dcc5980e088992ec16b/src/vite-env.d.ts

2023-10-27 04:31 UTC, Hiroshiba reviewed
良い感じの実装になってきていると思います！！！
もうひと押しでマージできるのかなという雰囲気を感じています、もうしばらくお付き合いいただければ 🙇

2023-10-27 04:31 UTC, Hiroshiba commented on src/views/EditorHome.vue
> +        <update-notification-dialog />
dialogの場所ですが、↓にいっぱいあるのでこの辺りに追加していただけると！ 
https://github.com/VOICEVOX/voicevox/blob/0346b31020e3590a146f2dcc5980e088992ec16b/src/views/EditorHome.vue#L159-L178

2023-10-27 04:31 UTC, Hiroshiba commented on src/components/UpdateNotificationDialog.vue
> +const showDialog = ref<boolean>(true);
あ、なるほどです！！`v-if="isUpdateAvailable"`が入っているのを見逃していました！

ちょっと相談したいことが･･･！

[既存でいろんなダイアログがある](https://github.com/VOICEVOX/voicevox/blob/0346b31020e3590a146f2dcc5980e088992ec16b/src/views/EditorHome.vue#L159-L178)のですが、それらの既存のダイアログは開くかどうかを外のコンポーネントが制御しています。
（`isHelpDialogOpenComputed`とかで）
このダイアログも同じように制御するというのはどうでしょう？
その場合おそらく`EditorHome.vue`内に`useFetchLatestVersion`などを移動し、`isUpdateAvailable`になったら`isUpdateNotificationDialogOpenComputed = true`にするなどの実装になるのかなと･･･！

今の実装でも間違っておらず、既存の実装に合わせて欲しいというわがままなお願いなのですが、もしよければ 🙇

2023-10-27 04:31 UTC, Hiroshiba commented on src/composables/useFetchLatestVersion.ts
> +    });
あ、これキャッチしてスローし直すのであれば省略しても同じ結果だったかと！

2023-10-28 03:17 UTC, liszt01 commented
ダイアログの制御を`EditorHome.vue`に移しました。


(ちなみに自分の環境だと、`VITE_APP_NAME`もundefinedになります)

2023-10-28 08:35 UTC, Hiroshiba commented
> (ちなみに自分の環境だと、`VITE_APP_NAME`もundefinedになります)

おっとなるほどです！なにか妙なことになってるかもですね…。
ファイル名は.envでしょうか？（.env.productionではなく）
そこ以外思い当たる点がないので、解決が難しそうであればこちらでコード変更させていただこうと思います！

2023-10-28 13:05 UTC, liszt01 commented
はい。.envで定義していました。

viteについて詳しくないのでそちらにお願いしたいです🙏

2023-10-29 16:35 UTC, Hiroshiba reviewed
ほぼLGTMです！！！！

ちょっとUI周りというかUX周りというかで、よりユーザービリティが高くなるような提案をいくつかしてみました！
もし良さそうなのあれば･･･！

これが完了し次第マージさせていただこうと思います！！

自分用メモ：表示をデバッグするときは、EditorHomeの`isUpdateAvailable`をtrueにし、`UpdateNotificationDialog.vue`の`semver.lt`を`gt`にする

2023-10-29 16:35 UTC, Hiroshiba commented on src/components/UpdateNotificationDialog.vue
> +          新しいバージョンが利用可能です。<br />
バージョン名を追加してもいいかも？

2023-10-29 16:35 UTC, Hiroshiba commented on src/components/UpdateNotificationDialog.vue
> +        />
詳細ダイアログを別表示する形だと、魅力的なアップデートがあったとしても気づかずに閉じちゃう人が現れてお互い損かもとちょっと思いました。
通知ダイアログの中にアップデート情報も表示してしまうのはどうでしょう？
`<div class="scrollable-area">`の内容をこちらのダイアログ内に移行する感じかなと･･･！

2023-10-29 16:35 UTC, Hiroshiba commented on src/composables/useFetchLatestVersion.ts
> +  const latestVersion = ref("");
これ元々のコードがそうだった形なのですが、より分かりやすくしておくのも良いかもですね。
`latestVersion`（最新バージョン）はどっちかというと`newerLatestVersion`（より新しい最新バージョン）のがあってるかも？

まあそこ変更するのは大変かもなので、こんな感じでドキュメントに追加しておくのはどうでしょう！
```suggestion
// 最新版があるか調べる
// 現バージョンより新しい最新版があれば`latestVersion`に代入される
export const useFetchLatestVersion = () => {
  const isCheckingFinished = ref<boolean>(false);
  const currentVersion = ref("");
  const latestVersion = ref("");
```

2023-10-29 16:35 UTC, Hiroshiba commented on src/composables/useFetchLatestVersion.ts
> +  fetch(
すみません、なんか忘れちゃいそうな気がするのでTODOコメントだけお願いしても良いでしょうか 🙇 
```suggestion
  // TODO: 環境変数で変えられるようにする
  fetch(
```

2023-11-02 04:11 UTC, liszt01 commented
アップデート内容を通知ダイアログに直接表示するようにしました！

2023-11-03 07:31 UTC, Hiroshiba approved these changes
LGTM！！！

色々な調整ありがとうございました！！
進行がとてもスムーズで非常にやりやすかったです！！

バージョンごとに通知を切れる仕組みは必須機能だと思うので、ちょっとissue作ってみました。
もしよかったら挑戦してみていただければ･･･！！

- https://github.com/VOICEVOX/voicevox/issues/1633

他にもいろんなissueがあるのでよかったら是非挑戦してみてください･･･！

---

一点、`.env`に設定した変数が利用できない点ですが、こちらで試してみた感じviteの設定がそうなっていることが判明しました･･･。
不正確なことを言って混乱させてしまって申し訳ないです 🙇 

↓こちらで @sevenc-nanashi さんが修正してくださいました！

- https://github.com/VOICEVOX/voicevox/pull/1634

追加で`.env`の値を使うようにこちらからコミットさせていただきます！

2023-11-03 07:48 UTC, merged