fix: voicevox-cpu等の使用しないディレクトリが作成される問題を修正
VOICEVOX/voicevox pull request #1620
Opened 2023-10-25 13:16 UTC by sabonerune

## 内容

`electron-log`がインポートすると自動的にログディレクトリを作成してしまうこと、初期状態で`app.getPath("userData")`を実行すると自動的にディレクトリを作成してしまうことが原因でした。

このため`electron-log`を問題が修正された`5.0.0`へ更新、
`beforeUserDataDir`を取得した後、そのディレクトリを削除することで問題を解決します。

## 関連 Issue

- close #1487

## その他

ref [electron-log](https://github.com/megahertz/electron-log)

`portManager.ts`の`!== undefined`を修正
`vvppManager.ts`の`=== null`を修正

2023-10-25 13:53 UTC, sevenc-nanashi requested changes

2023-10-25 13:53 UTC, sevenc-nanashi commented on src/electron/preload.ts
> +    });
https://github.com/megahertz/electron-log/blob/master/README.md#renderer-process
```ts
import log from 'electron-log/renderer';
log.info('Log from the renderer process');
```
わざわざ手動で呼び出す必要はないような感じがします、何か問題とかあったらコメントがあると判りやすいかと。

2023-10-25 18:26 UTC, Hiroshiba approved these changes
LGTM！！

･･･なのですが、正直ちょっとしばらく様子見したいなという気持ちもちょっとあります 😇 
メジャーバージョンアプデなので、なんか大きくガラッと仕様変わったらやだな～くらいの気持ちです。

･･･２週間待機とかでどうでしょう！

2023-10-25 18:26 UTC, Hiroshiba commented on src/background.ts
> +// app.getPath("userData")を呼ぶとディレクトリが作成されてしまうため空なら削除する。
これ･････悲しいですね････。

2023-10-25 18:26 UTC, Hiroshiba commented on src/background.ts
> +  fs.rmdirSync(beforeUserDataDir);
おまじない程度ですが、再帰的消去の有無のデフォルト値を知らなくてもわかるようにしておくのはどうでしょう。
```suggestion
  fs.rmdirSync(beforeUserDataDir, {recursive: false});
```

2023-10-25 18:26 UTC, Hiroshiba commented on src/electron/preload.ts
> +    });
ブラウザ版の考慮はすごい納得感ありました。
ここでelectron-logをimportするのはまあOKだと思いますが、userDataにjsファイルが作られるのはちょっとよくわかんないですね･･･。

まあドキュメントでも案内されてる方法ですし、この形が良いのかなと思いました。
https://github.com/megahertz/electron-log/blob/19bb2a1ab5e12eb985f87cae058d54f6970c7d49/docs/initialize.md#using-ipc-directly

コメントは１箇所あると良さそうですね！
ここのやりとりへのリンクをコメントする感じとか。

2023-10-25 20:17 UTC, sevenc-nanashi approved these changes

2023-10-25 20:17 UTC, sevenc-nanashi commented on src/electron/preload.ts
> +    });
なるほと。コメントあれば大丈夫だと思います。

2023-10-26 06:39 UTC, Hiroshiba commented
マージします！

2023-10-26 06:39 UTC, merged

2023-10-26 08:31 UTC, Hiroshiba commented on src/background.ts
> +
おっとなるほどです！！気づいてくださってありがとうございます！
修正プルリクエストをお願いしても良いでしょうか？
（こちらで良い感じに直しておくのももちろんOKです！）

2023-10-26 09:00 UTC, Hiroshiba commented on src/background.ts
> +
ありがとうございます！！