開発環境であればconfigをリセットするか聞くようにする
VOICEVOX/voicevox pull request #1630
Opened 2023-10-28 15:17 UTC by Hiroshiba

## 内容

- https://github.com/VOICEVOX/voicevox/issues/1626

の解決です。
開発版の時だけ、コンフィグをリセットするか問う機能を追加します。

## 関連 Issue

close #1626 

## スクリーンショット・動画など

## その他

2023-11-11 13:55 UTC, sevenc-nanashi commented on src/background.ts
> +            resetConfig();
このパスだとappExit()が呼ばれないような？

2023-11-11 14:01 UTC, sevenc-nanashi requested changes

2023-11-11 14:01 UTC, sevenc-nanashi commented on src/background.ts
> +          }
```suggestion
          switch (response) {
            case 0:
              await appExit();
              break;
            case 1:
              await openConfigFolderAndExit();
              break;
            case 2:
              resetConfig();
              break;
            default:
              throw new Error("Unreachable");
          }
```

この方が見やすい気がします。

2023-11-12 15:51 UTC, Hiroshiba commented on src/background.ts
> +          }
switch、break書き忘れが起こりそうでちょっと怖いんですよね・・・。
とりあえず今回は見通しが良いのでそうしたいと思います！

2023-11-12 21:06 UTC, sevenc-nanashi approved these changes

2023-11-12 22:13 UTC, sevenc-nanashi commented on src/background.ts
> +          }
eslintが怒ってくれるはずです： https://eslint.org/docs/latest/rules/no-fallthrough

2023-11-13 04:10 UTC, Hiroshiba commented on src/background.ts
> +          }
おおなるほど！！！！安心！！

2023-11-14 15:26 UTC, Hiroshiba commented
テストが通っていたのでマージします！

2023-11-14 15:26 UTC, merged