サードパーティがエンジンへのアクセス情報を得るための設定書き出し機能
VOICEVOX/voicevox pull request #1765
Opened 2024-01-26 14:04 UTC by nmori

## 内容
* ポート番号動的変更に伴い、サードパーティツールが通信ポートを特定出来ない問題が発生する
* この PR では、起動しているエンジンに関する情報をエクスポートする機能を追加する

対応として
* エンジン起動時、再起動、停止時にサードパーティ向けのデータを書き出す
* 書き出す場所は AppData/Roaming/VOICEVOX/runtime-info.json (Windows)

## 関連 Issue
ref #1738

## スクリーンショット・動画など

## その他

2024-01-26 14:18 UTC, sevenc-nanashi commented on src/background/engineManager.ts
> +      );
asyncならfs.promisesを使った方がいいかも？

2024-01-26 14:18 UTC, sevenc-nanashi commented on src/background/engineManager.ts
> +      return "failedToWriteFile";
普通のErrorオブジェクトを返した方が良さそう。

2024-01-26 15:29 UTC, nmori commented on src/background/engineManager.ts
> +      );
この点について非同期化コードに寄せるに当たり、少々相談しておきたい点があります。ファイル書き出しを非同期化した場合、この関数が並走実行される可能性をどれだけ考慮すべきか、ご意見いただきたいです。（個別起動時のルートで、少し気になっています。NGだとしたら、asyncやめて同期側に揃えようと思います）

2024-01-26 21:32 UTC, sevenc-nanashi commented on src/background/engineManager.ts
> +      );
> この関数が並走実行される可能性をどれだけ考慮すべきか、ご意見いただきたいです。

「複数実行されてもいい感じになるようにしたい」、ならasync-lockなどを使えばいい感じになりそう？ConfigManagerあたりにあったはずです。

2024-01-26 22:07 UTC, Hiroshiba commented on src/background/engineManager.ts
> +      );
少なくとも考慮するのに越したことはないと思います！
一言でいうとこのままでもOKですが、もし気が向けばlockしたりatomicなファイル処理にすると良いかもって感じです！

（細かい解説）

ファイルが壊れるのは非同期に１つのファイルを処理してしまうことですが、これはいくつか可能性があります。それぞれで対策はこんな感じになるかもです。

* javascript的に非同期だった場合
	* つまりasync/await
	* 実は同じプロセス（ワーカー？）だった場合、jsのawaitは普通同時に複数の処理をしない（はず）
	* でもファイルioが発生するものは同時に複数走りうる（たぶん）
	* writeFileSyncは同時に２つ以上走らない（･･･たぶん。嘘かも。）
	* fs.promisesはたぶん同時に走っちゃう。ドキュメント読むとたぶん２つ以上同時に走らない気がするけど･･･。
	* lockかけるというのはあり
	* lockかけるのは情報の取得から書き出し終わり全体が良い、つまり`makeEngineInfoFor3rdParty`関数全体
	* ちょうど[ConfigManagerのsave辺り](https://github.com/VOICEVOX/voicevox/blob/2b2013bcd20c312e37054723d1304a4d00382166/src/shared/ConfigManager.ts#L190-L203)がそうなってます
* プロセスが複数あった場合
	* ボイボ自体が複数起動している場合、あるいはjs内でプロセスが複数ある場合
	* lockじゃ防ぎようがないので、ファイルをアトミック操作することで無事を祈る
	* ファイル書き出しやファイルコピーはアトミックな処理じゃないので、衝突しうる
	* mvコマンドはアトミックな処理なので衝突しない
	* なので、ここを気にするなら同ディレクトリの別ファイル（.tmpとか）を作り、mvで移動すると良い
	* Node.jsの場合、たしかrename関数がmv処理同等だったはず
* ファイルシステム側が非同期に処理する場合
	* mvにしてようがなんだろうが、最終的に利用者のファイルシステム側の処理がどうなってるかに依存してる（はず）
	* これはもうどうしようもない。

2024-01-26 22:08 UTC, Hiroshiba commented on src/background/engineManager.ts
> +      return "failedToWriteFile";
これはエラーの握り潰しになっちゃってるので、同じくエラーをそのままthrowが良いと思います！
（エラーが起きていてもユーザーが、それどころか開発者もそのことに気づけない）

2024-01-26 22:25 UTC, Hiroshiba approved these changes
良いですね！！！！！
処理が簡潔で読みやすかったです！！！
この処理で良いはずと、いろいろなとこ読んでくださったんだなと感じました！

2024-01-26 22:25 UTC, Hiroshiba commented on src/background/engineManager.ts
> +  async makeEngineInfoFor3rdParty() {
どちらかというとwriteかも？
（まあmakeもするのですが、本当はmakeは他の関数がやって、この関数はドキュメントの通り書き込むだけが理想かな～と）
```suggestion
  /**
   * サードパーティ向けの設定ファイルを書き出す
   */
  async writeEngineInfoFor3rdParty() {
```

2024-01-26 22:25 UTC, Hiroshiba commented on src/background/engineManager.ts
> +        this.makeEngineInfoFor3rdParty();
これはちょっと相当ややこしいので、自分向けのメモです！

`restartEngine`や`runEngineAll`を実行する関数の直後か、`runEngine`関数の最後で呼ぶか判断する。
たぶんあとあと情報が増えるとRuntimeInfoを別クラスで管理したくなる。
そっちにEngineInfo渡す形が良いかもなので、前者のがその方針に移行しやすい。
前者の場合は起動シーケンスや再起動シーケンスに書き足す。

2024-01-26 22:26 UTC, Hiroshiba requested changes
（すみません、癖でapprove押してしまいました 🙇 ）

2024-01-27 08:18 UTC, nmori commented on src/background/engineManager.ts
> +      );
ありがとうございます。ひとまず同プロセス内の処理と非同期化はかいてみました。
（最新版だけ動かすライトユーザの環境では問題なさそうです）

なお、「異なるエンジン設定されたVOICEVOXが複数起動したパターン」
これをどれぐらいサポートするか？（これはどれぐらいありうるのか？）は相談ポイントですね。

その場合は、VOICEVOXプロセスごとにファイルを書き出すようにする手もありそうですが
強制/異常終了時にゴミファイルが貯まっていくなどの背反はありそうなので、
もう少し実装に手を入れていく必要があるかもしれません。

2024-01-27 08:19 UTC, nmori commented on src/background/engineManager.ts
> +      return "failedToWriteFile";
サードパーティむけの機能がVOICEVOXに影響を与えるのは避けたいので
ログに記録をのこす形としてみました

2024-01-27 08:24 UTC, nmori commented
* 自プロセス向けに、タイムアウト付きロックと非同期関数利用を追記。仮に数回呼ばれてもタイムアウトするのでVOICEVOX側に影響出さずにすむかと思います。
* JSONの書き込みは、非同期関数が呼ばれてから処理したほうがスムーズかとおもったので、 fs-extra の JSON書き込み関数に差し替えました。
* サードパーティツールがファイルを開いている間はエラーが出ますが、VOICEVOX側に影響を与えたくないのでログにエラー記録が残るだけにしました。

2024-01-29 22:52 UTC, Hiroshiba reviewed
すみません遅くなりました！！ほぼLGTMです！！

2024-01-29 22:52 UTC, Hiroshiba commented on src/background/engineManager.ts
> +  async writeEngineInfoFor3rdParty() {
ドキュメントの場所は関数の真上のが良いかもです（関数の上に書くとVSCodeでマウスホバーしたときに出てくる）
```suggestion
  private lock = new AsyncLock({
    timeout: 1000,
  });
  private lockKey = "write";

  /**
   * サードパーティ向けの設定ファイルを書き出す
   */
  async writeEngineInfoFor3rdParty() {
```

2024-01-29 22:57 UTC, Hiroshiba commented on src/background/engineManager.ts
> +        await fsExtra.writeJSON(exportEngineInfoFilename, engineInfoList);
あ、これ直接`npm install`してる感じじゃない＋可能なら依存を増やしたくない（メンテナンス性が下がる）＋そんな手間のかかる処理じゃないので、とくに拘りなければ普通のファイル書き込みのがありがたいかもです！

2024-01-30 12:30 UTC, nmori commented on src/background/engineManager.ts
> +        "runtime-info.json"
コンストラクタ引数にして、background.ts 側からパスを渡すように変更してみます

2024-01-30 12:33 UTC, nmori commented
レビューありがとうございます。
コメント頂いた観点、理解しましたので織り込んでみました。
よろしくお願いいたします。

2024-01-30 22:33 UTC, Hiroshiba reviewed
良い感じですね！！

いろいろ細かいことコメントしていますが、もう大枠は完成していると思うので、もしよければ！！

2024-01-30 22:33 UTC, Hiroshiba commented on src/background/engineManager.ts
> +          JSON.stringify(engineInfoList)
後々他の情報が書き込まれるかもなので、こうかなと！

```suggestion
          JSON.stringify({engineInfos: engineInfoList})
```

2024-01-30 22:33 UTC, Hiroshiba commented on src/background/engineManager.ts
> +          type: engineInfo.type,
あっ。。非常に申し訳ないのですが、ここで返してるhostはhostじゃないんですよね･････。
↓で言うところのoriginだったかな････。
https://shukapin.com/infographicIT/url

１回出力すると互換性維持するために頑張り続けないとなので、一旦正確なのだけ出力する方針はどうでしょう🙇
とりあえず自信もって出せるのは、まあ･･･uuidとport（this.altPortのto）かな。。。🙇
わかりづらくなってて申し訳ないです🙇

2024-01-30 22:33 UTC, Hiroshiba commented on src/background.ts
> +const exportEngineInfoFilename = path.join(
あ、エンジン情報以外も書いていくと思うので、変数名わかりやすくするのどうでしょう。
あとFilenameは文字通りファイル名だと勘違いしやすそうなので、パスだとわかるようPathかなと。
とりあえずまあ･･･こうとか？
```suggestion
const runtimeInfoPath = path.join(
```

2024-01-30 22:33 UTC, Hiroshiba commented on src/background.ts
> +const exportEngineInfoFilename = path.join(
RuntimeInfoを良い感じに書けるよう、クラスにしてあげた方が良い気がしますね･･･。
いけそうだったら実装お願いしたいかもです！（ConfigManagerみたいな感じでRuntimeInfoManagerを作る感じ）
難しそうであればとりあえずFIXMEコメントを残しておければ！
```suggestion
// FIXME: RuntimeInfoクラスにする
const exportEngineInfoFilename = path.join(
```

2024-01-30 22:33 UTC, Hiroshiba commented on src/background/engineManager.ts
> +  async writeEngineInfoFor3rdParty() {
めっちゃ細かいですが、sつけて全情報書き出せる感じを匂わせられれば！

```suggestion
  async writeEngineInfosFor3rdParty() {
```

2024-01-30 23:42 UTC, wappon28dev commented on src/background/engineManager.ts
> +          type: engineInfo.type,
(横入り失礼します; ただの情報提供です！)  
確か `host` が紛らわしい状態なのは Issue が立っていましたね！: https://github.com/VOICEVOX/voicevox/issues/1297 (← のキッカケ: https://github.com/VOICEVOX/voicevox/pull/1267#discussion_r1174605497)

`engineInfo.host` に実際入っている値は `http://127.0.0.1:50021` のような形になりますね！
おっしゃる通り本来は Origin ですね.  (Issue の方では Origin より広義の url になっているかも……？)

2024-01-31 03:38 UTC, nmori commented on src/background/engineManager.ts
> +          type: engineInfo.type,
レビュー、コメントありがとうございます。

現段階のコード提案は構造を継承しているだけだったので、ご提案の方向にしたいです。

その一方で、いくつか項目を相談したほうがよさそうにも思いました。

1.このファイルの互換性を判断するために、バージョンに関するデータを吐き出したほうがよさそう

2.マルチエンジン構造の将来像にクラウドのエンドポイントを提供する可能性があるなら(プロトコル、ホスト、ポート番号、パスを含む)エンドポイントurlを吐き出すほうがよさそう。(サードパーティはこのファイルを見た後は音源情報をサーチしにアクセスするため)

3.他に吐き出したほうが良いデータがあるかは、コメント追記があれば判断(逆に外部から使い所がなさそうな項目は削除)

というあたりです。一旦コード修正は進めつつ、サードパーティ作者さん含めご意見を伺いたいです。

2024-01-31 17:14 UTC, nmori commented on src/background/engineManager.ts
> +          type: engineInfo.type,
出力されるJSONフォーマットはこんな感じでいかがでしょうか。

``` JSON
{
    "versions": {
        "fileFormat":  "1,0",
        "VOICEVOX": "999.999.999"
    },
    "engineInfos": [
        {
            "uuid": "074fc39e-678b-4c13-8916-ffca8d505d1d",
            "url": "http://127.0.0.1:50021",
            "name": "VOICEVOX Engine",
            "executionEnabled": true,
            "executionFilePath": "D:\\VOICEVOX0.15.0\\run.exe",
            "executionArgs": [],
            "type": "default"
        }
    ]
}
```

これでよかったとして、下記みたいに構造を個別にかいていくと
ちょっと雑多な感じがしますね…　クラス化しちゃいましょうか？

``` ts
      // ファイルに書き出すデータをつくる
      const outputInfoData = {
        versions: {
          fileFormat: "1.0",
          VOICEVOX: app.getVersion(),
        },
        engineInfos: engineInfoList,
      };
```

2024-01-31 17:16 UTC, nmori commented on src/background.ts
> +const exportEngineInfoFilename = path.join(
ありがとうございます。クラス化してみようと想います。
ファイル位置を shared配下にしようと想いましたが、他に適切な場所があれば
お勧め頂けるとたすかります（階層をどうやって判断するのか、判断基準が難しい）

2024-02-01 17:23 UTC, nmori commented on src/background/engineManager.ts
> +          type: engineInfo.type,
この部分はクラス化し、コード提案してみます
（少し単純さは失われましたが、ファイルフォーマット定義はわかりやすくなりました）

2024-02-01 17:25 UTC, nmori commented
ファイルフォーマットの追加、クラス化しました。
クラス化は見様見真似で一旦形にしました。単純さを保つ部分で改良の余地はあるのかもしれません。
レビューよろしくお願いいたします。

2024-02-11 17:21 UTC, Hiroshiba commented on src/background.ts
> +const exportEngineInfoFilename = path.join(
判断に関しては僕もとても迷います･･･。もし提案あれば別でコメントします！

2024-02-11 17:38 UTC, Hiroshiba reviewed
良い感じに整ってきているのを感じます！

`RuntimeInfoManager`を後から拡張しやすいようにちょっと設計を提案してみました！
（微妙そうな点あったらすみません 🙇 ）

2024-02-11 17:38 UTC, Hiroshiba commented on src/background.ts
> +const runtimeInfoPath = new RuntimeInfoManager(app.getPath("userData"));
こうかもです！
```suggestion
const runtimeInfoManager = new RuntimeInfoManager(app.getPath("userData"));
```

2024-02-11 17:38 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +export interface EngineInfoFormatFor3rdParty {
ここはエンジン情報というよりそれを含んだ情報全部なので、こうかもです！
```suggestion
export interface RuntimeInfoFormatFor3rdParty {
```

2024-02-11 17:38 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> + * サードパーティ向けランタイム情報のレコード定義
逆にこっちはランタイム情報じゃないかもです
```suggestion
 * サードパーティ向けエンジン情報のレコード定義
```

2024-02-11 17:38 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +}
このクラスですが、このクラス単体でjsonデータを作成・保存できるようにし、かつ別の情報も足しやすい設計にするのはどうでしょう？

* private runtimeInfoPath（そのまま）
* private appVersion
	* VOICEVOXVersionの名前を変えて`OutputInfoDataFor3rdParty`からこっちに移す
* private fileFormatVersion
	* `OutputInfoDataFor3rdParty`から移す
* private engineInfos
	* エンジン情報を持っておく
* constructorはディレクトリパスではなくruntime-info.jsonのファイルパスを与える形に
	* ちょっとだけテストが書きやすくなる
* setEngineInfos
	* エンジン情報をセットする
* save
	* jsonを作って保存する

こうしておけば、他にデータを追加したいときに`setなんとか`を追加して`save`内でjsonにデータを足せば完了するので、拡張が用意になるかなと！

2024-02-12 13:46 UTC, nmori commented on src/shared/RuntimeInfoManager.ts
> +}
ご助言ありがとうございます。クラス側に機能を集め寄せて行くということですね。
ご提案いただいているメンバーをベースに、揃えて書いてみました。

* コンストラクタの引数として、appVersion自体も渡すことにしました。（他のコメントやlintのコメントを見ると、 electron を import するのは推奨されないようなので、依存関係を減らす方を優先しました）
* setEngineInfos はすべての配列をそのままセットする形にしました。（runEngine / restartEngine においてもすべて取得し直していますが、これが一番簡素な実装と思いそのまま実装しました）
* コメント、変数名…　見落としてました。レビューありがとうございます。

2024-02-13 15:22 UTC, Hiroshiba approved these changes
LGTM！！！

色々調整ありがとうございました、ものすごい分かりやすいコード・仕様になったと思います！！！
ちょっと細かいところをこちらでいくつか変更させていただきます！

あ、そういえば案内をどうしようか考えていませんでした！
そちらはissueの方とかで進めたり、別プルリクエストで進められればと思います！！

丁寧な進行ありがとうございました！！
また力をお借りできると非常に心強いです！！！

2024-02-13 15:22 UTC, Hiroshiba commented on src/background.ts
> +);
メモ：`vvppManager = new VvppManager({ vvppEngineDir });`の下辺りだと収まりが良いかも

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +    this.runtimeInfoPath = userDataPath;
こうかも？
```suggestion
  constructor(runtimeInfoPath: string, appVersion: string) {
    this.runtimeInfoPath = runtimeInfoPath;
```

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +
ファイルの有無は隠蔽可能になったので不要になったかなと！
```suggestion
```

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +   * サードパーティ向けの設定ファイルを書き出す
ちょっと微調整まで！
```suggestion
   * サードパーティ向けのランタイム情報ファイルを書き出す
```

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> + * サードパーティ向けランタイム情報のエクスポート情報クラス
微調整です 🙏 
```suggestion
 * サードパーティ向けのランタイム情報を書き出す
```

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +export class RuntimeInfoManager {
役割がかなり明確になったので`Exporter`でも良いかも

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +      // ファイルに書き出すデータをつくる
微調整です 🙏 
```suggestion
      // ファイル書き出し
```

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +import log from "electron-log/main";
メモ：これで大丈夫だったかは要確認

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +export interface EngineInfoRecordFor3rdParty {
どっちかというとこうかも
```suggestion
export interface EngineInfoForRuntimeInfo {
```

2024-02-13 15:22 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +    const engineInfoFormatFor3rdParty: RuntimeInfoFormatFor3rdParty = {
engineInfoじゃなさそう

2024-02-13 15:24 UTC, Hiroshiba commented on src/shared/RuntimeInfoManager.ts
> +export class RuntimeInfoManager {
･･･やっぱりマネージャーで！

2024-02-13 16:32 UTC, Hiroshiba commented
ちょっと構造を変更させていただいて、テストを追加させていただきました！

2024-02-13 16:34 UTC, Hiroshiba commented on src/background/RuntimeInfoManager.ts
> +   * Note: 破壊的変更があった場合に数字を上げること
テスト側で変更があったら書き換える旨は案内するようになったので省略可能
```suggestion
   * ファイルフォーマットバージョン
```

2024-02-13 16:36 UTC, merged