refactor: 使用されていない関数を削除し、コード量を削減
VOICEVOX/voicevox pull request #1978
Opened 2024-04-04 15:11 UTC by weweweok

## 内容

題の通りです。全体検索をかけて、確認してから削除しました。

## その他

2024-04-04 15:14 UTC, weweweok commented on src/openapi/models/InstalledLibrary.ts
> -export function instanceOfInstalledLibrary(value: object): boolean {
該当箇所は
`instanceOfInstalledLibrary`関数です。

2024-04-04 15:15 UTC, weweweok commented on src/openapi/models/InstalledLibraryInfo.ts
> -    let isInstance = true;
該当箇所は
`instanceOfInstalledLibraryInfo`関数です。

2024-04-04 20:34 UTC, sevenc-nanashi requested changes
一番上にも書いてありますが、このファイルはOpenAPI Generatorで生成されたものなんですよね...
そのためここのファイルは基本的にいじっても無駄かつ次のアプデで消えてしまいます。
そのためCloseします。

2024-04-04 20:34 UTC, closed without merging

2024-04-07 22:05 UTC, Hiroshiba commented
`src/openapi`ディレクトリ以下にREADME.md作って、そこでこれが自動生成コードだと案内しても良いかもと思いました！
それで気付けるようになりやすくなるかと言われる、だいぶ微妙かもですが･･･。