IPC周りの呼び出しをdot記法で書けるように
VOICEVOX/voicevox pull request #2240
Opened 2024-08-21 17:04 UTC by MT224244

## 内容

#2088 の実現方法を参考に、IPC周りの呼び出しをdot記法で書けるようにしてみました。

## 関連 Issue

## スクリーンショット・動画など

## その他

2024-08-21 17:34 UTC, Hiroshiba reviewed
プルリクエストありがとうございます！！

もしかしたらより使い勝手が良いというか、メンテナンスしやすい形があるかもですが、とりあえず初学者の人がコードをコードジャンプで追えるようになってとても良いと思います！！
（まあ参照に移動しないといけないのでちょっと難度は高いのですが、）

---

@Segu-g さん
すみません！
もしお時間あれば型周りに関してアドバイスいただけると心強いです！！

2024-08-22 15:36 UTC, MT224244 commented
受信側をオブジェクトで書くことで実装へコードジャンプが可能になりました。
なぜこの書き方でコードジャンプ可能になったのかは分かっていません…。

オブジェクトで書くようになった影響で未実装(未使用)の項目が見つかったので、それをどうするかが決まるまではDraftにしておこうと思います。

2024-08-23 21:35 UTC, Hiroshiba commented on src/backend/electron/main.ts
> +  },
型の方を削除で良さそうに思いました！！

実際４つとも現在使われていないと思われます！
（LOG系はたぶんelectron-logを使う形になった、RESTART_ENGINE_ALLは不明だけど[何かしらのミスかも･･･？](https://github.com/VOICEVOX/voicevox/pull/855/files#diff-a6f4b99080d20781616d3df78a9a8da0e260ce4aa039913695675ac57b4aa031R203-R206)）

2024-08-24 09:21 UTC, MT224244 commented on src/backend/electron/main.ts
> +  },
ログを追ってみたところ、 `LOG_*` 系は[#1620](https://github.com/VOICEVOX/voicevox/pull/1620/files#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291f)、 `RESTART_ENGINE_ALL` は[#1090](https://github.com/VOICEVOX/voicevox/pull/1090/files#diff-11db236acd6b02b1229e7d325e9bf8edb521032e6388f68b6a884ec24bbe291f)でそれぞれ実装が削除されていました。
どちらも単に型定義から消し忘れているだけっぽいので、確かに消しても良さそうですね。

2024-08-24 10:40 UTC, Segu-g requested changes
型を確認しました！
mainとrendererのどちらからもコードジャンプできていて良いと思います！

また、この辺りのコードが置き換え忘れているようです！
https://github.com/VOICEVOX/voicevox/pull/2240/files#diff-d2475d73ba5acb680e9dee5e4253a9bc70d470ed5835750c9832f21074090cd4R460-R476

2024-08-24 10:40 UTC, Segu-g commented on src/backend/electron/preload.ts
> +});
```suggestion
const ipcRendererInvoke = new Proxy(
  {},
  {
    get:
      (_, channel: string) =>
      (...args: unknown[]) =>
        ipcRenderer.invoke(channel, ...args),
  },
) as IpcRendererInvoke;
```

2024-08-24 10:40 UTC, Segu-g commented on src/backend/electron/ipc.ts
> +});
型的にはこちらの方がいいかも？
```suggestion
export const ipcMainSend = new Proxy(
  {},
  {
    get:
      (_, channel: string) =>
      (win: BrowserWindow, ...args: unknown[]) =>
        win.webContents.send(channel, ...args),
  },
) as IpcMainSend;
```

2024-08-26 13:19 UTC, Hiroshiba reviewed
ほぼLGTMです！！
実装ありがとうございます！！

型はもっと詰められそうかもですが（`registerIpcMainHandle`に渡すものがちゃんとVOICEVOXが想定するIPC通信用のオブジェクトになってるかなど）、まあこだわり過ぎなくても良いかもですね！

2024-08-26 13:19 UTC, Hiroshiba commented on src/backend/browser/sandbox.ts
> +  window.addEventListener(
ここどうやら使われてないっぽいので、メモ書きコメントだけお願いできると 🙇 
```suggestion
  // NOTE: もしブラウザ本体からレンダラへのメッセージを実装するならこんな感じ
  window.addEventListener(
```

@yamachu ちなみに例示するのが実装時の意図だった、という認識で合ってそうでしょうか 👀 
[このあたり](https://github.com/VOICEVOX/voicevox/pull/1345/files#diff-b50f6753c347be6ca10c4e787a6d6d9217570fb679430c5ef9652d9dc6b0b651R184-R193)っぽそう。
すんごい前のことを聞いちゃってすみません 🙇 

---

このあたり解説すると、electronではバック→フロントへの通信が必要で（エンジンプロセスがエラー吐いたとか）、その通信用なんですよね。
でもブラウザ版ではいまのとこ必要なさそう。
たぶんこれから先もいらなそう･･･？だとしたら消しても良さそう？

だけどそれは流石にこのPRの範疇を超えてそう！
なのでちょっとメモコメントをお願いしてみた次第です！

2024-08-26 16:25 UTC, MT224244 commented on src/type/ipc.ts
> +};
これらの型を `backend/electron/ipc.ts` に移動してみましたが、 `type/preload.ts` からIpcRendererOnをimportせねばならず、そうするとeslintのno-restricted-importsルールでelectronをimportするなと怒られてしまいます。

Sandboxインターフェースには抽象的な型を書いてそれぞれの実装で具体的な型で上書きすればいいかと思いきや、 `plugins/ipcMessageReceiverPlugin.ts` には抽象的な型が渡ってしまいます。
そしてここでもIpcRendererOnをimportすることができないので、asで無理やり型を通すとかも出来なさそうです。

このあたり、ちょっと私には解決策が思いつきませんでした…。

2024-08-26 17:37 UTC, Hiroshiba commented on src/type/ipc.ts
> +};
あーーーなるほどです！！！

以前どうしてたのか見てみたんですが、そもそも渡された値を使っていないので、
```ts
event: import("electron").IpcRendererEvent
```
となってるとこが
```ts
_: unknown
```
になってました！
https://github.com/VOICEVOX/voicevox/pull/2240/files#diff-a2e928a7b8428dba5f753cc8014e39204ccb3aaf1049ba8567f4b59af69defc7L269

とりあえずこれで迂回できる･･･？

ちょっと試しに作ってみたのでプルリクエスト送ってみました！参考になれば 🙇 

- https://github.com/MT224244/voicevox/pull/1/

2024-08-27 13:36 UTC, MT224244 commented on src/type/ipc.ts
> +};
ありがとうございます！
頂いたPRを参考に修正しました。

2024-08-29 14:38 UTC, Hiroshiba commented on src/backend/electron/ipc.ts
> +export function registerIpcMainHandle<T extends IpcMainHandle>(
（細かいのですが）
コメント内で指示語はなるべく使わないようにするのが良いとされてたりします！
曖昧になっちゃうので。

「こう」「もっとキレイ」を展開すると、こう･･･？
```suggestion
// FIXME: asを使わないようオーバーロードにした。オーバーロードも使わない書き方にしたい。
export function registerIpcMainHandle<T extends IpcMainHandle>(
```

2024-08-29 14:41 UTC, Hiroshiba commented on src/backend/browser/sandbox.ts
> +// FIXME: asをなるべく使わずに書いたらこうなった。もっとキレイな書き方があれば…
こっちも！
```suggestion
// FIXME: asを使わないようオーバーロードにした。オーバーロードも使わない書き方にしたい。
```

2024-08-29 14:53 UTC, Hiroshiba commented
あ、 @Segu-g さんのrequestedが未解決に残ってるのでマージは保留ということで！
問題ないと思うので明日ぐらいにマージさせていただこうと思います！ 🙏 
（早めにマージしないとコンフリクトがいっぱい出てきちゃう）

2024-08-29 15:14 UTC, yamachu commented on src/backend/browser/sandbox.ts
> +  window.addEventListener(
resolvedになってるけど一応当時の意図を…

当初WorkerにファイルReadの処理を投げて、それを受け取るためにipcの処理を先んじて実装しておこうという意図で置いていました。
実装するとしたらこうなりますだけ書いておいたやつですね…

なので

> でもブラウザ版ではいまのとこ必要なさそう。
> たぶんこれから先もいらなそう･･･？だとしたら消しても良さそう？

消しても良さそうではあります！

2024-08-29 15:21 UTC, Hiroshiba commented on src/backend/browser/sandbox.ts
> +  window.addEventListener(
おおなるほどです！！
自信が持てました、ありがとうございます！！

2024-08-29 16:24 UTC, Segu-g approved these changes
私の指摘箇所について修正されていることを確認しました！その他も問題なさそうです！
LGTM!

2024-08-29 16:28 UTC, merged