前回開いていたエディタ(トーク or ソング)画面を起動時に表示
VOICEVOX/voicevox pull request #2355
Opened 2024-11-15 23:35 UTC by X-20A

## 内容
とりあえず動くはずですが、理解して書いたというよりもエラーメッセージの誘導に従っただけな感があるので、設計の方針に沿うかはなんとも分からないです

## 関連 Issue
#2010

2024-11-16 02:32 UTC, sevenc-nanashi requested changes

2024-11-16 02:32 UTC, sevenc-nanashi commented on src/components/App.vue
> +    editor: store.state.editorType as EditorType,
stateの型を書く必要があると思います（store/type.ts参照）

2024-11-16 02:32 UTC, sevenc-nanashi commented on src/store/ui.ts
> +      });
```suggestion
      await window.backend.setSetting("editorType", editorType)
      mutations.SET_OPENED_EDITOR({
        editor: editorType,
      });
```
普通に分けた方が良さそう。

2024-11-16 13:47 UTC, X-20A commented on src/components/App.vue
> +    editor: store.state.editorType as EditorType,
追記しました

2024-11-16 13:58 UTC, X-20A commented on src/store/ui.ts
> +      });
私もそちらが分かりやすそうに思えます。ただ、既存のSET_INHERIT_AUDIOINFOやSET_ACTIVE_POINT_SCROLL_MODEでは引数内で記述されているので統一感を考慮してSET_EDITOR_TYPEもそれに倣いました。これらの関数がどのような意図や都合で書かれたか分からないため、判断に迷っています。

2024-11-17 17:03 UTC, Hiroshiba commented on src/store/ui.ts
> +      });
確かにこれ混乱しますね！！
僕も正確なところがちょっとわかんないです。。。

最初は設定ごとにSETのためのmutation/actionがあったのですが、後々に統合された`SET_ROOT_MISC_SETTING`ができました。
なので大多数は`SET_ROOT_MISC_SETTING`を使ってますが、どうやらまだ個別にSETしているものが残っていたっぽいです･･･！

今回の場合は多分`SET_EDITOR_TYPE`は用意せず、`SET_ROOT_MISC_SETTING`を使う形が良さそうに感じました！

2024-11-17 17:25 UTC, Hiroshiba reviewed
PRありがとうございます！！！
実装とコメントを見させていただいて、確かにちょっとややこしくなっていることがわかりました 🙇 
ということで、整理した後提案を書いています！

既存で「どれが開かれているか」を格納している`openedEditor`と、それとは別に`editorType`が状態（State）に含まれていますね！
実際にUIの表示に使われているのは`openedEditor`で、後者は設定の同期のために使われていそう。
つまり設定の同期が終わった後は同じものを示す変数が2つあり、このままだと何が取りに依存するかわからなくなって難しいことになるかも。

ちょっと提案なのですが設定＋状態の`editorType`を追加せず、逆に今までの`openedEditor`を設定に追加するのはどうでしょうか？ 👀 
多分方針はこんな感じ･･･？

* settingに`openedEditor`を追加
	* 型は`"talk" | "song"`だけでundefinedは無し
	* デフォルト値を"talk"にする
* 元からあったuiState.openedEditorをなくし、serringState.openedEditorに移動
* あとは微調整して完成？

---

ちょっとややこしいと思うので、多分こんな感じというのをコメントしていきます！！
コメントの内容以外に↓もすれば完成････なはず･･･！！

* `SET_OPENED_EDITOR`を消す
	* `SET_OPENED_EDITOR`でファイル全体検索すれば･･･！
* 代わりに`SET_ROOT_MISC_SETTING("openedEditor")`を使う

不明だったら何でもコメントください 🙇

2024-11-17 17:25 UTC, Hiroshiba commented on src/components/App.vue
> +      });
ここはなくなる

2024-11-17 17:25 UTC, Hiroshiba commented on src/components/App.vue
> +  });
ここは以前のコードもなくなる
（`SET_OPENED_EDITOR`を呼ばない）

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/setting.ts
> +  editorType: "talk",
openedEditorに

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/setting.ts
> +        "editorType",
ここも`openedEditor`に

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/type.ts
>    openedEditor: EditorType | undefined; // undefinedのときはどのエディタを開くか定まっていない
ここはuiStateなので、editorTypeもopenedEditorも両方消す

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/type.ts
> +  };
これもなくせるはず

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/ui.ts
>    openedEditor: undefined,
ここも消えるはず

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/ui.ts
> +
`HYDRATE_SETTING_STORE`内の`mutations.SET_ROOT_MISC_SETTING`があるのでこのコードはなくても良いはず！

（さらに言うと上の`mutations.SET_ACTIVE_POINT_SCROLL_MODE`とかもいらなそうだけど･･･まあ一旦放置で･･･。
あ、もし気が向いたら別でプルリクエストとかいただけるとめちゃくちゃ嬉しいです！！）

2024-11-17 17:25 UTC, Hiroshiba commented on src/store/ui.ts
> +    async action({ mutations }, { editorType }: { editorType: EditorType }) {
ここもなくせそう！

2024-11-17 17:25 UTC, Hiroshiba commented on src/type/preload.ts
> +  editorType: z.enum(["talk", "song"]).default("talk"),
ここをopenedEditorに変える感じで･･･！
（これが今回の提案の肝）

2024-11-17 17:25 UTC, Hiroshiba commented on src/type/preload.ts
> +    editorType: z.enum(["talk", "song"]).default("talk"),
`rootMiscSettingSchema`側にあるのでこちらいらないはず！

2024-11-18 07:36 UTC, Hiroshiba commented
テストが落ちてそうでした！！

調べてみた感じかなり難しかったので、こちらでPR作ってみました！
原因はショートカットキーがなぜか登録されないためだったので、ちゃんと実行するようにしてみました 🙏 

- https://github.com/X-20A/voicevox/pull/3

2024-11-18 15:24 UTC, Hiroshiba reviewed
変更ありがとうございます！！
もうほとんど感染してる気がします！！

これソングで開いたあと保存して再度開いた時、一瞬だけトーク画面が映っちゃいますね！！

Vuex.stateの初期値はundefinedにし、保存されている値の初期値talkにして、undefinedのときは（以前と同様に）何も映さないようにすれば解決しそう･･･？
ということでまたになってしまうのですがプルリクエスト作ってみました 🙇 

- https://github.com/X-20A/voicevox/pull/4

何かおかし挙動とかあれば･････ 🙇

2024-11-18 21:58 UTC, X-20A commented
ありがとうございます。
npm run electron:serveしてみると作動はしますがいくつかエラーが出るようです。
更新との関係がなかなか読み難い感じです。
![キャプチャ_2024_11_19_06_49_45_81](https://github.com/user-attachments/assets/2b3a96b0-afed-46e5-98fd-1a55fc55d8c7)

2024-11-18 22:13 UTC, sevenc-nanashi commented
多分ローカルでnpm iし直したら治ると思います

2024-11-18 22:22 UTC, X-20A commented
ありがとうございます。
だいぶ消えたのでまた見直してみます

2024-11-19 07:27 UTC, sevenc-nanashi approved these changes
大丈夫だと思います。

2024-11-19 18:33 UTC, Hiroshiba commented
LGTM！！！

実装ありがとうございました！！

またお誘いになってしまうのですが、もしよかったらまた機能追加に挑戦してみませんか･･･！！
できそうなissueを探してみました！！

* https://github.com/VOICEVOX/voicevox/issues/2251
	* electronとの通信が必要
	* [すでにある程度進めてくださってる方](https://github.com/VOICEVOX/voicevox/pull/2273)がいらっしゃるので、そこを参考にすると進めやすいかも
* https://github.com/VOICEVOX/voicevox/issues/2057
	* ショートカットキー周りのコードを追いかける必要があります
	* まずはどういうものが便利そうかを整理するだけでも楽しいかも？
* https://github.com/VOICEVOX/voicevox/issues/2300
	* ソングの機能、どこをどう変えればいいかコードを追うのがちょっとややこしいかも
* https://github.com/VOICEVOX/voicevox/issues/2345
	* 同じくソング側の話、これだけバグ直しタスクです

もしよければぜひぜひ！！！
（ちょっと難度が上がってると思うので、不明なとこがあれば何でも聞いていただければ！！）

2024-11-19 18:33 UTC, merged