ソング：labファイルを書き出す機能を追加
VOICEVOX/voicevox pull request #2383
Opened 2024-11-30 16:15 UTC by sigprogramming

## 内容

labファイルを書き出す機能を追加します。

書き出し対象のトラックを指定できた方が良いと思いますが、ひとまず全てのトラックを対象として書き出す形で実装しています。

## 関連 Issue

- https://github.com/VOICEVOX/voicevox/issues/2107

## その他

2024-12-01 15:37 UTC, sigprogramming commented on src/sing/fileDataGenerator.ts
> +    writeLine(phoneme.frameLength / frameRate, phoneme.phoneme);
トークは`vowel != "N"` のときに `vowel.toLowerCase()` する実装になっていました。
ソングは必要なさそう…？

2024-12-01 15:39 UTC, sigprogramming commented on src/components/Sing/menuBarData.ts
> +      label: "音声書き出し",
トーク側と合わせました。

2024-12-03 16:31 UTC, Hiroshiba commented
ちょっと実際に動かしてみて挙動だけチェックさせていただきました！
しっかり波形と合うlabが出力されてそうでした！！

2024-12-03 21:03 UTC, sevenc-nanashi commented on src/components/Sing/AudioExportOverlay.vue
メッセージの部分だけ差し替えられるようにすれば共通化できそう？
Container/PresentationのContainerが音声用とlab用とで2個ある形でも、SingEditorから差し込む形でも。

2024-12-05 15:41 UTC, sigprogramming commented on src/components/Sing/AudioExportOverlay.vue
書き出し専用のオーバーレイ（ダイアログ？）として共通化するのが良さそうに感じたので、
`ExportOverlay`として共通化しました！
（stateも共通化しました）

2024-12-05 15:43 UTC, sigprogramming commented on src/sing/fileDataGenerator.ts
> +    writeLine(phoneme.frameLength / frameRate, phoneme.phoneme);
トークと合わせて`vowel != "N"`のときに`toLowerCase()`するようにしました！

2024-12-14 11:01 UTC, sevenc-nanashi requested changes
ちょっと試していました。
各トラックの最初が0になる感じだとかなり不便（1キャラに複数トラックが割り当たっている場合）なのでここは挙動を変えるべきだと思います。

2024-12-14 14:27 UTC, sigprogramming commented
> 各トラックの最初が0になる感じだとかなり不便

トラックの先頭を0秒としてlabファイル（音素タイミング）が書き出される形だと不便、ということでしょうか…？

2024-12-14 14:29 UTC, sevenc-nanashi commented
あ、明らかに書き方を間違えました...

トラックの最初のPhraseの始点が0秒だと不便、ですね。

2024-12-14 15:19 UTC, sigprogramming commented
なるほどです！
確かにトラックの最初のPhraseの始点が0秒で書き出されてますね。
これは意図した挙動ではないので（どこかバグってる）、修正します…！

2024-12-15 14:11 UTC, sigprogramming commented
修正しました！

2024-12-15 21:20 UTC, sevenc-nanashi commented
一番速いpauが0になってそう？
![image](https://github.com/user-attachments/assets/ce97b935-bd29-463e-a3f7-d1c89a2d99e8)

例えばこう言うケースで音声と一致しなくなります。
マイナス時間に行ったものは消して良いかなと思います（[ヒホさんも同意見 at Discord](https://canary.discord.com/channels/879570910208733277/893889888208977960/1317711097050169364)）

2024-12-17 10:06 UTC, sigprogramming commented
マイナス時間のところを書き出さないようにしました！

2024-12-17 10:19 UTC, sevenc-nanashi approved these changes
挙動は大丈夫そうでした。

2024-12-17 10:19 UTC, sevenc-nanashi commented on src/store/singing.ts
> +  exportState: "NotExporting",
enumの命名形式はちゃんと決めた方がよさそう（どうなってましたっけ？）

2024-12-17 10:19 UTC, sevenc-nanashi commented on src/components/Sing/menuBarData.ts
> +      "text",
通知は「labファイル」の方がよさそう？

2024-12-22 14:59 UTC, sigprogramming commented on src/store/singing.ts
> +  exportState: "NotExporting",
現在は特に決まってなさそう…？
コード上でも統一されてないですが、enumはScreamingSnakeCaseが一般的だと思うので、それに統一するのが良いかもです。

2024-12-22 15:09 UTC, sigprogramming commented on src/store/singing.ts
> +  exportState: "NotExporting",
ひとまずScreamingSnakeCaseに変更しました。

2024-12-23 21:25 UTC, sevenc-nanashi requested changes
あれ、また最初のフレーズが始点になってそう？

2024-12-23 21:48 UTC, sigprogramming commented
必要な処理を消してました…修正しました！

2024-12-24 12:03 UTC, sevenc-nanashi approved these changes
あとはConflictが直れば大丈夫だと思います。

2024-12-24 14:25 UTC, sigprogramming commented on src/sing/fileDataGenerator.ts
> +) {
`AudioBufferLike`型を定義しても良いかも…？

2024-12-24 20:37 UTC, Hiroshiba reviewed
ほぼLGTMです！！

いくつかリファクタリングの提案コメントをさせていただきました。
あまり気乗りしないor時間かかりそうであればこっちでやっちゃおうと思います！

2024-12-24 20:37 UTC, Hiroshiba commented on src/store/singing.ts
> +            }
この４０行の処理、間違いなく共通化できるので共通化しておきたいですね！
けどまあstoreに関数足すのちょっと面倒なので、とりあえず`EXPORT_STEM_AUDIO_FILE`側と両方にTODOコメント残すのはどうでしょう。

```ts
// TODO: EXPORT_STEM_AUDIO_FILEと処理が同じなので共通化する
```
みたいな！

2024-12-24 20:37 UTC, Hiroshiba commented on src/store/singing.ts
> +            );
改行位置にちょっと違和感があるかも＆コメントが有っても良いかも
こんな感じ？
```suggestion

            // フレーム数が1未満の音素を除く
            const filteredEntirePhonemeTimings = entirePhonemeTimings.filter(
              (value) => {
                const frameLength = value.endFrame - value.startFrame;
                return frameLength >= 1;
              },
            );

            const entirePhonemes = phonemeTimingsToPhonemes(
              filteredEntirePhonemeTimings,
            );
```

2024-12-25 18:00 UTC, Hiroshiba commented on src/components/Sing/ExportOverlay.vue
> +    return "";
あ、ここ到達しないはずなのでエラーにしてあげるほうがよさそう！
```suggestion
    throw new Error(store.state.exportState);
```
到達しないはずだと開発者側にわかるように`UnreachableError`をimportして使うとより良さそう！

```suggestion
    throw new UnreachableError(store.state.exportState);
```

2024-12-26 14:43 UTC, sigprogramming commented on src/components/Sing/ExportOverlay.vue
> +        v-if="nowRendering"
説明コメントを追加しました！
書き出しのキャンセルはレンダリング中にのみ可能なので、nowRenderingのv-ifにしています。

2024-12-26 14:44 UTC, sigprogramming commented on src/components/Sing/ExportOverlay.vue
> +.export-overlay {
`SingEditor.vue`の``exporting-dialog`を消しました！

2024-12-26 14:44 UTC, sigprogramming commented on src/sing/fileDataGenerator.ts
> +export function generateWavFileData(
`src/helpers/`に移動しました！

2024-12-26 14:45 UTC, sigprogramming commented on src/sing/fileDataGenerator.ts
> +export async function generateTextFileData(obj: {
`audio.ts`でも`generateTextFileData`を使用するようにしました！

2024-12-26 14:51 UTC, sigprogramming commented on src/store/singing.ts
> +            }
action化しました！

2024-12-26 14:52 UTC, sigprogramming commented on src/store/singing.ts
> +      }
元のコードは`characterInfo`が無かったときに`continue`するようになっていましたが、`characterInfo`が無いというのは起こり得ないと思うので、エラーをthrowするように変更しました。

2024-12-26 14:53 UTC, sigprogramming commented on src/store/singing.ts
> +            );
改行位置とコメントを修正しました！

2024-12-26 15:04 UTC, sigprogramming commented on src/components/Sing/ExportOverlay.vue
> +    return "";
エラーをthrowするようにすると、
- `v-if="nowExporting"`されている要素の中で`exportingMediaName`が使用されている
- 不要な場合にcomputedの処理が走らない

のを前提としたコードになり（`script`タグ内のコードが`template`タグ内のコードに依存している）、その辺りで違和感があったので、refとwatchを使用する形にしました。

（`script`タグ内のコードが`template`タグ内のコードに依存しない形が良いかなと思います）

2024-12-26 16:31 UTC, Hiroshiba commented on src/components/Sing/ExportOverlay.vue
> +    return "";
なるほどです！！
たしかにtemplate内での位置を考えながらcomputedの中を実装するのは良くなさそう！！

ただwatchにすると結局`""`が生まれてしまうので、問題は変わってないかも･･･？
直和型を使って、`nowExporting`がtrueのときのみ`exportingMediaName`があることを型レベルで制限してしまうのがロジック的には一番正しいかもです！（一時的な状態を排除できる）

ということで、直和型（ユニオン型？）のお手本みたいな感じなので、ちょっとPR作ってみました！！
参考になれば！！

- https://github.com/sigprogramming/voicevox/pull/3

2024-12-26 16:56 UTC, Hiroshiba commented on src/store/singing.ts
> +            if (state.cancellationOfLabelExportRequested) {
これ、stateに存在しないかも･･･？
なんでエラーにならないんだろう。。。。 😇

2024-12-26 16:56 UTC, Hiroshiba commented on src/helpers/fileDataGenerator.ts
> +export async function generateLabelFileData(
あっ　この関数はsingドメインのisVowel使ってたり、singドメインのFramePhoneme使ってたりするので、singドメイン以下のがあってるかもです 🙇 🙇 🙇

2024-12-26 16:56 UTC, Hiroshiba commented on src/helpers/fileDataGenerator.ts
> +    timestamp += phonemeLengthSeconds * 10e7; // 100ns単位に変換
この指摘正しいかもです！！
`generateLabFromAudioQuery`では`10000000`で、これは`1e7`かも。

2024-12-26 16:56 UTC, Hiroshiba reviewed
ほぼLGTMです！！

いくつかミスがあるかも＆提案まで！！

2024-12-27 11:12 UTC, sigprogramming commented on src/helpers/fileDataGenerator.ts
> +    timestamp += phonemeLengthSeconds * 10e7; // 100ns単位に変換
`1e7`でした…！修正しました！（Copilotすごい…！）

2024-12-27 11:42 UTC, sigprogramming commented on src/store/singing.ts
> +            if (state.cancellationOfLabelExportRequested) {
変更漏れでした…！修正しました！
存在しないstateにアクセスしてもエラーにならないのは結構前からですね。

---

原因を調べてみました。
以下のように`Record<string, unknown>`と定義されている`ProxyStoreState`と`DIctionaryStoreState`があり、
https://github.com/VOICEVOX/voicevox/blob/bb5eaa367f1562d9fe1ddc0a5958bdec78b221c6/src/store/type.ts#L2282
https://github.com/VOICEVOX/voicevox/blob/bb5eaa367f1562d9fe1ddc0a5958bdec78b221c6/src/store/type.ts#L2242
これを
https://github.com/VOICEVOX/voicevox/blob/bb5eaa367f1562d9fe1ddc0a5958bdec78b221c6/src/store/type.ts#L2318-L2319
と交差型で繋げて`State`としているのが原因のようです。
（これらをコメントアウトするとエラーが出るようになりました）

2024-12-27 11:47 UTC, sigprogramming commented on src/helpers/fileDataGenerator.ts
> +export async function generateLabelFileData(
`src/store/utility.ts`に移動しました！

2024-12-27 11:57 UTC, sevenc-nanashi commented on src/store/singing.ts
> +            if (state.cancellationOfLabelExportRequested) {
虚無オブジェクトなら`Record<never, unknown>`や<Record<never, never>`の方がよかったはずですね
https://www.typescriptlang.org/play/?#code/C4TwDgpgBAEg9gc2gXigJQgYzgJwCYA8AdhAG4Q4A0UArkQNZFwDuRAfAFCiRQBiNCAIZRUAbw5RJUAGYDBALigBnYDgCWRBBwC+HLuGgBZCkjwjYiaADI+cvdiIqoAWxMQ8i4zlPnxUmXKKAESCQZQ6eq7e7gB0skIcUaYxYGogcEA

PR出します

2024-12-27 11:58 UTC, sigprogramming commented on src/components/Sing/ExportOverlay.vue
> +    return "";
PRありがとうございます！マージ＆少し変更させていただきました！

2024-12-27 15:11 UTC, Hiroshiba commented on src/sing/fileUtils.ts
> +  extension: string,
あまり良い指摘じゃなさそう！

2024-12-27 15:22 UTC, Hiroshiba approved these changes
LGTM！！！

数か所コメントしているのですが、ロジック的には問題ないと思うのでこちらで勝手に変えさせていただいてマージしたいと思います！！

2024-12-27 15:22 UTC, Hiroshiba commented on src/components/Sing/ExportOverlay.vue
> +const exportingInfo = computed((): ExportingInfo => {
（全く問題ないのですが）
`ref<T>`と書くことが多いので、合わせておくとちょっと読みやすいかも！
まあ本当に見やすさだけなので勝手に変えさせていただきます！
```suggestion
const exportingInfo = computed<ExportingInfo>(() => {
```

2024-12-27 15:22 UTC, Hiroshiba commented on src/sing/fileUtils.ts
> +export async function generateUniqueFilePath(
判断が難しいのですが、`window.backend.checkFileExists`を使ってる都合上、store/singing.tsのローカル関数にしたほうが合ってるかもです！
特にコーディング規約があるわけではないのですが、ちょっと勝手に移動させていただこうと思います🙇

store以外からも使うことがあればここに移動しても良いかも･･･！
うーんわからない！！ちょっと頓珍漢な指摘かもです🙇

2024-12-27 15:27 UTC, Hiroshiba commented on src/sing/fileUtils.ts
> +export async function generateUniqueFilePath(
これ、`src/store/audio.ts`のchangeFileTailToNonExistent関数と処理が同じですね！
というTODOコメントを残しつつ、issue切り出ししようと思います！

2024-12-27 15:32 UTC, Hiroshiba commented on src/sing/fileUtils.ts
> +export async function generateUniqueFilePath(
✅ 

- https://github.com/VOICEVOX/voicevox/issues/2440

2024-12-27 15:54 UTC, merged

2024-12-27 16:03 UTC, Hiroshiba commented
こんな感じで28日の18時ごろに宣伝ポストさせていただこうと思います！
Xのアカウントをメンションさせていただいても大丈夫でしたっけ･･･？（ちなみにメンションを書いてる理由は、これを見た人が開発に興味を持ってくださる確率をちょっとでもあげたいなと思っているためです）
問題あればコメントいただけると！！
```
#VOICEVOX開発状況
ソングでもリップシンクなどに便利なlabファイルを出力できるようになりました🎉（今後のアップデートで実装されます。）
【開発者:@m_sig_tw】
https://github.com/VOICEVOX/voicevox/pull/2383
```

2024-12-28 01:59 UTC, sigprogramming commented
@Hiroshiba 
メンション大丈夫です！