Add: プロジェクトのエクスポート機能を追加
VOICEVOX/voicevox pull request #2428
Opened 2024-12-22 12:02 UTC by sevenc-nanashi

## 内容

プロジェクトをmidi等にエクスポートできるようにします。
最悪自前実装できる4つにしました。

## 関連 Issue

（なし）

## スクリーンショット・動画など

![image](https://github.com/user-attachments/assets/035d9bd0-144e-4137-ab24-5bd6f817d8c5)

## その他

（なし）

2024-12-22 12:13 UTC, Hiroshiba commented
まだ全部見きれていませんが、方針良さそうに思いました！

ちょっとUX周りでどうしようか迷う点が１つ思いつきました。
メニューで「エクスポート」と案内すると、音声のエクスポートと勘違いして「.wav無いじゃん」ってなりそうな気配ありますね。
かといって「プロジェクトエクスポート」とするのは若干長く、カタカナ続きなので眼が滑るという。
良い感じの提供方法が無いか考えたいところですねぇ。（そもそも音声エクスポートが離れてるのが課題かも･･･？）

ちなみにメニュー配置のガイドラインをいろんなとこが提供してくれてるので参考になるかもです。
これはappleの例 https://developer.apple.com/jp/design/human-interface-guidelines/the-menu-bar

2024-12-28 20:10 UTC, Hiroshiba reviewed
機能的には良さそう！！
コーディング周りでいろいろコメントしました！

2024-12-28 20:10 UTC, Hiroshiba commented on src/components/Sing/menuBarData.ts
> +        ] satisfies [fileType: ExportSongProjectFileType, name: string][]
とりあえず「プロジェクトをエクスポート」が良さそう。

もしよかったら他のソフトがどうなってるかの調査をお願いしてもよろしいでしょうか 🙇 
XMLに書き出す機能は結構ありそうかなーと。
「エクスポート」とカタカナにしてるか、「プロジェクトを」と案内しているかなどが気になりどころかなと！

2024-12-28 20:10 UTC, Hiroshiba commented on src/store/singing.ts
> +          }
（細かいけど）
こういう小さいの、１行にするとだいぶ見やすくなるので個人的におすすめです。
```suggestion
          if (!dirPath) {
            return { result: "CANCELED", path: "" };
          }
```

ちなみに最初の改行を消してフォーマットかけると１行になります。
```
{
  "hoge":
```
↓
```
{"hoge":
```
↓
フォーマット

見た目は慣れ！

2024-12-29 06:51 UTC, sevenc-nanashi commented on src/store/singing.ts
> +              throw new UnreachableError(`Unexpected fileType: ${fileType}`);
`ufdata`のnarrowingが行われないせいでExhaustiveは使えないんですよね...

2024-12-29 07:06 UTC, sevenc-nanashi commented on src/components/Sing/menuBarData.ts
> +        ] satisfies [fileType: ExportSongProjectFileType, name: string][]
プロジェクトを、がついている系：
![image](https://github.com/user-attachments/assets/4ba752bf-5cc5-4172-8412-4a2cf9b0de16)
![image](https://github.com/user-attachments/assets/11f31cad-17d8-49c9-a1c6-156f5ddde760)

ついていない系：
![image](https://github.com/user-attachments/assets/c8785694-5303-4034-90fc-26d48e22f227)

2024-12-29 07:20 UTC, sevenc-nanashi commented on src/backend/browser/fileImpl.ts
> +
> writeFileImplのシグネチャにtype: "path" | "fakePath"を足して、typeで処理を分岐する

これ、結構難しいような？ブラウザ版の都合を（Electron版とかも使う）メインロジックの`backend.writeFile`とかに入れるのは少し微妙な気がします。
`isFakePath(path: string): path is FakePath`を作る...？

2024-12-29 07:28 UTC, Hiroshiba commented on src/store/singing.ts
> +              throw new UnreachableError(`Unexpected fileType: ${fileType}`);
あ～　include君もうちょっと頑張ってほしいですね･･･

サポートするプロジェクトファイル形式が増えたとき、こっちに足し忘れる可能性を考えると、`default`は微妙に危ないかもとちょっと思いました。
でもTypeScript的に妥当な方法がない。。。。。
（↓みたいに書いてみたけどnarrowingされませんでした。。）

```ts
const multiables = {
  ust: true,
  musicxml: true,
  smf: false,
  ufdata: false,
} as const satisfies { [K in ExportSongProjectFileType]: boolean };

if (state.trackOrder.length > 1 && multiables[fileType]) {
```

うーん！　`UnreachableError`で良さそう！！

2024-12-29 07:30 UTC, Hiroshiba commented on src/store/singing.ts
> +              throw new UnreachableError(`Unexpected fileType: ${fileType}`);
あ、それかまあ、こうするか。。。。。。
```ts
          switch (fileType) {
            case "musicxml":
              tracksBytes = await project.toMusicXml();
              extension = "musicxml";
              break;
            case "ust":
              tracksBytes = await project.toUst();
              extension = "ust";
              break;
            case "smf":
            case "ufdata":
              throw new UnreachableError(fileType);
          }
```

2024-12-29 07:36 UTC, Hiroshiba commented on src/backend/browser/fileImpl.ts
> +
！！　たしかに！！！！

型ガード関数作るに賛成です！
ロジックは「`fileHandleMap`にあるかどうか」じゃなく、想定してるstringが来てそうかで判断する感じが良さそう･････？

2024-12-29 07:44 UTC, sevenc-nanashi commented on src/backend/browser/fileImpl.ts
> +
そんな感じにしてみました。

2024-12-30 11:57 UTC, Hiroshiba commented
再レビュー可能な状態でしょうか？ 👀 　（催促ではなく確認です！）

2024-12-30 12:11 UTC, sevenc-nanashi commented
あ、一通り修正したはずです。

2024-12-31 04:38 UTC, Hiroshiba commented on src/store/singing.ts
> +              firstFilePath = filePath;
たぶんresolve！

2024-12-31 04:41 UTC, Hiroshiba commented on src/components/Sing/menuBarData.ts
> +        ] satisfies [fileType: ExportSongProjectFileType, name: string][]
おーーーありがとうございます！！！！
意外とproject付けてるソフト多そうですね！

Voisonaは「エクスポート」→プロジェクト系ファイルって感じでした。
![image](https://github.com/user-attachments/assets/10a25f65-7015-4a41-b183-47999e7f66a9)

いったん「プロジェクトをエクスポート」で良さそう！！
ありがとうございます！！！

2024-12-31 05:32 UTC, Hiroshiba approved these changes
`showAudioSaveDialog`とかが削除できてて素晴らしいですね！！！！！

いろいろコメントはしていますがほぼLGTMです！！！

2024-12-31 05:32 UTC, Hiroshiba commented on src/components/Sing/menuBarData.ts
> +        ] satisfies [fileType: ExportSongProjectFileType, name: string][]
細かいけど気づいてしまったので
```suggestion
        ] satisfies [fileType: ExportSongProjectFileType, label: string][]
```
（下の引数名がlabel）

2024-12-31 05:32 UTC, Hiroshiba commented on src/sing/utaformatixProject/utils.ts
> +export const singleFileProjectFormats = ["smf", "ufdata"] as const;
細かいけどみやすさ向上のため
```suggestion

export const singleFileProjectFormats = ["smf", "ufdata"] as const;
```

2024-12-31 05:32 UTC, Hiroshiba commented on src/store/singing.ts
> +            path.basename(filePath, `.${extension}`),
ここbasenameにしてる意図は何でしょうか？ 👀
ディレクトリ指定したときに意図しない場所に書き出されそう･･･？

（と、ChatGPTさんに指摘もらって気付いた）
https://chatgpt.com/share/67737d62-a1b4-8008-8d48-aa46b7820803#:~:text=1.%20%E3%82%B7%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E6%9B%B8%E3%81%8D%E5%87%BA%E3%81%97%E6%99%82%E3%81%AB%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%83%91%E3%82%B9%E3%81%8C%E6%AC%A0%E8%90%BD%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B

2024-12-31 05:32 UTC, Hiroshiba commented on src/store/singing.ts
> +          multiFileProjectFormats.includes(fileType as MultiFileProjectFormat)
ちょっとやりすぎかもですが、`isMultiFileProjectFormat`を切り出しても良いかもですね。
`multiFileProjectFormats`をexportしなくて良くなり、includesを使うロジックを隠蔽でき、asが妥当かも近くにコードが配置されるのでわかりやすくなるかな～と

2024-12-31 05:32 UTC, Hiroshiba commented on src/store/singing.ts
> +            fileType as MultiFileProjectFormat,
isMultiFileProjectFormatにするとここのas消せるかも

2024-12-31 05:32 UTC, Hiroshiba commented on src/store/singing.ts
> +          };
細かいけど、万が一`""`なパスが返ってしまったら結構危険な気がするので、初期値はundefinedのが良さそう。
```suggestion
          let firstFilePath;
          for (const [i, trackBytes] of tracksBytes.entries()) {
            const filePath = await actions.GENERATE_FILE_PATH_FOR_TRACK_EXPORT({
              trackId: state.trackOrder[i],
              directoryPath: dirPath,
              extension,
            });
            if (i === 0) {
              firstFilePath = filePath;
            }

            const result = await actions.EXPORT_FILE({
              filePath,
              content: trackBytes,
            });
            if (result.result !== "SUCCESS") {
              return result;
            }
          }
          if (firstFilePath == undefined) {
            throw new Error("firstFilePath is undefined.");
          }

          return { result: "SUCCESS", path: firstFilePath };
```

2024-12-31 05:32 UTC, Hiroshiba commented on src/store/singing.ts
> +            };
気づいてしまったので
```suggestion
            return { result: "CANCELED", path: "" };
```

2024-12-31 05:32 UTC, Hiroshiba requested changes
間違えました 🙇

2024-12-31 05:41 UTC, sevenc-nanashi commented on src/store/singing.ts
> +            path.basename(filePath, `.${extension}`),
あ、シンプルにミスですね...

2024-12-31 05:41 UTC, sevenc-nanashi commented on src/store/singing.ts
> +          multiFileProjectFormats.includes(fileType as MultiFileProjectFormat)
切り出しました。結構なasがなくなってすっきりしました。

2024-12-31 05:43 UTC, sevenc-nanashi commented on src/backend/browser/fileImpl.ts
切り出しました。

2024-12-31 05:50 UTC, sevenc-nanashi commented on src/backend/browser/fileImpl.ts
>  export const writeFileImpl: (typeof window)[typeof SandboxKey]["writeFile"] =
良い感じに分けました。

2024-12-31 13:33 UTC, Hiroshiba reviewed
あとちょい！！

2024-12-31 13:33 UTC, Hiroshiba commented on src/store/singing.ts
> +        // それ以外の場合は単一ファイルの形式を選択する
（ただのみやすさ）
```suggestion

        // それ以外の場合は単一ファイルの形式を選択する
```

2024-12-31 13:33 UTC, Hiroshiba commented on src/type/ipc.ts
>    };
型定義側（`src/type/ipc.ts`）と順番がごっちゃになっちゃってるかも･･･？
この下に`SHOW_PROJECT_LOAD_DIALOG`があって読み込み系があるので、まあとりあえず戻しちゃっても良いのかも。

2024-12-31 13:38 UTC, sevenc-nanashi commented on src/type/ipc.ts
>    };
あれ、コメント位置が間違ってそう？

2024-12-31 13:42 UTC, Hiroshiba commented on src/type/ipc.ts
>    };
あ、逆でした！
`src/backend/electron/main.ts`の`registerIpcMainHandle<IpcMainHandle>`側とずれてそうで、`src/type/ipc.ts`側を戻すのが良いかなという意図でした！

2024-12-31 15:38 UTC, Hiroshiba approved these changes
LGTM！！

なんかまだ順序変わってる気がしますが、こっちで直しちゃいます！
https://github.com/VOICEVOX/voicevox/pull/2428/files#diff-a6f4b99080d20781616d3df78a9a8da0e260ce4aa039913695675ac57b4aa031

2024-12-31 16:00 UTC, Hiroshiba commented
こんな感じで明日の15時ごろにポストしたいと思います！
```
#VOICEVOX開発状況 
ソングプロジェクトファイルを別の形式でエクスポートできるようになりました 🎉（今後のアップデートで実装されます。）
【開発者:@sevenc_nanashi】
https://github.com/VOICEVOX/voicevox/pull/2428
```
↓添付画像
<img width="476" alt="a" src="https://github.com/user-attachments/assets/0fc10191-e86e-470d-9b8c-511b51ce6b69" />

2024-12-31 16:00 UTC, Hiroshiba commented
マージします！！

2024-12-31 16:00 UTC, merged