デフォルトスタイル選択画面を実装
VOICEVOX/voicevox pull request #354
Opened 2021-10-15 19:12 UTC by MT224244

## 内容

各キャラクターのデフォルトスタイルを選択する画面を実装しました

## 関連 Issue

close #293

## スクリーンショット・動画など

![image](https://user-images.githubusercontent.com/25514849/137539210-58871e1e-224d-4a47-838e-0c2adf5eca5d.png)
![image](https://user-images.githubusercontent.com/25514849/137592603-abe5cf67-8c04-4a21-857a-a978f26385eb.png)

## その他

- [x] 初回起動時に画面を開く
- [x] いつでも開けるようにする
- [x] 音声サンプルを再生する
- [x] AudioCellのデフォルトをこの画面で選択したものにする

2021-10-16 07:11 UTC, Hiroshiba commented
すごくいいですね！！！
キャラクター＋スタイルを全通り並べるのを想像していましたが、キャラクターごとに１画面にするほうが良いなと感じました！！
デザインはゆっくり考えて、もし変更がある場合でもこちらでちょこっと変えさせていただこうと思います。
「次へ」「戻る」のフッターは、ヘッダーの右上に配置すると画面が広くて見やすいかもと思いました！

2021-10-16 14:08 UTC, MT224244 commented
ヘッダーはウィンドウ幅を狭めていくとボタンを置く余裕がないので下に置いています
(既に※がはみ出してたりで崩れてしまっているのでこれも修正する予定です)

![image](https://user-images.githubusercontent.com/25514849/137588679-340cee50-e548-4a77-9f5a-047ac2b058a7.png)

2021-10-16 18:26 UTC, MT224244 commented
ヘッダーへのボタン配置、なんとかなったのでこれでいこうと思います！

![image](https://user-images.githubusercontent.com/25514849/137598117-f381d26c-82a9-4e52-bfd4-938db719af41.png)
![image](https://user-images.githubusercontent.com/25514849/137598126-a0072c6e-4cb5-4a6b-8f9f-292a3cfe5a69.png)

音声サンプルについては後々質問させていただくつもりでした、ありがとうございます…！

2021-10-18 18:40 UTC, MT224244 commented
> スタイル選択する際、右上のボタンだけではなく、スタイル枠全体のどこをクリックしても選択されるようにするとユーザビリティが更に上がると思います！

スタイル枠全体がクリック可能であることが分かるように、ボタンと同じくhoverで色が変わったりクリック時にrippleさせることになると思うのですが、再生ボタン上にカーソルがある状態でもhoverやrippleが反応してしまいます
再生ボタンクリック時にボタンとスタイル枠全体の両方がrippleしてしまって見た目が残念な感じになったので、ラジオボタンのみクリック可能にしました

…これを書いている間に回避できそうな方法を思いついたので、実装してみます

> 細かいですが、音声サンプルと製品版のスタイルが対応していないかもしれません。

すみません、これは #335 の時点で既にズレてしまっていました…
放送やツイートにて順序が違うというのは認識していたはずですが、実装時完全に忘れていました

> UXデザインをどうするか迷っているので、なにかアイデアや参考例をお聞きしてみたいです。

ウェルカム画面っぽくするのであれば、よくあるセットアップウィザードのようにするといいかもしれません

```
ようこそ > デフォルトスタイル設定 > CPU/GPUモード等の初期設定 > 完了
```

Quasarにはまさにこの用途のための [QStepper](https://quasar.dev/vue-components/stepper) というコンポーネントがあります

2021-10-19 14:54 UTC, Hiroshiba requested changes
良いですね！！
コードを読んでコメントしてみました！

2021-10-19 14:54 UTC, Hiroshiba commented on src/background.ts
> +      defaultStyleId,
characterInfoの他の値はユーザーによって決まらない値で、`defaultStyleId`だけ役割が違う印象を受けました。
なんとなくstateのrootなどにあったほうが良さそうに感じたのですが、どうでしょう。

2021-10-19 14:54 UTC, Hiroshiba commented on src/components/DefaultStyleSelectDialog.vue
> +      selectedStyleIndexes.value = characterInfos.value?.map((info) =>
ここcomputedにできるかも？
（まあそんな頑張る場所でもないかもなので、watchのままでも良いかなと思いました。）

2021-10-19 14:54 UTC, Hiroshiba commented on src/views/Home.vue
> +      let styleId: number | undefined = undefined;
undefinedにしても大丈夫な理由がちょっとわかりませんでした。
（別のところで if undefined がある・・・？）

2021-10-21 12:52 UTC, merged