[WIP] プリセット機能の作成 (#300 の後続)
VOICEVOX/voicevox pull request #428
Opened 2021-10-31 17:15 UTC by Segu-g

## 内容

#300 の引継ぎPRです．
プリセット機能を追加します．

#300での議論により，このプリセット機能では

+ プリセット値の登録・編集・削除
+ プリセット値の保存（グローバル設定・electron storeに保存）
+ セルを追加した際にアクティブなセルのプリセット値を適応
+ 選択しているセルにプリセット値を適応

を実装します．

プリセットとして保存する項目は

+ プリセットタイトル
+ speaker番号
+ 話速
+ 音高
+ 抑揚
+ 音量
+ 開始無音
+ 終了無音
です．

登録したプリセットのデータは設定の値と同様にelectron storeに保存します．

## 関連 Issue

ref #67

## スクリーンショット・動画など

## その他

2021-10-31 17:37 UTC, Hiroshiba commented
> プリセットとして保存する項目

キャラクターにプリセットを紐付けるか、全キャラ統一にするか迷いますね・・・
どっちも需要があると思っているのですが、たぶん実装が簡単なので全キャラ統一で実装してみるのが良いのかなと感じました！
となると`speaker番号`が不要になるかも？

2021-11-21 12:00 UTC, Hiroshiba reviewed
かなり大きめの機能で、ちょっとこちらの工数的に次のアップデートに組み込むのは難しいかもしれません。申し訳ないです。

とりあえず動かしてみました！
プリセット周りの再適用ってどういう結論になったんでしたっけ・・・？
（再適用はなしにする・・・？）

2021-11-21 23:18 UTC, Segu-g commented
こちらこそ遅くなってしまい申し訳ありませんでした。
再適用についてはプリセット値を設定した際にセルに自動で適応されるようになっていますが、現在のプリセット値を再適用する操作がありませんでしたね。AudioInfoに`プリセット値に戻す`のようなボタンを置く方向で大丈夫でしょうか？

2021-12-01 18:51 UTC, Hiroshiba commented
すみません、遅くなりました。挙動に関していろいろ議論しました。
こんな感じでお願いします・・・！

* プリセットはマスターに保存
* セルごとにプリセットIDを保存
* セルのパラメータをプリセット値から値を変更しても、持っているプリセットIDを変えない
* プリセット上書き時に、同じプリセットIDを持つ全てのセルにそのプリセットを再適用するか聞く

以下、メモです

![image](https://user-images.githubusercontent.com/4987327/144295390-3d787c46-6fcb-46e2-97ef-c6ca5b90d3cc.png)
![image](https://user-images.githubusercontent.com/4987327/144295449-242c4e51-d8c7-4ae7-bd04-c9365363fcb2.png)
![image](https://user-images.githubusercontent.com/4987327/144295574-e3e32d43-44f9-44cc-82ba-83a377b2ebe3.png)

2021-12-02 18:49 UTC, Hiroshiba requested changes
（Request changesにし忘れていたのでそのためだけのコメントです）

2021-12-03 09:19 UTC, Segu-g commented
再適用の為のボタンを追加し，上書き時にそのプリセットが設定された全てのセルに適用するかどうかの選択肢を追加しました．
![image](https://user-images.githubusercontent.com/51497552/144577266-6023749e-137a-43a0-9841-47fd5114de9d.png)
![image](https://user-images.githubusercontent.com/51497552/144577042-8ffc721a-d7e7-4a6f-84cf-9af759ea4d94.png)

2021-12-03 09:27 UTC, Segu-g commented
なお，現在のUIでは「あるプロジェクトで上書きしたプリセットを別のプロジェクトでも全適用したい」といったユースケースに対応できない(再度同じパラメータで上書きしないと全適用ができない)ので，全適用のボタンも必要だと感じましたがどうでしょうか．

2021-12-05 11:47 UTC, MT224244 requested changes
いくつか気になった箇所があったのでコメントしました！

2021-12-05 11:47 UTC, MT224244 commented on src/store/audio.ts
> +      const { name: _, ...presetAudioInfos } = presetItem;
`@typescript-eslint/no-unused-vars` の元である[no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)を見てみると `ignoreRestSiblings` というオプションがあるらしく、これをtrueにするとeslint-disable-next-lineしなくてよくなるかもしれません。
ただ、ESLintのルール変更をこのPRでやってしまっていいのかは分かりません…。

2021-12-05 11:47 UTC, MT224244 commented on src/components/AudioInfo.vue
> +        <q-btn-dropdown dense flat icon="more_vert">
▼アイコンは無い方が見た目がスッキリするかなと思いました。

![image](https://user-images.githubusercontent.com/25514849/144744547-c765dd54-9970-4454-9bf8-be189990057c.png)
(この画像はDevToolsで要素を消しただけなので、実装するならCSSを弄る必要がありそうです。)

2021-12-05 16:18 UTC, y-chan reviewed
いくつか気になった点をコメントしてみました。

2021-12-05 16:18 UTC, y-chan commented on src/components/PresetManageDialog.vue
> +      store.dispatch("DELETE_PRESET", { presetKey: key });
プリセットをサクッと削除できるのが気になりました。
間違って削除してしまうことの無いように確認ダイアログが欲しいなと思いました。

2021-12-05 16:18 UTC, y-chan commented on src/components/AudioInfo.vue
> +      },
単純にデザインの問題で、大きな問題ではないと思うのですが、プリセットを選択していない時にも解除の選択肢が出ているのは若干気になりました。
技術的背景によって難しいのであれば、このままでもよいと思いますが、できれば`プリセットはありません`と表示した方がきれいだなと思いました。
![image](https://user-images.githubusercontent.com/34832037/144754224-0ba01a4e-dfd4-4827-ba47-74ea9bdbb84a.png)

2021-12-05 16:18 UTC, y-chan commented on src/components/AudioInfo.vue
> +        <q-btn-dropdown dense flat icon="more_vert">
公式ドキュメントの使用例でも、modelを使わずに動かしているものばかりなので、ドキュメント側のミスである可能性が高い気がしますね...
このままで問題ないと思いました。

2021-12-05 16:30 UTC, MT224244 commented on src/components/AudioInfo.vue
> +        <q-btn-dropdown dense flat icon="more_vert">
型エラーも出ているので必須なのは間違ってなさそうなんですよね…。
ドキュメントと型両方が間違っている可能性もありますが…。
まぁどちらにせよ無くても今のところ正常に動作していそうですし、何か変な挙動が見つかった時に対処すればよさそうですね。

![image](https://user-images.githubusercontent.com/25514849/144754714-fb22f994-035a-4b08-b0b9-189fd50f162c.png)

2021-12-05 16:33 UTC, y-chan commented on src/components/AudioInfo.vue
> +        <q-btn-dropdown dense flat icon="more_vert">
なるほど、ドキュメントを見ると、型はBoolean、内容は`Controls Menu show/hidden state;`ということで、適当にtrueでも渡しておけば良さそうに感じました。

2021-12-05 16:36 UTC, MT224244 commented on src/components/AudioInfo.vue
> +        <q-btn-dropdown dense flat icon="more_vert">
trueを渡すと表示された時に自動で開いてしまうので、渡すならfalseがいいですね。

2021-12-06 12:37 UTC, Segu-g commented on src/store/audio.ts
> +      const { name: _, ...presetAudioInfos } = presetItem;
Typescriptの分割代入によるomitは型を綺麗にしたままプロパティのフィルタを書けます．
Typescriptだと便利なのでルール変更もこのプルリクでしたいと思います．

2021-12-06 12:55 UTC, Segu-g commented
修正しました。確認をよろしくお願いします。
![image](https://user-images.githubusercontent.com/51497552/144849431-352c66b8-cfe2-49ce-ab74-7100c9c56fd1.png)
![image](https://user-images.githubusercontent.com/51497552/144849462-01021785-ae89-4837-85e7-9098187b4ba2.png)

2021-12-06 16:39 UTC, MT224244 approved these changes
LGTM!

2021-12-06 22:53 UTC, y-chan approved these changes
LGTMです!

とても規模の大きいPRでしたが、綺麗にまとまり良い機能となっていると思います...!

議論・実装お疲れ様でした...!

2021-12-07 16:05 UTC, Hiroshiba reviewed
マージします！
@Oyaki122 さんもありがとうございました！！

2021-12-07 16:05 UTC, Hiroshiba approved these changes

2021-12-07 16:06 UTC, merged