ツールバーのボタンをカスタマイズ可能にする
VOICEVOX/voicevox pull request #489
Opened 2021-11-17 14:59 UTC by y-chan

## 内容

題の通りです

## 関連 Issue

close #462 

## スクリーンショット・動画など

## その他
メニューバーの機能をコピペしてる部分があるので、それをどこか機能関数をまとめたファイルなどにまとめたい感じがあります。

2021-11-18 15:23 UTC, Hiroshiba requested changes
すごく良いですね！！

２つだけ気になる点がありました。

---

１つ目は実装のコピーが発生している点です。
generateAllAudio()などがMenuBarとHeaderで重複していて、おそらくこのままだと別の修正が入ったときに片方だけアップデートが入ってもう片方がバグるということが容易に起こり得てしまいます。
解決方法は色々ありますが、難度が簡単な方から提案すると

* utility関数を作って書き出す
* VUEXのactionに移動して、$q.dialogが必要とするobjectを返し、$q.dialogだけを複製する
* $q.dialogの依存をなくしてVUEXだけで完結するようにし、VUEXのactionを移動する

などがありそうです。
個人的には最初のだとコードの見通しが悪くなるので避けたいです。
最後のが一番綺麗ですが、たぶんだいぶ難しいので、２番めの方法が良いのではと思いました。

---

２つ目はカスタマイズ中のUIです。

ツールバーカスタムダイアログの見た目が、上から「ツールバー」「プレビュー中」「プレビュー」と３つの帯が重なっているのがちょっと気になりました。
たぶん「ツールバー」の部分に「プレビュー」があるのがきれいなのですが、こうすると現在地がわかりにくくなるのが課題になると思います。

これはiOSアプリの移動UI（アプリがワナワナするやつです）のように、違和感を与えればそれはプレビュー中であることがわかるかもしれません。
空白を表示したり、背景の色をちょっと暗くしたりするとわかるかもしれないと思いました。

---

それ以外のとこはとても良いと思います！
D&D可能にするとユーザーからは喜ばれそうですが、工数が大きそうなので一旦このPRの内容でマージしたいです！

2021-11-19 14:20 UTC, y-chan commented
同一コードが複数個所あったのは、すべてVuex Storeに移動させました。

そして、UIに関してはツールバーの表示順を少し入れ替え、その上で編集中の画面であることを強調するようなUIにしました。

加えて、UIが変更されていない場合は、保存ボタンを押せなくしたり、ボタンホバー時にdescと同じツールチップを表示するようにしました。

![voicevox_custom_toolbar2](https://user-images.githubusercontent.com/34832037/142637510-98a05adc-d1cb-4828-b2dd-381516ce3c44.gif)

2021-11-21 11:24 UTC, y-chan commented
コンフリクトの解消・テストが回らない問題を修正しました。
よろしくお願いします。

2021-11-21 12:49 UTC, Hiroshiba reviewed
すごく良いですね！！！！直感的に操作できると思います。

もうこのままリリースしてもぶっちゃけ大丈夫だと思うのですが、
より洗練できるかもと感じた部分をコメントしてみます。

1. プレビューとタイトルバーどちらを上にするかですが、タイトルバーが上の方が良いのかなと思いました。
理由はいろいろですが、操作される対象と操作するボタンは近いほうが良いとかです。
（議論の余地があるかもです）

2. 開いている状態で「設定」ボタンを押すと閉じれるのですが、ここでも保存するかを聞くと良いかもと思いました。

3. 保存の横に「デフォルトに戻す」があっても良いなと感じました。
（が、実装難しそうならとりあえずなくても良いと全然思います）

2021-11-21 18:56 UTC, y-chan commented
> タイトルバーが上の方

タイトルバーを上に戻しました！まあプレビュー中であることはすでにわかると思うので、これで良さそうですね...!

> 開いている状態で「設定」ボタンを押すと閉じれる

設定ボタンなどを押したときに閉じれてしまうのは盲点でした...
これに関しては、押した時点でダイアログを開くように修正しました。
なお、ヘルプに関しては直接開けてしまうので、以下のような挙動をしてしまいます。
![help_issue](https://user-images.githubusercontent.com/34832037/142773997-2721595f-3e70-40a1-86eb-cd282890d733.gif)
これに関して、解決策が2つあります。
1. ヘルプをそもそも表示せずに破棄確認ダイアログを出す。
  ![help_issue1](https://user-images.githubusercontent.com/34832037/142774110-9af6c903-dc4f-435b-975e-fd377155bc22.gif)
2. ヘルプを裏で表示して、キャンセル時はヘルプを見れるようにする。
  ![help_issue2](https://user-images.githubusercontent.com/34832037/142774156-cd9a946c-0ac5-4900-9629-2ff8128dc122.gif)

2の挙動の方がユーザー的には好ましいのかもしれないですが、若干気持ち悪いという点があります。
どちらがいいか、これに関しては議論ができるところだと思うので、まだ適用していません。

> 保存の横に「デフォルトに戻す」があっても良い

少し苦戦しましたが、 #472 を元に追加しました！
![toolbar_default](https://user-images.githubusercontent.com/34832037/142775193-c8805d29-d2b4-4863-a9e6-83a0517247ab.gif)

加えて、レビューには書かれていませんが、すべてのボタンを消したときの挙動を改善し、`「ボタン名」を`で途切れていた文章を`「ボタン名」を選択中`に変更しました。
![image](https://user-images.githubusercontent.com/34832037/142774329-8bf7e42b-3e19-4e65-993c-bc3e7336f757.png)
![image](https://user-images.githubusercontent.com/34832037/142774350-db15dc88-6e07-43e6-a425-342aec22a85d.png)


また、ダークテーマ時適用時の色が変になる現象を解消しました。
例えば、色の指定がおかしくなっており、「右に動かす」「左に動かす」等のボタンが暗闇に消えてしまっていたり、以下のようにトグルボタンが見にくくなってしまっていたりする問題です。
before
![image](https://user-images.githubusercontent.com/34832037/142773881-9f07692e-70b1-4a03-ba64-4d6956756ded.png)

after
![image](https://user-images.githubusercontent.com/34832037/142773901-838ea65f-216b-4663-aabb-46a11caf5ab9.png)

2021-11-23 08:31 UTC, Hiroshiba commented
> 開いている状態で「設定」ボタンを押すと閉じれる

うーん･･･比較的ロジックが簡単そうなので、1でお願いします！！

このプルリクエストで組み込む内容じゃないですが、そもそもダイアログを開いたときはメニューボタンを押せなくなるようにしたほうが良い気がしてきました。

2021-11-23 09:11 UTC, y-chan commented
> 1でお願いします！！

適用しました！

> そもそもダイアログを開いたときはメニューボタンを押せなくなるようにしたほうが良い

確かにそうかもしれませんね….
後でIssue化しますね…!

2021-11-28 13:49 UTC, y-chan commented
コンフリクトを解消し、#518 のおかげで、不要になった部分を削除しましたり、一部文言の統一をしたりしました。

2021-12-02 12:58 UTC, Hiroshiba commented
`GENERATE_AND_SAVE_ALL_AUDIO_WITH_DIALOG`などが共通化されて良い感じだと思いました！
ただその関係で変更行数がなかなか多くなっていて、なにか間違いがあっても気づけないようになっていそうな気がしました。

`GENERATE_AND_SAVE_ALL_AUDIO_WITH_DIALOG`などのアクションを共通化する部分と、ToolBarをカスタマイズ可能にする部分に分けると変更行数を少し小さくできるのかなと感じました。
どうでしょう・・・？

2021-12-02 13:09 UTC, y-chan commented
> GENERATE_AND_SAVE_ALL_AUDIO_WITH_DIALOGなどのアクションを共通化する部分と、ToolBarをカスタマイズ可能にする部分に分ける

なるほど、少し切り分けてみますね

2021-12-02 15:13 UTC, Segu-g requested changes
@Hiroshiba さんが見られたようですが全体を見て，特に気になった部分をコメントしました．
正直，あまり正しいことを言っている自信がないのでダブルチェックして頂けると助かります．．．

2021-12-02 15:35 UTC, y-chan commented on src/components/HeaderBarCustomDialog.vue
> +    });
おっと、everyを使う手法は気づきませんでした。
そちらの方がきれいだと思うので、そちらで書き直してみたいと思います。

2021-12-02 15:36 UTC, y-chan commented on src/components/HeaderBar.vue
> +      text: ToolbarButtonsType;
なるほど、確かに言われてみれば、テキストだけを変更したい時を考えていませんでした。
識別子化は非常に良い解決策だと思うので、対応に当たりたいと思います。

2021-12-02 15:37 UTC, y-chan commented on src/components/HeaderBar.vue
>      };
仰る通りです。
少々複雑な処理になっているのは否めないので、もう少しきれいにできないかなとは思いましたが、私にはこれが今のところ限界でした。

2021-12-02 15:45 UTC, y-chan commented on src/components/HeaderBar.vue
> +    ];
> textもcomputedにすれば

確かに、これを機に再生と停止を同じボタンにまとめてしまうのは良いと思いました。
そうすれば、上のレビューであった`continuouslyFlag`の利用をしなくて済むので、複雑度が下がりそうです。
ただ、このPR内で再生と停止をまとめてしまっていいかが微妙な気がします。

また、ボタンカスタマイズの時点で、再生と停止の両方を行えるボタンであることを示すことが難しいような気もしています。
何かいい方法はないですかね...?

> ツールバーに配置可能なactionの多くはHotKeyでも操作可能な処理

actionにまとめてしまう感じのことは、`WITH_DIALOG`系の処理で一度行っていますが、それ以外はこれ以上まとめられないような気がしています。getterを増やすのは良いかもと思いました。ちょっと検討してみます。

2021-12-02 15:47 UTC, y-chan commented on src/components/HeaderBar.vue
> +        return usableButtons.find((b) => b.text === button) as ButtonContent;
型レベルで強制できる、確かに仰る通りです。

findの使い過ぎは私も少し感じていたので、オブジェクト化を試みようと思います。

2021-12-02 15:48 UTC, y-chan commented on src/components/HeaderBarCustomDialog.vue
> +                >
三項演算子が増えそうで、ちょっとコードの可読性が落ちそうだったので手を付けていなかったのですが、仰る通りそれよりもコードを縮める方がよいかもしれません。
少し検討してみます。

2021-12-02 15:52 UTC, y-chan commented on src/store/setting.ts
> +    },
確かに、仰る通りなのですが、他のactionが同じような形だったのであまり気にしていませんでした。
修正してみようかと思います。

2021-12-02 17:09 UTC, MT224244 reviewed
レビューしてみました。
型に関して気になったところがあったのでコメントしました。

2021-12-02 18:25 UTC, Segu-g commented on src/components/HeaderBar.vue
> +    ];
> ボタンカスタマイズの時点で、再生と停止の両方を行えるボタンであることを示すことが難しいような気もしています。
UIについて私は詳しくないので素人なのですが，押してみれば分かりますしこれまで使っていた人が最初見た時に混乱する程度でしょうか．特に記載を行わなくても問題はなさそうな気もしますが@Hiroshiba さんに意見を貰いたいです．

それとは別に今気づいたのですが，ContinusllyフラグをAudioStateに置くべきだと思いました．どちらにしても現在の実装ではShift+Space等の別経路で連続再生したときに，連続再生したか単体再生したかHeaderBarでは判別ができないからです．
とはいっても今の実装では，STOP_AUDIOを叩いてもSTOP_CONTINUOUSLY_AUDIOを叩いてもどちらでも停止してくれるようなので分岐を間違えてもバグにはないようです．STOP_CONTINUOUSLY_AUDIOだけ叩いていても問題にはならないのですが...

> ツールバーに配置可能なactionの多くはHotKeyでも操作可能な処理
ショートカットキーは一部を除いてコンポーネントに所属しないグローバルな操作なのでショートカットキーの多くはactionとして記載でき，ツールバーにも置けるかなと思いましたがこのPRでする必要は特にないと思いました．testablityが改善しそうだったので提案しましたが忙しいならこのままでも構わないと思います．

2021-12-02 18:56 UTC, y-chan commented on src/store/type.ts
> +      saveAllResultDialog: unknown;
ここをDefineComponentにしなかったのは、型の調製がとてつもなくしんどかったからです(DefineComponentに渡すgenericsの引数まで合わせないと型エラーになってしまうので)

何かいい方法があればいいのですが、うまくいきそうにないので、この旨をコメントとして残しておくべきかなとは思いました。

2021-12-02 18:56 UTC, Hiroshiba commented on src/components/HeaderBar.vue
> +    ];
再生と停止を同じボタンにするのは別機能なので、とりあえずこのPRではしない方針で良いと思います。
UI上もそこまで大きな問題ではないので、要望が来るまではまあ良いかなと。

> 別経路で連続再生したときに，連続再生したか単体再生したかHeaderBarでは判別ができない

こちら目からウロコでした。見逃していました･･･レビュー感謝です。

2021-12-02 19:11 UTC, y-chan commented on src/components/HeaderBar.vue
> +    ];
> > ボタンカスタマイズの時点で、再生と停止の両方を行えるボタンであることを示すことが難しいような気もしています。
>
> 押してみれば分かりますし

確かに、プレビュー時点で押せば表記が切り替わるみたいな挙動をさせるのは良いと思いました。

ただ、やはり再生(連続再生)と停止のボタン統合は別PRで行うべきな気がします。
一旦切り出したいところですね。

> ContinuslyフラグをAudioStateに置くべき

おっと、この問題は気づきませんでした...(私がボイボにおいてほとんどホットキーを使わないので、そこまで頭が回っていませんでした...)
この問題を解決する(continuslyをstateに持っていく)ついでに、ショートカットキーの多くをactionに移行するというのはありな気がします。
ただ、一部の例外を置いておくなどはそれはそれで気持ち悪いような気もしますが....
どちらにせよ、このPRの規模が大きくなる一方な気がするので、やるならば別PRへの切り出しが必要そうです。

> STOP_CONTINUOUSLY_AUDIOだけ叩いていても問題にはならないのですが...

(もうSTOP_CONTINUOUSLY_AUDIOをSTOP_AUDIOと統合してもいいんじゃないかなって個人的には思います...)

2021-12-03 00:10 UTC, MT224244 commented on src/store/type.ts
> +      saveAllResultDialog: unknown;
> DefineComponentに渡すgenericsの引数まで合わせないと型エラーになってしまう

おっと…これは確認不足でした。
なるほど、であれば確かにDefineComponentは適切ではないですね…。

2021-12-05 13:14 UTC, y-chan commented
ちょっと、PRの規模が大きすぎるのと、同時にレビューでの改善点もかなりあるので、細分化してPRを作り直そうかと思います。

一旦closeしたいと思うのですが、どうでしょうか...?

2021-12-05 13:23 UTC, Hiroshiba commented
良いと思います！

2021-12-05 13:30 UTC, y-chan commented
一旦クローズします!

2021-12-05 13:30 UTC, closed without merging