利用率の収集のためのGoogle Tag Managerの組み込み
VOICEVOX/voicevox pull request #497
Opened 2021-11-20 15:07 UTC by mes51

## 内容

Google AnalyticsでUIのクリックやウインドウサイズ等の情報を収集し、改善に利用できるようにGoogle Tag Managerを組み込みます
収集はオプトインとし、起動時、および設定からON/OFF切り替えられるようにしています

## 関連 Issue

close: #487 

## スクリーンショット・動画など

![image](https://user-images.githubusercontent.com/936617/142730663-15be7e09-8896-4609-a67e-e820b107d9e6.png)

![image](https://user-images.githubusercontent.com/936617/142730700-16397026-60bf-4bc2-aa41-6d41ac3ca5ce.png)

## その他

文は仮で入れているので、お手数ですがプライバシーポリシーの策定に合わせ修正をお願いします
https://marketingplatform.google.com/intl/ja/about/analytics/tag-manager/use-policy/
https://marketingplatform.google.com/about/analytics/terms/jp/

## TODO

- [ ] Google Tag Managerの設定の追記

2021-11-20 17:42 UTC, mes51 commented
Google Tag Managerの設定方法の記述がまだ終わっていないためDraftとなっていますが、コード的にはこれで提出となるため、レビュー自体は開始していただいて問題ありません

2021-11-21 03:20 UTC, Yosshi999 requested changes

2021-11-21 03:20 UTC, Yosshi999 commented on src/components/TelemetryAcceptDialog.vue
> +          unelevated
「同意しない」ボタンが若干目立たなすぎな気がします。styleにborderを適用して枠線を付けるなどしてボタン感を強めるのはどうでしょうか

2021-11-21 08:56 UTC, mes51 commented on src/components/TelemetryAcceptDialog.vue
> +          unelevated
確かに見にくいですね...
ただ、確かprimaryでないボタンのスタイルは他も同じだったはずなので、ここだけスタイルを変更しても良いかどうか確認したいです @Hiroshiba

2021-11-21 12:23 UTC, Hiroshiba commented
良さそうです！！

ただ、一番最初にダイアログが表示されてそこから進めない、というのはちょっとユーザーの創作欲を削ってしまうかもとちょっと思いました。
かといってどういう挙動が良いのかすぐに思いつきませんでした。

一旦頂いたプルリクエストは、収集機能をデフォルトでオフにしておき、
別issueで議論しつつ、デザインしていくのが良いのかなと感じましたが、その方針でも良いでしょうか・・・？

2021-11-21 12:25 UTC, Hiroshiba commented on src/components/TelemetryAcceptDialog.vue
> +          unelevated
目立たないけど気付けるので、別にいいかなと思いました！
ただ別でもコメントしたのですが、どういう聞き方をすればユーザーも開発者も幸せになれるのかを模索したいなと思いました。

2021-11-21 14:11 UTC, mes51 commented
> 一旦頂いたプルリクエストは、収集機能をデフォルトでオフにしておき、

了解です。ただ、今後同意画面、もしくはそれに類する何かを出すことになった際、まだ同意を取っていないことがわかるよう、設定ファイル上のデフォルト値はnullとしておこうかと思いますが大丈夫でしょうか? (descriptionに記載しているGoogle Tag Manager上の設定では、テレメトリーの収集は`acceptRetrieveTelemetry`が`true`の時以外は行わないようになっています

2021-11-23 08:43 UTC, Hiroshiba commented
> まだ同意を取っていないことがわかるよう、設定ファイル上のデフォルト値はnullとしておこうかと思います

なるほど、とてもいいと思います。
よりわかりやすく、未確認・同意・拒否のリテラル型を作ってそれを保存するようにすると、コードとしてはより綺麗になるかもと思いました。

2021-11-23 09:02 UTC, Hiroshiba requested changes
GTMの設定方法の詳細もありがとうございます！
ぜひ導入したいのですが、ちょっと時間がかかりそうなので、一旦完全に機能をOFFにした状態でマージする方針を取りたいのですが、どうでしょう。

2021-11-23 09:02 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +                    VOICEVOXの改善のため、ウインドウサイズや各UIの利用率などの収集を許可します
GTMの設定やプライバシーポリシーの把握をするのに時間がかかりそうで、いったんONにすることができなくした状態でマージできればと思います。
一旦ここ辺りの設定が出ないようコメントアウトして頂けると・・・！

2021-11-23 12:26 UTC, mes51 commented on src/components/SettingDialog.vue
> +                    VOICEVOXの改善のため、ウインドウサイズや各UIの利用率などの収集を許可します
こちらですが、何もしない状態でもgtm.jsは読まれてしまうので、もし設定やプライバシーポリシーの準備に時間が掛かるようであれば、それまでPending、もしくは一旦Closeして、準備ができ次第再度PR提出がいいかなと思うのですがどうでしょうか?

2021-11-29 16:44 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +                    VOICEVOXの改善のため、ウインドウサイズや各UIの利用率などの収集を許可します
バージョン0.9で時間がかかってしまっていました、すみません。
0.10で収集機能をつけられればと思います。なのでマージしちゃいたいです！

プライバシーポリシーって具体的に何をすれば良い等ご存知だったりしますか・・・？
（文章を読むのに結構時間がかかってしまいそうだったので、ご存知であればと思った次第です。）

2021-11-30 11:49 UTC, mes51 commented on src/components/SettingDialog.vue
> +                    VOICEVOXの改善のため、ウインドウサイズや各UIの利用率などの収集を許可します
> プライバシーポリシー

[Google Analytics利用規約](https://marketingplatform.google.com/about/analytics/terms/jp/)の7. プライバシーには、概ね
* Google Analyticsを利用していること
* Google Analyticsでどのような情報を集めるのか
    * Cookie
    * デバイスの識別情報(広告識別子等)
    * その他こちらで取得するようにした情報等
* Google Analyticsではどのように情報を集め、処理するのか
    * こちらは https://www.google.com/intl/ja/policies/privacy/partners/ へのリンクで良さそうです

といったことを記載する必要がある、というような事が記載されているようです。
こちらに関しては、法的な部分を含む所ではあるので、時間は掛かりますが一度規約全体を読まれてから最終的にどのような内容を記載するかを検討された方がいいかなと思います

2021-12-03 15:07 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +                    VOICEVOXの改善のため、ウインドウサイズや各UIの利用率などの収集を許可します
ありがとうございます！！
このあたりちゃんと把握するのはちょっと時間がかかりそうなので、discordの方でちょっと募集をかけてみました。
マージまではもうしばらくお待ち頂けると･･･！
https://discord.com/channels/879570910208733277/893889888208977960/916344818148454442

2021-12-03 18:03 UTC, Hiroshiba commented
プライバシーポリシーを眺めていたのですが、完全にオプトアウトする方法が思いつきませでした。
なので、一旦完全に無効にした状態（UIに何も表示されず、createGtmのenabledがfalseになっている状態）にしてマージし、今後どうするかを考えるというのはどうでしょう。

その上で、コメントアウトしている部分に、どうやったらコメントが外れるのかとか意図の追加コメントをお願いしたいです。
// FIXMEとかで書いておくと良いのかもです。
よろしくお願いします！

2021-12-03 18:03 UTC, Hiroshiba commented
以降はなぜ上述の決定としたかのメモです。

google analyticsはオプトアウトを提供していますが、おそらくelectronだとgoogle analyticsが用意してあるオプトアウトページの設定を適用できません（要検証）。
なのでVOICEVOX側で完璧なオプトアウト（一切データを送らない）を実装したいのですが、どうやらそれはVue.useのところのcreateGtmのenableをfalseにする以外に方法がなさそうです。

となると、Vueを初期化するときに設定ファイルを読む必要が出てくるのですが、現状その方法がよくわかりません。
（electronに詳しい方がいらっしゃったら、BrouserWindow初期化時にinitial valueをVueにわたす方法を教えて頂けると嬉しいです。）
この辺りが解決されたら、機能を有効にできる気がしています。

2021-12-04 17:24 UTC, Hiroshiba approved these changes
LGTM！！

リサイズのとき、debounceを送信側に付けないとプロセス間通信が何度も働いて重いかもと思いましたが、実際重さは感じなかったので大丈夫そうでした。

たぶんissueの内容は完全に実装されたわけではなさそうなので、close→refに変更しておきます！

2021-12-04 17:25 UTC, merged