「長さ欄を表示」ショートカットキーの初期化ができない不具合の修正とショートカットキーの重複追加防止
VOICEVOX/voicevox pull request #545
Opened 2021-12-02 21:42 UTC by yuqquu

## 内容
タイトルの通りで、以下の2点です。
- 「長さ欄を表示」ショートカットキーの初期化ができない不具合の修正 (#541)
- ショートカットキーの重複追加防止

## 関連 Issue
ref #541 

## スクリーンショット・動画など

## その他
ショートカットキーの重複追加防止について：

保存されたショートカットキーの中に追加しようとしているキーと同じ操作名(action)がある場合はその操作が重複して追加・保存されていましたが、この場合はキーの追加をしないようにしました。
0.8 → 0.6 → 0.8 などとバージョンダウン→アップをした場合に重複が起こるかもしれません。
バージョンダウンは通常あまりしませんし、migrationsの仕様に詳しくないので重複は起こり得ないかもしれませんが、念のため入れました。

2021-12-02 22:25 UTC, y-chan requested changes
プルリクエストありがとうございます、とてもきれいに仕上がっていると思います！

> ショートカットキーの重複追加防止について

おお！ありがとうございます。
確かに、ダウングレードは想定されていませんが、より動作が安全になると思います...!
しかも、よく考えてみると`defaultHotkeySettings`に「長さ欄を表示」ショートカットキーを含めたことで、今までの実装であればマイグレーション処理が走る度に追加されてしまう恐れがあったので、非常に良いと思います！！！

2点、変更してほしい点があります。
1点は、`newHotkey`(225-228行目)が同じものを2回定義していることになっている(95-98行目)ので、これをできれば辞めたいです。
計算量が多くなるので、望ましくはないかもしれないですが、findなどを用いて`defaultHotkeySettings`から取得するのがよいのかなと思いました(これに関しては別にいいかもしれません)。
もう1点は、今後ショートカットキーが増えることを見越して、同じ機構を流用できるように、今回いただいた変更のうち、230-239行目に当たる部分を関数化してほしいです。
少々型定義を振り回すことになるとは思いますが、`store`と`newHotkey`を渡せば同じ処理をしてくれる関数に切り出せるとよいのかなと思いました。

コードそのものは問題ないと思うので、難しそうであれば、再度レビューリクエストをしてもらえれば、Approve&マージしてしまって、こちらで解決したいと思います...!

2021-12-02 23:59 UTC, Hiroshiba commented
あ、あとformatでテストが落ちてるかもです。`npm run fmt`していただければ！

2021-12-03 08:42 UTC, yuqquu commented
レビューありがとうございます！

レビューいただいたとおり、`newHotkey`を2回定義している部分の除去と、操作を追加する処理の関数化をしました。
関数とその他型定義は一旦グローバルに置きましたが、適切な場所があればお教えいただきたいです……

なお、重複追加防止の処理を関数本体からは取り除きました。
不足しているものだけ`defaultHotkeySettings`から取り出して追加するようにしたためです。
計算量は多いですが、スマートにはなったと思います。

> formatでテストが落ちてるかもです
`npm run fmt`忘れていました、失礼しました。

2021-12-03 11:35 UTC, Hiroshiba approved these changes
LGTM！！

2021-12-03 12:42 UTC, y-chan commented
> 不足しているものだけ`defaultHotkeySettings`から取り出して追加するようにしたため、不要になりました。

なるほど！！！良い案だと思います!

LGTM...と言いたいところですが、個人的にではあるものの`0.7.3`のマイグレーション処理の箇所で、それ以上(例えば`0.10`)のバージョンで追加されるショートカットキーも対応出来るというのはなにか違和感を覚えました。
処理的には何も問題は起きないと思うのですが、もはやマイグレーション処理に含める必要も無いのかなと思いました。

私が個人的に気になっただけではあるんですが、 @Hiroshiba さんどうでしょうか...?
(本当に私が気になっただけなので、問題なさそうならApproveしちゃいます)

2021-12-03 12:58 UTC, Hiroshiba requested changes
…たしかに！
増えたアクションだけ追加できるようになっていた方が、どの処理が増えたのか後でもわかるので良さそうです！！

2021-12-03 13:54 UTC, yuqquu commented
作っていて確かに違和感のようなものはありました。

解決策として、以下の2案を思いつきました。

- `defaultHotkeySettings`の要素ひとつひとつに登場バージョンを振っていく
- `newHotkey`を2回定義するコードに戻す

前者は変更の規模が大きくなりそうですが、一度変更してしまえば将来的なミス(今回のような不具合)を減らせそうです。
後者の利点欠点はその逆です。

どうでしょうか？

2021-12-03 15:13 UTC, y-chan commented
なるほど、提案ありがとうございます！

> 要素ひとつひとつに登場バージョンを振っていく

こちらに関して、登場バージョンを振ることでさらなるマイグレーションが必要になりそうな気がしています。
今後のためを考えると、こちらで良さそうだなと思うのですが、一旦こちらで実装してみて、あまりにも複雑度が上がりそうであれば、「`newHotkey`を2回定義するコードに戻す」に戻してみるとよいかもと思いますが。

一旦お任せにしたいと思いますので、レビューできる状態になれば、再レビューリクエストいただければと思います...!

2021-12-03 17:07 UTC, yuqquu commented
結論から申しますと、登場バージョンを振ることもコードを戻すこともせず、このままにしたいと思いますがいかがでしょうか？

少し考えていましたが、ショートカットの一覧の順番を保証するためには最初に一括で処理したほうが良さそうだと思いました。
新しく追加されるショートカットの位置によっては期待していない位置に挿入される可能性があります。
例えば次のバージョンで「長さ欄を表示」よりも上の位置に操作が1つ加わった場合、0.7.3のマイグレーションが先に走ると所定の位置よりも1つ下に「長さ欄を表示」が挿入されます。

これを踏まえて登場バージョンを振ってバージョンを判別できるようにする方向で考えていましたが、今のところ良い感じのコードが思い浮かばないので難しくなりそうです。

2021-12-03 17:25 UTC, y-chan commented
> このままにしたい
> 最初に一括で処理したほうが良さそう

なるほど...難しいですね...

私が個人的に考えたのは、特定のバージョンにおけるマイグレーションの場所にそのコードがあるから違和感があるのであって、別にそうでないのなら(別の場所にあれば)構わないと思いました。

`background.ts`のだいたい300行目あたりから、グローバルに"キャラクター情報の読み込み"～"アップデート情報の読み込み"のコードがあります。
その下に、"hotkeySettingsのマイグレーション"といったセクションを用意し、そこに今回いただいたコードを移動させてみるというのはどうでしょうか？

そうであれば、大きな改変が必要なく、かつ違和感も取り払えるのかなと思いました。

2021-12-04 06:51 UTC, yuqquu commented
提案ありがとうございます。

提案いただいた内容を元に関数を整理しました。
また、一括でできるのであればいろいろ改良してしまえ、と関数の中身も変えました。
ショートカットの順番が保証され、バージョンダウンやショートカット操作の廃止にも対応できるようになっています。

2021-12-04 13:47 UTC, yuqquu commented
すみません、typoで落ちていたので修正しました。

2021-12-04 16:43 UTC, y-chan commented on src/background.ts
> +
良さそうです！
ただ、マイグレーションの部分から完全に切り離せるとうれしいので、以下の形にするとよいかもです(同時に、マイグレーションの箇所から消す必要があります)

```suggestion
// hotkeySettingsのマイグレーション
function migrateHotkeySettings() {
  const COMBINATION_IS_NONE = "####";
  const emptyHotkeys = defaultHotkeySettings.map((defaultHotkey) => {
    const hotkey: HotkeySetting = {
      action: defaultHotkey.action,
      combination: COMBINATION_IS_NONE,
    };
    return hotkey;
  });
  const loadedHotkeys = store.get("hotkeySettings");
  const copiedHotkeys = emptyHotkeys.map((emptyHotkey) => {
    return (
      loadedHotkeys.find(
        (loadedHotkey) => loadedHotkey.action === emptyHotkey.action
      ) || emptyHotkey
    );
  });
  const migratedHotkeys = copiedHotkeys.map((hotkey) => {
    if (hotkey.combination === COMBINATION_IS_NONE) {
      const newHotkey =
        defaultHotkeySettings.find(
          (defaultHotkey) => defaultHotkey.action === hotkey.action
        ) || hotkey; // ここの find が undefined を返すケースはないが、ts のエラーになるので入れた
      const combinationExists = copiedHotkeys.some(
        (hotkey) => hotkey.combination === newHotkey.combination
      );
      if (combinationExists) {
        return hotkey;
      } else {
        return newHotkey;
      }
    } else {
      return hotkey;
    }
  });
  store.set("hotkeySettings", migratedHotkeys);
}
migrateHotkeySettings();
```

2021-12-04 16:49 UTC, y-chan commented
一か所気になったのでコメントしてみました、これ以外は大丈夫そうなので、指摘箇所の修正が入ればマージできると思います...!
よろしくお願いします！

2021-12-04 17:01 UTC, yuqquu commented
レビューありがとうございます！
関数実行をグローバルに移しました。
また、マイグレーションの箇所からは削除しました。

2021-12-04 17:08 UTC, y-chan approved these changes
LGTMです...!

2021-12-04 22:39 UTC, Hiroshiba commented on src/background.ts
> +migrateHotkeySettings();
.map()を3回使って処理ごとに ~Hotkeys変数が作られていますが、.map()を1回だけ使って中でhotkeyを生成するとよりわかりやすいコードになりそうだなと感じました。
（emptyHotkeysやcopiedHotkeysやmigratedHotkeysはそれぞれ直後に１度だけ使えば済みそうなので）

2021-12-04 22:40 UTC, Hiroshiba commented
`acceptRetrieveTelemetry: AcceptRetrieveTelemetryStatus;`が増えた関係でコンフリクトが発生してるっぽいです。
コンフリクト解消をよろしくお願いします！

2021-12-05 14:48 UTC, yuqquu commented on src/background.ts
> +migrateHotkeySettings();
レビューありがとうございます。
結論から申しますと、`map`は2回までに短縮できましたが、そもそもの考え方が良くなさそうなのでもう少し考えてみます。

## `map`について
`map`は2回使うことになりました。
ショートカット操作が廃止された際に不具合を防止するため、2回は必要でした。
例えばあるバージョンでショートカットキーが廃止・追加の両方がされる場合、両方の`combination`が同じだと、追加された`combination`は空になる不具合が出ます。

## 考え方が良くないことについて
…と長く書きましたが、この不具合防止のコードはまずいと思い始めました。
バージョンアップでショートカットキーが追加されるなら、それを跨ぐバージョンダウンは「ショートカット操作の廃止」と同等の処理がなされます。
私は0.9.3と0.8.2をキャラクターに合わせて使い分けていますが、せっかく登録したショートカットキーが消えたり復活したりするのは問題だなと思いました。
（バージョンごとにエンジンが簡単に切り替えられるのであればこれは杞憂ですが…）

## 今後
廃止されたキーはconfigに置いたままにして読み出さず、またコードを簡易なものにする方向も含めてもう少し考えてみます。

2021-12-05 14:51 UTC, yuqquu commented
コンフリクト解消しました。
バージョンダウン⇔アップをするとユーザーに不便を感じさせそうな実装になっていたので、もう少し考えてみようと思います。

2021-12-05 16:01 UTC, yuqquu commented
考えていましたが、バージョンダウン⇔アップで不便にならないような実装は取りやめようと思います。
以下の4点がその理由です。

- 廃止されたキーをconfigに置いたままにして読み出さない処理を実装するには大規模な変更が必要
- config.jsonは重要なファイルではない (これを消去する手順が公式サイトの使い方に載っている)
- バージョンダウン or ショートカットの廃止はまれ？
- ショートカットキーを変えるのもまれ？

よって、今の実装をベストとしておきたいと思います。いかがでしょうか？

2021-12-05 16:22 UTC, y-chan commented on src/background.ts
> +        return hotkey;
`combination`が`COMBINATION_IS_NONE`のままだと、そのまま設定画面に表示されてしまうことになるので、`""`に置き換えてから返さなければならないことに気づきました。

2021-12-05 16:30 UTC, y-chan commented
> バージョンダウン⇔アップ

よくよく考えてみると、バージョンダウンで起きることは、設定画面で存在しないショートカットキーの内容を書き換えられる以外ないはずなので、もう気にしなくていい気がします。

> ショートカットの廃止はまれ？

稀だと思います。現状はショートカットキーの表示名が変わるだけで廃止と新規追加が起きる形になっていますが、 #547 を解消するPRで対処できそうなので、気にする必要もないかなと思います。

よって、私は現状の形でよいと思います。

2021-12-06 05:02 UTC, yuqquu commented on src/background.ts
> +        return hotkey;
レビューありがとうございます。
失礼しました、たしかにそうですね。修正しました。

2021-12-06 06:37 UTC, yuqquu commented
いただいたレビューを元に修正しました。
よろしくお願いします。

2021-12-06 09:17 UTC, y-chan approved these changes
LGTMです！

いろいろお願いが多かったですが、対応していただけて感謝します...!
初PRありがとうございました！

2021-12-06 14:00 UTC, Hiroshiba approved these changes
LGTM！！
良い議論と実装だったと感じました。
またのプルリクエストをお待ちしています…！！

2021-12-06 14:00 UTC, merged