音声をすべて繋げて書き出す機能を追加
VOICEVOX/voicevox pull request #549
Opened 2021-12-04 01:45 UTC by y-chan

## 内容

題の通り
ただし、ショートカットキーの追加は、以下Issue・PRとの整合性を保つために待った方が良さそうです(追加しちゃってるので消す必要がある?)
- #545 
- #547 
また、ツールバーのカスタマイズ(#489)とも少しconflictを起こしそうです。

## 関連 Issue

close #107 

## その他

書き出すときのデフォルトの名前は要検討かもです。

2021-12-04 18:57 UTC, MT224244 requested changes
確認用と思われるconsole.logが残っていたので、それを消せば後は問題ないと思いました！

2021-12-04 18:57 UTC, MT224244 commented on src/store/audio.ts
> +          console.log(encodedBlob);
このconsole.logは消し忘れですかね…？

2021-12-04 18:57 UTC, MT224244 commented on src/store/audio.ts
> +            console.log(splitCurrentLab);
消し忘れ…？

2021-12-05 00:41 UTC, y-chan commented on src/store/audio.ts
> +          console.log(encodedBlob);
消し忘れですね...w
指摘ありがとうございます...!

2021-12-05 00:41 UTC, y-chan commented on src/store/audio.ts
> +            console.log(splitCurrentLab);
こちらも同様です、ありがとうございます...!

2021-12-05 05:39 UTC, MT224244 approved these changes
LGTM!

2021-12-05 10:48 UTC, Segu-g commented on src/store/audio.ts
> +    ) {
vuexのstoreをquasarに依存させて良いのかが少し気になります．
action内ではもはやelectronの依存は外しようがないくらいにはelectronのdialog等のUIが混入してしまっていますが，ここにquasarの依存を入れて大丈夫なのかがわかりません．

actionは割と無法地帯なので通していい気もしますが，差し替えやすいように`QVueGlobals`ではなくdialog関数を渡すべきだと思います．

2021-12-05 11:05 UTC, y-chan commented on src/store/audio.ts
> +    ) {
なるほど、確かにdialog関数だけ渡すのはありだと思いました。
ちょっと試して見ます。

2021-12-05 11:43 UTC, Hiroshiba commented
> 書き出すときのデフォルトの名前は要検討かもです

判断します！こちらって何になっていますか👀

2021-12-05 11:46 UTC, Hiroshiba commented on src/store/audio.ts
> +    ) {
vuexとdialog周りはどうするか考えた方が良さそうですね…
とりあえず他の書き出しactionと合わせて、Vue側でresultを受け取ってVie側でダイアログ出すようにしておけば、あとあと改変が楽なのかなと感じました。

2021-12-05 11:55 UTC, y-chan commented on src/store/audio.ts
> +            : headItemText;
現状の書き出し名はaudioItemsの最初と最後の名前を"..."で繋げた形になっています。

`buildFileName`関数を使った方がいいのかなと思ったのですが、特に考えずにこのような名前にしました。

2021-12-05 13:54 UTC, y-chan commented on src/store/audio.ts
> +    ) {
これは`WITH_DIALOG`関数なので、ツールバーのカスタマイズを想定してあらかじめ切り出した関数です。
他の書き出し関数と同じようなVue側でresultを受け取る関数は別に存在します...!

2021-12-05 16:48 UTC, Hiroshiba commented on src/store/audio.ts
> +            : headItemText;
なるほどです！
どうすれば良いのか想像つかないので、とりあえずそちらで良いのかなと思いました！

2021-12-05 16:49 UTC, Hiroshiba commented
書き出しをfixする機能はありそうですが、上書き防止機能がなさそうでした。
https://github.com/VOICEVOX/voicevox/blob/c83af58e4a39b9c1427a76ebae063d87f4ec842b/src/store/audio.ts#L671-L678
（全部接続した状態で、上書き防止したいことある？と思わなくもないのですが、一応･･･）

2021-12-14 05:41 UTC, y-chan commented
`dialog.ts`ができたので、そちらに`WITH_DIALOG`関数を移動し、仰られていた上書き防止機能の実装を行いました。
レビューお願いします...!

2021-12-14 08:09 UTC, Hiroshiba commented on src/store/audio.ts
> +  QuasarDialog,
未使用warningが出ていそうです

2021-12-14 08:22 UTC, Hiroshiba requested changes

2021-12-14 08:22 UTC, Hiroshiba commented on src/store/audio.ts
> +          // pauが重なっているのを取り除く
あれ、なんで取り除くんでしたっけ。音声とlabで同期ずれるかも･･･？

2021-12-14 08:26 UTC, y-chan commented on src/store/audio.ts
> +          // pauが重なっているのを取り除く
音素的にpauが2つ(post phoneme lengthとpre phoneme lenght)並ぶので、それを1つに統合します。
時間は開始時刻と終了時刻を統合するので、同期性は失われないはずです。
pauが2つ並ぶのを許容できる場合、何も問題はないと思うのでそもそもこの処理ごと消して良い気もします。

2021-12-14 09:19 UTC, Hiroshiba commented on src/store/audio.ts
> +          // pauが重なっているのを取り除く
おお、なるほどです！
それなりに複雑な処理な割に需要がないかもなので、省いちゃってもいいかなと感じました！

2021-12-14 12:56 UTC, y-chan commented on src/store/audio.ts
> +          // pauが重なっているのを取り除く
了解です、省くことにします！

2021-12-15 03:28 UTC, MT224244 approved these changes
LGTM！

2021-12-15 15:56 UTC, Hiroshiba approved these changes
LGTM！！

2021-12-15 15:56 UTC, merged