macOS用アプリケーション (.app) とdmgファイル (.dmg) の自動ビルド
VOICEVOX/voicevox pull request #570
Opened 2021-12-11 10:44 UTC by PickledChair

## 内容

macOS用アプリケーションと、それをインストールするためのdmgファイルの自動ビルドを追加します。

## 関連 Issue

close #399 
ref #348 

## スクリーンショット・動画など

### VOICEVOX.0.9.3.dmg をマウントした際に表示されるアイコン

<img width="122" alt="mount_voicevox_dmg" src="https://user-images.githubusercontent.com/41382894/145673296-5616d5f6-97cf-4f55-859f-b31905a6a4d4.png">

### VOICEVOX.0.9.3.dmg を開いたときのインストール画面

矢印に従ってアプリアイコンをアプリケーションフォルダにドラッグするとインストールされます。

<img width="652" alt="open_voicevox_dmg" src="https://user-images.githubusercontent.com/41382894/145673341-38ec840b-ffef-4074-af1c-ac35c473d2c6.png">

## その他

- macOS向けのテストリリースは[こちら](https://github.com/PickledChair/voicevox/releases/tag/0.9.3-pickledchair-4)の `VOICEVOX.0.9.3.dmg` からダウンロードできます。
- インストール後、初回の起動時はセキュリティ警告が出て起動できません。「システム環境設定 → セキュリティとプライバシー → 一般タブ」でダウンロードしたアプリケーションの実行許可を与えるか、VOICEVOX.app を直接二本指クリック（右クリック）して出るコンテキストメニューから開く操作を２回試みると開きます。
- pkgファイルの構築も検討しましたが、dmgによる配布の方が一般的だと感じたのでこちらを選択しました。検討の余地がある場合はご提案ください。

2021-12-11 11:04 UTC, Hiroshiba commented
こちらのmacでも試してみた感じ、動きました！！

初回起動時に `ENOENT: no such file or directory open psn_0_数値` みたいなエラーダイアログが出ました。
調べても何のファイルなのか謎でした･･･。

2021-12-11 11:07 UTC, Hiroshiba commented
たぶん、.appをzipにしただけのzip版もニーズがあると思います。
もしよかったらそちらの作成もお願いできるとすごく嬉しいです･･･！

2021-12-11 11:27 UTC, PickledChair commented
> 初回起動時に `ENOENT: no such file or directory open psn_0_数値` みたいなエラーダイアログが出ました。
> 調べても何のファイルなのか謎でした･･･。

２回目以降の起動時には出ませんでしたでしょうか？（しかし、初回起動時だけの現象だったとしても、ちょっと気持ちのいいものではありませんね……。）自分の環境では遭遇していないエラーなので、発生条件がわからないです。一度 [AppCleaner](https://freemacsoft.net/appcleaner/) 等のツールで関連ファイルごと完全にアンインストールしてから、もう一度インストールし、**クリックで初回起動せず**に

```
$ cd /Applications/VOICEVOX.app/Contents/MacOS
$ ./VOICEVOX
```

の起動方法をとると、詳しいエラーが読めると思うので、もしよかったらご報告いただければと思います（自分がいつも取っているデバッグ方法です）。

> たぶん、.appをzipにしただけのzip版もニーズがあると思います。
> もしよかったらそちらの作成もお願いできるとすごく嬉しいです･･･！

作業してみます。Linux向けのtar.gzを作っている付近でmacOS向けにzipへ固めれば、期待しているものが得られそう？ と思いました。

2021-12-11 11:28 UTC, Hiroshiba requested changes
すごく良いなと感じました！！

やりなおしが時間かかって少々面倒かと思うのですが、もしよかったら処理の共通化をお願いしたいです。

2021-12-11 11:28 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          # sed -i '' 's/productName: "VOICEVOX"/productName: "${{ matrix.product_name }}"/' vue.config.js
欲を言えばなるべく共通化したいなと思いました。
（将来、片方に修正を入れてもう片方に忘れる、ということを防止したいためです。）

たぶんmacのsedとlinux/windowsのsedが違うことに起因していると思うのですが、gnu-sedをインストールしてsedを置き換えてしまってもいいかなと感じました。
https://zenn.dev/captain_blue/articles/use-gnu-sed-on-mac

2021-12-11 11:28 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          cat vue.config.js
どういうリプレイスをしているかのコメントがあるとわかりやすいかもと思いました

2021-12-11 11:28 UTC, Hiroshiba commented on .github/workflows/build.yml
> +          rm -rf prepackage/VOICEVOX.app/Contents/Resources/app
こちらも可能であれば共通化しておきたいと感じました。

`prepackage/resources/app`が`prepackage/VOICEVOX.app/Contents/Resources/app`になる感じでしょうか。
matrixに書いておいてrun内で使うなどの方法を思いつきました。

ENGINEのlibtorch_urlなどが近い印象を受けました。
https://github.com/VOICEVOX/voicevox_engine/blob/5fe249eb3bb7b5a03009c5ce418a623b35bdfd3a/.github/workflows/build.yml#L27

2021-12-11 11:30 UTC, PickledChair commented on .github/workflows/build.yml
> +          # sed -i '' 's/productName: "VOICEVOX"/productName: "${{ matrix.product_name }}"/' vue.config.js
確かにその方が良さそうです。gnu-sed を導入してみたいと思います。

2021-12-11 11:31 UTC, PickledChair commented on .github/workflows/build.yml
> +          cat vue.config.js
確かに説明不足ですね。コメントを足します。

2021-12-11 11:33 UTC, PickledChair commented on .github/workflows/build.yml
> +          rm -rf prepackage/VOICEVOX.app/Contents/Resources/app
わかりました！

2021-12-11 11:55 UTC, Hiroshiba commented
> ２回目以降の起動時には出ませんでしたでしょうか？

一度だけでした。正確には、
`dmgインストール→.appダブルクリック→許可がないので開けません→system preferenceから「開く」→起動時にエラー`
という流れでした。

教えていただいた方法でコンソールから初回起動したいのですが、system preferenceから許可しないと開けず、かつ許可するとGUIで起動してしまって試せませんでした･･･。

2021-12-11 12:02 UTC, PickledChair commented
> 教えていただいた方法でコンソールから初回起動したいのですが、system preferenceから許可しないと開けず、かつ許可するとGUIで起動してしまって試せませんでした･･･。

すみません、言われて気づいたのですが、そうなってしまいますよね……。お手間を取らせてすみませんでした。

２回目以降は正常に起動するとのことなので、本当にファイルが不足している or 間違ったファイル指定をしている、といった問題はないものと思われます。OSがアプリの起動を中途半端なところで止めていて起こっているエラーなのかもしれませんが、憶測の域を出ないです……。

今回の PR では対策ができなさそうですが、何度も再現する場合は Issue 化が必要そうですね。

2021-12-11 16:28 UTC, HyodaKazuaki commented
> > ２回目以降の起動時には出ませんでしたでしょうか？
> 
> 一度だけでした。正確には、 `dmgインストール→.appダブルクリック→許可がないので開けません→system preferenceから「開く」→起動時にエラー` という流れでした。
> 
> 教えていただいた方法でコンソールから初回起動したいのですが、system preferenceから許可しないと開けず、かつ許可するとGUIで起動してしまって試せませんでした･･･。

ターミナル上でVOICEVOXを例外許可して実行する方法ですが、システム全体のセキュリティ設定を一時的に緩和するのが手っ取り早いかと思います。
ターミナル上で以下のコマンドを実行した上で、VOICEVOX.appパッケージ内のVOICEVOXを直接ターミナルで呼び出してあげれば動作確認できるかと思います。
```sh
sudo spctl --master-disable
# 以下戻す場合
sudo spctl --master-enable
```

2021-12-11 16:37 UTC, PickledChair commented
zip版について検討した結果、当初考えていたよりちょっと実現が難しそうです。Linux版ビルドでtar.gzを作っているところに次のようなコメントがあります。

https://github.com/VOICEVOX/voicevox/blob/c257aea50e3388c023276e5220de894ed371472b/.github/workflows/build.yml#L370-L382

これについてはmacOSでも同じ問題があります。chmod で設定した File permission をダウンロード後にも維持するにはtar.gzに固める以外に手段がなさそうです。これについては以下の Upload Artifact v2 のドキュメントにも記載されています。また、zipをアップロードすると２重のzipになってしまうことなども書いてあります。

https://github.com/actions/upload-artifact/blob/11e311c8b504ea40cbed20583a64d75b4735cff3/README.md#limitations

実際、 https://github.com/PickledChair/voicevox/actions/runs/1566674713 のアーティファクト `macos-cpu-prepackage` をダウンロードすると（zipに固めていないにも関わらず）zipファイルが得られ、解凍するとappバンドルが得られますが、appバンドル内の実行ファイルの実行権限は全て消えています。

選択肢は２つで、Linuxと同様tar.gzで配布するか、配布しないかのどちらかになると思います。zipは自分が調査した限りでは難しそうです。

（zip版配布に関して有益な情報を知っている方や、「ここ間違ってますよ」という方がいらっしゃれば、情報の提供やご指摘等よろしくお願いいたします。）

2021-12-11 16:42 UTC, PickledChair commented
> ターミナル上でVOICEVOXを例外許可して実行する方法ですが、システム全体のセキュリティ設定を一時的に緩和するのが手っ取り早いかと思います。

@HyodaKazuaki ありがとうございます。https://github.com/VOICEVOX/voicevox/pull/570#issuecomment-991601013 と https://github.com/VOICEVOX/voicevox/pull/570#issuecomment-991616036 のデバッグに使えそうな手ですね。今後このエラーが出た方でデバッグに協力してくれる人に、この操作の後でエラーを確認してもらう、ということができそうです。

2021-12-11 20:00 UTC, Hiroshiba commented
@.HyodaKazuaki さんの方法で試せました！
が、エラーが出ませんでした。
たぶんなのですが、system preferenceから許可してopenすると何かが引数として送られてくることがあって、それを↓でproject file loadしようとしてエラーが出ているのかなと思いました。

https://github.com/VOICEVOX/voicevox/blob/c257aea50e3388c023276e5220de894ed371472b/src/background.ts#L496-L501

2021-12-11 23:39 UTC, Hiroshiba commented
> 選択肢は２つで、Linuxと同様tar.gzで配布するか、配布しないかのどちらかになると思います。zipは自分が調査した限りでは難しそうです。

完全に失念していました。
今webページで配布しているLinux Zip版は動作しないのですね･･･。

Linux Zip版がまともに動かないのに報告がないということは、あまりユーザーがいないということなので、用意しなくても良いかもですね･･･
もし簡単に作れそうであればtar.gz版も作成して頂けると嬉しいですが、一旦dmgだけでも良いと思います！

2021-12-12 01:27 UTC, PickledChair commented
> Linux Zip版がまともに動かないのに報告がないということは、あまりユーザーがいないということなので、用意しなくても良いかもですね･･･

Linux Zip版を試してみました。プロパティを開いて「プログラムとして実行可能」にチェックを入れると起動できるようになります（AppImageの一般的な起動手順の一部としてよく案内されているみたいです）。LinuxからはAppImageがディレクトリではなく単一のファイルとして見えているようなので、実行権限の付与が１回で良いのかもしれません。

![voicevox_appimage_permission](https://user-images.githubusercontent.com/41382894/145696511-9b748a4b-9d65-4aef-87e9-adb2a71204a9.png)

zip版について、もう少し作業してみて駄目そうであればtar.gzを作るようにしてみます。

2021-12-12 02:45 UTC, PickledChair commented
zipにしてアーティファクトとしてアップロードしたところ、File permissionが失われていないことがわかりました。[こちら](https://github.com/PickledChair/voicevox/actions/runs/1568451752)の `macos-cpu-prepackage-zip` からダウンロードできます。２重のzipになっていますが、それ以外は問題なさそうです。起動も試しましたがうまく行きました。

こちらのzipはどうすれば良いですか？ Releases からダウンロードできるようにすると良いですか？

2021-12-12 03:59 UTC, aoirint commented
@Hiroshiba 

> Linux Zip版

実は公式サイトのzip版としてAppImageが配布されていることに気づいていましたが、忘れていました。
Linuxユーザとしては、zip版（tar.gz版）として配布されている場合、AppImageではなくて、Windows zip版と同じようにprepackage-targzを配布する方が自然かなと思いました（artifactはzip圧縮されるので、tar.gz in zipで配布するか、中のtar.gzを取り出す手間が増えますが）。

- Discord tar.gz版: <https://discord.com/api/download?platform=linux&format=tar.gz>

<details>

![discord_targz](https://user-images.githubusercontent.com/27213639/145699706-8b0ca01d-519d-4650-b9d1-3ba3fecc5307.png)

![voicevox_targz](https://user-images.githubusercontent.com/27213639/145699432-405e1070-da30-416b-850c-5e3980240f49.png)

</details>

2021-12-12 04:53 UTC, aoirint commented
> Releases からダウンロードできるようにすると良いですか？

いまの方針だとzip版は、ヒホさんのGoogle Driveで配布していますが、GitHub Releasesの1ファイル2GB容量制限を回避するためにそうしているだけだったと思うので、個人的には（Windows、Linuxも）CPU版はGitHub Releasesにアップロードするようにしてもいいかなと思いました。

ONNX化が完了したらファイルサイズの問題が解消されるので、すべてGitHub Releasesにアップロードするようになると思います。

2021-12-12 04:57 UTC, PickledChair commented
@aoirint 

> いまの方針だとzip版は、ヒホさんのGoogle Driveで配布していますが、GitHub Releasesの1ファイル2GB容量制限を回避するためにそうしているだけだったと思うので、個人的には（Windows、Linuxも）CPU版はGitHub Releasesにアップロードするようにしてもいいかなと思いました。

なるほどです！ とりあえずmac版に関して、zipをReleasesのassetsに含める作業を進めてみます。

2021-12-12 05:24 UTC, aoirint approved these changes
いったんReviewしておきます。コードは良さそうでした！ LGTM！

2021-12-12 05:43 UTC, PickledChair commented on .github/workflows/build.yml
> +    #   - main
情報ありがとうございます。便利ですね！ 別PRを出そうかなと思いました。

2021-12-12 06:19 UTC, PickledChair commented
Releasesにzipがアップロードされるのを確認しました。 https://github.com/PickledChair/voicevox/releases/tag/0.9.3-pickledchair-6 の `voicevox-cpu-macos-x64.zip` からダウンロードできます。自分の環境では動作することを確認できました。

2021-12-12 07:47 UTC, Hiroshiba commented
見るの遅れました。（ @aoirint さんありがとうございます！）

GPU版は容量が大きくてreleasesに乗らないのですが、macはCPU版のみなので、プルリクで頂いているようにreleasesに乗っけて頂くので良さそうに感じました！

2021-12-12 07:49 UTC, Hiroshiba approved these changes
LGTM！！！　配布が楽しみですね！！

とりあえず次のバージョンから正式対応にしたいと思っています。
（余力があれば0.9.4？として現行のmac版も配布したいです。）

2021-12-12 07:49 UTC, merged