再生位置指定機能と、再生位置フォーカス・スクロール機能の追加
VOICEVOX/voicevox pull request #578
Opened 2021-12-12 16:15 UTC by y-chan

## 内容

題の通り

## 関連 Issue

close #491 

## スクリーンショット・動画など

https://user-images.githubusercontent.com/34832037/145720111-817b9bad-d0a7-4b85-b439-2b16706c3356.mp4

## その他

watchを使っている関係上、開発時点でのホットリロードが入るとバグります。
現状の私には解決策がわからなかったです...

2021-12-12 16:21 UTC, y-chan reviewed
議論の余地がある点をコメントしてみました。

2021-12-12 16:21 UTC, y-chan commented on src/components/AudioDetail.vue
> +          :class="[accentPhraseIndex === playPoint && 'bg-red-2']"
現状、仮として薄い赤色のバックグラウンドでフォーカスするようになっていますが、これはテーマに対応していない形になるので、フォーカスする色を決めてそれをテーマのjsonに移したいです。

2021-12-12 16:21 UTC, y-chan commented on src/store/audio.ts
> +    },
`AUDIO_ELEM_CURRENT_TIME`というgetterを作りましたが、これは適切ではないかもしれません。
ただ、これ以上に良い案が思い浮かびませんでした...

2021-12-13 16:44 UTC, Hiroshiba commented
UI触ってみました！すごく良いですね！！
更にユーザビリティを増せるような案がいくつか思いついたのでコメントしてみます！

1. アクセント句を選択していない状態から再生・停止すると、一番最初のアクセント句が選択状態になりますが、再生する前の状態に戻る（無選択状態に戻る）と混乱を減らせるかなと思いました。

2. 無をクリックすると選択状態になりますが、可能なら無じゃなくできるととても良さそうです。アクセント句をマウスオーバーするとアクセント句がマウスオーバーされていることがわかるようにし、かつクリック可能なところはマウスカーソルを変えてあげると良いのかなと感じました。

3. スクロールの追従ですが、DTMソフトとかはよくページめくりになっているので合わせられると良いかもと感じました。そちらのほうが疲れにくいかもです。（どう感じるか、ちょっと自信ががないです･･･）

あと実装なのですが、おそらくこの「アクセント句の選択」状態は今後もずっと使っていくことになると思うので、ユビキタス言語を何にするかも考えたいかもです。
実装では`Point`でしょうか。他にもActiveAccentPhraseやSelectedAccentPhrase、あるいはPointを採用して`ActivePoint`とか`SelectedPoint`とかでも良いのかなと感じました！

2021-12-16 06:03 UTC, y-chan commented
> 無選択状態に戻る

そうですね、この挙動は不自然なので、修正します。

> 無をクリックすると選択状態になり

こちらも対応します。

> ページめくり

実験的ですが、少し実装してみました。

https://user-images.githubusercontent.com/34832037/146316804-69b287a1-68b5-4167-a47f-e7ab239d632c.mp4

こちら、アクセント句が一部でも映っていれば、スクロールをしないようにしてみたのですが、どうでしょうか...
全部映るようにスクロールすべきですかね...?

2021-12-16 16:40 UTC, Hiroshiba commented
ページめくり良いですね！！

アニメーションを見たときの疲れを最小化するのが最も良いと思っていて、どうすれば良いのかを考えてました。
たぶん疲れは、時間辺りの見た目の変化量が大きいほど・予測できない動きをするほど増えると思っています。
なので横方向の縮尺をより広くできたり、ページ送りする際に再生中のAccentPhraseが必ず一番左に来たりすると、更に良いのかなと感じました。
（後者は最後の方のAccentPhraseを再生するときに、予測できない動きになったのが気になりました）

あと見た目が全く変わらないという選択もできるように、スクロールのON/OFF機能はぜひほしいなと感じました。

とはいえ、一旦実装してから考えるのがOSS的に良いのかなと思います！
ぱっと実装できそうなところは実装をお願いできると嬉しいです。
難しそうなところはマージ後にissue化しちゃうというのはどうでしょう。

個人的にこのプルリクエストでは、こんな感じの実装になっていればよいのかなと感じています。

- 自動スクロールができる
- ON/OFFが切り替えられる
- 連続再生・ページ送りが切り替えられる（もしくはoff/連続/ページで３択）

あと、追加でこうしたほうが良さそうと思ったのですが、連続再生時はAccentPhraseの左側の位置を固定ではなく、中心の位置を固定できると嬉しいかもです。
それと、AccentPharseの区切りは背景色が無い方がわかりやすいかなと感じました。

プルリクエストの範囲をどこまでにするかはお任せします･･･！
（個人的にはできるかぎり小さめだと嬉しいです。）

> ActivePoint

良いと思います！

2021-12-17 03:27 UTC, y-chan commented
> 横方向の縮尺をより広くできたり、ページ送りする際に再生中のAccentPhraseが必ず一番左に来たりする

縮尺の変更は破壊的変更になりそうで、例えば縮尺を開くすると操作UIが小さくなりUXが下がることが見込まれ、私には実装も難しそうなので、要議論な気がしました。
必要であればIssueへの切り分けをすべきだと思います。

AccentPhraseが必ず左に来るようにするのは、仰る通りUIの崩壊が起きる気がしていて、私にもパッときれいに実装する方法が思い浮かばないので、妥協案として現状のままで行きたいというのが私の今の考えです。
また、再生したいアクセント句を中央辺りで選択した場合に、それがいきなり左に動くのは疲れを伴う挙動な気がした(フォーカス部分が行ったり来たりすることになると思うので)のですが、どうですかね...

> 連続再生・ページ送りが切り替えられる（もしくはoff/連続/ページで３択）

個人的には、最後にこの状態になればいいかなと思っています(ユーザーにとっては選択肢が多い方がいろいろな使い方ができると思うので)
切り替えまでこのPRで実装するのは変更量が肥大化するので、一旦避け、ページめくりのみ有効化したいと思います。

> 連続再生時はAccentPhraseの左側の位置を固定ではなく、中心の位置を固定できる

こちら、以下のように実装しました(現在はコメントアウトしており、ページめくりが有効化されています)。

https://user-images.githubusercontent.com/34832037/146476902-1e9eb1ce-da0e-4cec-a00c-85e922be1dcf.mp4

完全なセンタリング(端のアクセント句は除く)になったので、結構動きが少し少なくなって見やすくなった気がします。
なので、これに切り替え出来るようにすれば、うれしい人もいるのではないか(私は逐次追従のほうがうれしい人です)と思います。
ただ、先ほども言った通り、切り替えは別PRにて実装するつもりです。

> AccentPharseの区切りは背景色が無い方がわかりやすい

確かにそう思ったのですが、では読点(`、`)はどうしようか、と少し思いました(現状は読点の時間もフォーカスをしています)。
どうすべきなんでしょう...

> `ActivePoint`

現状、`playPoint`/`PlayPoint`となっている点を、`activePoint`/`ActivePoint`に変更しました。

2021-12-17 17:15 UTC, Hiroshiba commented
> 縮尺

要望いただいたこともあるし、必要そうな気がしているのでissue化したいかなと思いました･･･！

> また、再生したいアクセント句を中央辺りで選択した場合に、それがいきなり左に動くのは疲れを伴う挙動な気がした(フォーカス部分が行ったり来たりすることになると思うので)のですが、どうですかね...

たしかにフォーカスしている箇所が即左に表示されるのは良くないと思います。ページ送りする際に一番左に来るイメージでした。

> では読点(、)はどうしようか

たしかに･･･
まあ、読点も含めなくてもそこまで問題ないのでは、とちょっと思いました。

2021-12-21 02:15 UTC, y-chan commented
> issue化したい

なるほど、では別問題として扱うということで、ここでは考えないこととします。

> ページ送りする際に一番左に来るイメージでした。

すみません、最初からそう書いてあったのに文意が読み取れてなかったですね...

> 読点も含めなくてもそこまで問題ない

これに関しては、読点の左右どちらでもアクセント句の結合操作ができることがまず問題な気がしています。
現状の仕様から変更するということはしないでおこうと思いますが、別Issueとして切り出したい問題のように思っています。
ただ、現状の作り的に読点の間もフォーカスが続くのと、読点の時間も制御可能であることから、読点部分の右側の区切り(本当のアクセント句の区切り)部分だけをフォーカスしないように作ろうかと思います。

2021-12-21 02:56 UTC, Hiroshiba commented
> ただ、現状の作り的に読点の間もフォーカスが続くのと、読点の時間も制御可能であることから、読点部分の右側の区切り(本当のアクセント句の区切り)部分だけをフォーカスしないように作ろうかと思いますが、どうでしょうか？

なるほどです、確かに読点の右の隙間（アクセント区の右端）が含まれなければOKな気がしました！そちらでお願いします！

2021-12-27 05:48 UTC, Hiroshiba commented
@Segu-g @MT224244 レビューお願いできると助かります･･･！

2021-12-29 14:23 UTC, MT224244 requested changes
レビューが遅れて申し訳ありません…。
気になった点をコメントしました。

2021-12-29 14:23 UTC, MT224244 commented on src/components/AudioDetail.vue
> +      );
`document.getElementById` より `ref` を使った方がいいかもしれません。

2022-01-02 12:04 UTC, y-chan commented on src/components/AudioDetail.vue
> +      );
`ref`を使って、`$refs`で引っ張るのは型周りで大変そうな気がします。
確かに`getElementById`を使うのはVueらしくない(?)気がするのですが、最初から`HTMLElement | undefined`型がついている`getElementById`の方が扱いやすいのかなと思いました。
(後、なぜか`this.$refs`はエラーが出て使えませんでした...何か使い方があるんでしょうか...?)

2022-01-02 12:05 UTC, y-chan commented on tests/unit/store/Vuex.spec.ts
> +        audioPlayOffset: 0,
既に足りないものが多くあるので、あまり気にしていませんでした。
念のため追加しておきます。

2022-01-02 12:28 UTC, MT224244 commented on src/components/AudioDetail.vue
> +      );
`this.$refs` はVue3のCompositionAPIでは使えなくなっています。
CompositionAPIでの書き方は下記のドキュメントが参考になると思います。

- [v-forのref配列](https://v3.ja.vuejs.org/guide/migration/array-refs.html)
- [テンプレート参照](https://v3.ja.vuejs.org/guide/composition-api-template-refs.html)

探してみると `Home` の `addAudioCellRef` や `AudioCell` の `textfield` でも似たようなことをしている箇所があったので、そちらも参考になると思います。

2022-01-02 13:04 UTC, y-chan commented on src/components/AudioDetail.vue
> +      );
なるほど、そうだったのですね...
ありがとうございます、少し読んでみます。

2022-01-10 17:22 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +      );
`ref`にして頂けると･･･！

ちなみに全然難しくなかったりします。例としてscrollerを見てみると、

idをrefにしてcamelCaseにし
https://github.com/VOICEVOX/voicevox/blob/c83af58e4a39b9c1427a76ebae063d87f4ec842b/src/components/OssLicense.vue#L3

ref型の変数を定義して
https://github.com/VOICEVOX/voicevox/blob/c83af58e4a39b9c1427a76ebae063d87f4ec842b/src/components/OssLicense.vue#L52

returnに含めるだけです（これ忘れがちです。。）
https://github.com/VOICEVOX/voicevox/blob/c83af58e4a39b9c1427a76ebae063d87f4ec842b/src/components/OssLicense.vue#L64

2022-01-10 18:31 UTC, Hiroshiba requested changes
ちょっとまだ全部見れていないのですが、コメントしてみました！！

2022-01-10 18:31 UTC, Hiroshiba commented on src/store/audio.ts
> +  audioPlayOffset: 0,
何のオフセットか若干ややこしい（たとえば連続再生するときの開始セル番号かもしれない、とか）ので、ぱっと分かるコメントの追加をお願いしたいかもです。

2022-01-10 18:31 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +    let accentPhraseOffsets: number[] = [];
`accentPhraseOffsets`はたぶん`computed`で書くと綺麗にできると思います！
たぶんこんな感じです

```ts
accentPhraseOffsets = computed(() => {
      accentPhraseOffsets = [];
      if (newPhrases === undefined) return;
      let length = 0;
      accentPhraseOffsets.push(length);
      // pre phoneme lengthは最初のアクセント句の一部として扱う
      length += query.value !== undefined ? query.value.prePhonemeLength : 0;
      newPhrases.forEach((phrase, i) => {
        phrase.moras.forEach((m) => {
          length += m.consonantLength !== undefined ? m.consonantLength : 0;
          length += m.vowelLength;
        });
        length +=
          phrase.pauseMora !== undefined ? phrase.pauseMora.vowelLength : 0;
        // post phoneme lengthは最後のアクセント句の一部として扱う
        if (i === newPhrases.length - 1) {
          length +=
            query.value !== undefined ? query.value.postPhonemeLength : 0;
        }
        accentPhraseOffsets.push(length);
      });
     return accentPhraseOffsets ;
})

```

2022-01-13 09:17 UTC, y-chan reviewed
色々指摘してもらった点を改善してみました。

2022-01-13 09:17 UTC, y-chan commented on src/store/audio.ts
> +  audioPlayOffset: 0,
追加しました。

2022-01-13 19:37 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +      );
refのリストを作れば一応解決できます。
refに関数を指定できるので、これで（無理やり）実装する形です。
https://v3.ja.vuejs.org/guide/migration/array-refs.html#frontmatter-title

VOICEVOX内でも一箇所これが使われていたりします。
https://github.com/VOICEVOX/voicevox/blob/a76f5159eee73429ff2743f023355880f891d108/src/views/Home.vue#L294-L302

が、まあちょっとややこしいので、idでも良いかなと思いました。

2022-01-14 07:49 UTC, y-chan commented on src/components/AudioDetail.vue
> +      );
refを使って書き直しました...!

2022-01-14 10:55 UTC, Hiroshiba approved these changes
LGTM！！

自動再生のON/OFF機能とかが実装されたら、バージョン0.10に組み込みたいなと考えています！
もしよければ･･･！

2022-01-18 14:20 UTC, y-chan commented
> 話速変更時におかしくなる問題の修正待ちというステート

現状はそうです...!
加えて設定画面(連続追従/ページめくり/オフ)の追加までやろうと思ってたんですが、どうですかね...?

2022-01-18 18:30 UTC, y-chan commented
本PR内で、挙がっていた問題の修正、設定画面の追加までやってしまいました。
少し変更量が多いですが、よろしくお願いします...!

https://user-images.githubusercontent.com/34832037/149997281-a3d5b244-40f1-44f2-ad2c-3adbad4b8333.mp4

2022-01-19 02:34 UTC, Hiroshiba requested changes

2022-01-19 02:34 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +      console.log("conputing");
👀

2022-01-19 02:34 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +    // 再生開始位置・話速変更時に、play offsetを更新する
いろんなとこでsetPlayOffsetが必要になってて、ステートの変更がややこしくなってそうだなと感じました。
将来この関数を呼ぶべきタイミングで呼び忘れてしまうことがそこそこ想像できそうです。

startPointをvuex側で持っておいてplayOffsetを再生時のタイミングで計算するようにすると綺麗になるかもです。

2022-01-19 07:04 UTC, y-chan commented on src/components/AudioDetail.vue
> +      console.log("conputing");
おっと...typoもしているデバッグログを消し忘れていました...w

2022-01-19 07:04 UTC, y-chan commented on src/components/AudioDetail.vue
> +    // 再生開始位置・話速変更時に、play offsetを更新する
将来的な改変(音素単位等での再生位置指定)のことを考えて`audioPlayOffset`のみをVuexに持たせていましたが、もはやその必要もなさそうな気がするので、仰る通り再生開始アクセント位置をVuexに持たせ、再生する度に算出するのが綺麗いそうですね...
その方向で修正してみます。

2022-01-19 07:14 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +    // 再生開始位置・話速変更時に、play offsetを更新する
あ、仮にそうなった場合はおそらくstartPointに音素単位の再生位置情報が含まれると思います。
であれば、startPointをVuexに持たせておけば自然な拡張で`audioPlayOffset`を計算できるかもです･･･！

2022-01-19 13:56 UTC, y-chan commented on src/components/AudioDetail.vue
> +    // 再生開始位置・話速変更時に、play offsetを更新する
`audioPlayOffset`をstore内で持つ必要がなくなったこと(将来的な目的で残してもいいが、冗長になる)から、`audioPlayStartPoint`に変更し、`accentPhraseOffsets`を`GET_AUDIO_PLAY_OFFSETS` actionとしてVuexに移動させました。
若干気持ち悪さが残りますが、私的にはこれ以上綺麗に書けそうになかったです....

2022-01-20 17:41 UTC, Hiroshiba requested changes

2022-01-21 15:22 UTC, y-chan commented on src/components/AudioDetail.vue
> +      if (elem === undefined) return;
上で指摘いただいたnextTickを使うべき場所で、arrayの範囲外指定のせいでundefinedを拾うことがあったので、入れていたものです。
nextTickを使ったことでここに入ることがなくなったので、消します。

2022-01-21 15:59 UTC, y-chan commented on src/store/type.ts
> +  audioPlayStartPoint: number | null;
undefinedですね、undefinedにしておきました。

2022-01-21 16:02 UTC, y-chan commented
頂いた指摘の改善をしてみました。
レビューお願いします...!

2022-01-21 18:54 UTC, Hiroshiba approved these changes
LGTM！！

１つだけ、修正してもしなくてもというコメントをしてみました。

2022-01-21 18:54 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +      if (elem === undefined) return;
良いと思います！
もしくはコメントの内容をそのままロジックに落とし込んで、
```ts
if (accentPhraseElems.length == 0) return;
```
にするのもいいかなと思いました！

2022-01-21 19:12 UTC, y-chan commented on src/components/AudioDetail.vue
> +      if (elem === undefined) return;
なるほど...!
確かにそうですね！
そのように修正してみました...!

2022-01-23 16:24 UTC, Hiroshiba requested changes
すみません･･･。
試しに利用していたときに気づいたことを１つだけ修正お願いしたいです。

途中から再生し始めたとき、一瞬だけ１つ前のアクセントフレーズが光りそうです。
https://user-images.githubusercontent.com/4987327/150687927-65697741-8295-406e-b275-8d1f37383e4b.mp4

たぶんユーザーさんから目が疲れる的な指摘をもらいそうなので、なんとかして防ぎたく。。

2022-01-23 16:45 UTC, y-chan commented
調べてみたところ、currentTimeをセットした後、再生時に小さい値が切り捨てられることによって少し時間が戻るということが起きていることによって起きているようです。
微小かつ、切り捨てられないギリギリの値を加算することで対応してみました。
また、`activePoint`の移動条件を厳密化しました(`<`から`<=`へ)。

2022-01-23 18:16 UTC, Hiroshiba requested changes
素早い修正ありがとうございます！！

何回もリクエストをお願いしてすみません。。
よくあるページ送りの実装は、見えていない部分があるときに先にスクロールする感じになっていると思うので、アクセント句のうち見えないところがあったらスクロールという処理に変えて頂けると･･･。。

2022-01-23 18:18 UTC, y-chan commented
> アクセント句のうち見えないところがあったらスクロール
対応しました...!

2022-01-23 18:25 UTC, Hiroshiba approved these changes
LGTM！！！

需要の有りそうな２つの機能の実装、ありがとうございました！！！

2022-01-23 18:26 UTC, merged