0.4.1のプロジェクトが0.9.3で開けないバグを修正
VOICEVOX/voicevox pull request #595
Opened 2021-12-14 15:53 UTC by yuqquu

## 内容
2点です。
- (タイトル通り) 0.4.1で保存されたプロジェクトファイル(.vvproj)が0.9.3で開けないバグを修正
- undefinedの判定を厳密化

## 関連 Issue
close #592 

## その他
0.4.1、0.5.3、0.6.1、0.7.5、0.8.2、0.9.3で保存されたプロジェクトが正常に読み込まれることを確認しました。

2021-12-14 16:12 UTC, y-chan requested changes
内容はLGTMです...!
ただ、後々のため(なぜここだけ`characterIndex`なのか)にこのあたりにコメントを書いておいてもらえないでしょうか...?(日本語でも英語でも、わかりやすいように残しておいてもらえると大変ありがたいです...!)

2021-12-15 04:23 UTC, yuqquu commented
レビューありがとうございます！
確かに、あとから変更されて再発しそうですね。
コメントを加えました。

2021-12-15 08:36 UTC, y-chan approved these changes
LGTMです、ありがとうございます!

2021-12-15 10:46 UTC, Hiroshiba approved these changes
LGTM！！
（issueにて確認頂くご連絡をお願いできるととても嬉しいです･･･！）

2021-12-15 10:46 UTC, merged