Mac版アプリの文言を追加
VOICEVOX/voicevox pull request #602
Opened 2021-12-17 18:34 UTC by Apple-Yuki

Mac版アプリの文言を追加

## 内容

Mac版のインストール、起動、アンインストール方法など追記

## 関連 Issue

（例）
ref #601

## その他

2021-12-17 22:08 UTC, Hiroshiba requested changes

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +**重要**：Apple Silicon製CPUのMacシリーズでは、「Rosetta 2」のインストールが必要です。「Rosetta 2」は初回起動時、未インストールの場合のみmacOSよりインストールの案内がありますので、案内に沿ってインストールしてください。
Rosettaの案内良いですね！
こちらも同じく、重要というのは外しちゃいましょう
```suggestion
Apple Silicon製CPUのMacシリーズでは、「Rosetta 2」のインストールが必要です。「Rosetta 2」は初回起動時、未インストールの場合のみmacOSよりインストールの案内がありますので、案内に沿ってインストールしてください。
```

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +**※Mac版ではGPU モードはご利用頂けません。**
まああえて書かなくても、わかるかなと思います。

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
え、そうなんですか！！
ちょっとこれは問題だと思うので、issueにして頂けると助かります！

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +**注記**:サードパーティーアプリ「[AppCleaner](https://freemacsoft.net/appcleaner/) 」で関連ファイルごと（隠しフォルダ内のものも含む）完全削除することもできます。
こちらもまあ案内しなくていいかなと思いました。

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +**警告**: そのアプリケーションは、次に手動で「ゴミ箱」を空にしたとき、またはFinderによって「ゴミ箱」が空にされたときに、Macから恒久的に削除されます。「VOICEVOX」で作成したファイルがある場合は、それらを開くことができなくなることがあります。「VOICEVOX」を残すことにした場合は、「ゴミ箱」を空にする前に戻してください。「ゴミ箱」でアプリケーションを選択し、「ファイル」＞
アンインストールするということはそういうことだというのはわかっていると思うので、案内しなくてもいいかなと思います。
（再インストールしても）二度とVOICEVOXを使えないのかと勘違いする人も出てくるかもしれません。

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +  ダウンロードした「VOICEVOX」を手動で「アプリケーション」フォルダーにコピーします。
windows版と表記を合わせて、そのアプリケーションフォルダーのパスを書くのが優しいのかなと思いました。

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +
「GPUがないパソコン」の中にmacは含まれているので、あえて二回案内しなくてもいいかなと思います

2021-12-17 22:08 UTC, Hiroshiba commented on public/howtouse.md
> +
同上です

2021-12-18 00:23 UTC, PickledChair commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
設定されているはずです。`Cmd + S` 等ではなく `Ctrl + S` 等ですが……

Mac ユーザーが初手で `Cmd` を使った操作をしてショートカットキーが効かず、「VOICEVOX ではショートカットキーが使えない」と思い込む可能性はありそうですかね……？

2021-12-18 03:17 UTC, Apple-Yuki commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
現状のこちらで持ってるビルド（私のGitでビルド）では、`⌘Command`がMetaになってしまう仕様のものしかないので、現状使えないです。（⌘ + Nとかも試しましたけど）

2021-12-18 03:23 UTC, Apple-Yuki commented on public/howtouse.md
> +**※Mac版ではGPU モードはご利用頂けません。**
まぁ、一応Mac版の現状仕様としてGPUモード切り替えのボタンがある以上、使えないことは明記は必要かなと思ったので記載しました。

このたりは、以前の改善案の言及になります。#298　https://github.com/VOICEVOX/voicevox/issues/576#issuecomment-994763478

2021-12-18 03:28 UTC, Apple-Yuki commented on public/howtouse.md
> +  ダウンロードした「VOICEVOX」を手動で「アプリケーション」フォルダーにコピーします。
実は、現状アプリケーションパスとして `/application/`と` /User/（username）/application/`があって今 Apple developer チームにこれらの違いは何か一旦確認してるのでパス記載は保留にしてます。（Apple Siliconだとこうがいいとか、突然こちらにおいてくださいとかmacOSの仕様が変わりかねないので）

2021-12-18 03:39 UTC, Apple-Yuki commented on public/howtouse.md
> +
Macは、MacProシリーズ、Intel版Macbook Pro（15インチと16インチ）シリーズ、iMacPro（生産終了）はがディスクリート型GPUが搭載されてるのでこの記載が必要かと

MacProシリーズの技術資料は[こちら](https://support.apple.com/ja-jp/HT202888)で確認できます。
iMacProの技術資料は[こちら](https://support.apple.com/kb/SP771)で確認できます。

歴代MacBook Pro GPUはこちら
![macbook-pros-gpu-list](https://user-images.githubusercontent.com/91584669/146627606-db41094f-d33a-4325-9553-693f476fcd67.jpg)

2021-12-18 03:42 UTC, Apple-Yuki commented on public/howtouse.md
> +
同上です

2021-12-18 03:45 UTC, Apple-Yuki commented on public/howtouse.md
> +**注記**:サードパーティーアプリ「[AppCleaner](https://freemacsoft.net/appcleaner/) 」で関連ファイルごと（隠しフォルダ内のものも含む）完全削除することもできます。
一応アンインストールの手順の場所なので記載しています。

**以下は削除予定です。**
**注記**:サードパーティーアプリ「[AppCleaner](https://freemacsoft.net/appcleaner/) 」で関連ファイルごと（隠しフォルダ内のものも含む）完全削除することもできます。

2021-12-18 03:52 UTC, Apple-Yuki commented on public/howtouse.md
> +**警告**: そのアプリケーションは、次に手動で「ゴミ箱」を空にしたとき、またはFinderによって「ゴミ箱」が空にされたときに、Macから恒久的に削除されます。「VOICEVOX」で作成したファイルがある場合は、それらを開くことができなくなることがあります。「VOICEVOX」を残すことにした場合は、「ゴミ箱」を空にする前に戻してください。「ゴミ箱」でアプリケーションを選択し、「ファイル」＞
なるほど。
そうですねぇ...けど、大体のmac向けのソフトウェアのページを見てると同じことは書いてあるので記載はしたほうがいい気がすると思います。ただ、再インストールすれば再度それらのファイルは使えることは太字のように追記した方がいいですかね。

**警告**: そのアプリケーションは、次に手動で「ゴミ箱」を空にしたとき、またはFinderによって「ゴミ箱」が空にされたときに、Macから恒久的に削除されます。「VOICEVOX」を残すことにした場合は、「ゴミ箱」を空にする前に戻してください。「ゴミ箱」でアプリケーションを選択し、「ファイル」＞「戻す」と選択します。**なお、「VOICEVOX」を再インストールすることで作成したプロジェクトファイルは開けるようになります。**

**「VOICEVOX」で作成したファイルがある場合は、それらを開くことができなくなることがあります。**という記載は一旦削除します。（プロジェクトファイルの仕様とかの変更での互換性で使えなくなる可能性はありますけど）

2021-12-18 03:56 UTC, Apple-Yuki commented on public/howtouse.md
> +Macでこれらの環境設定を変更するには、アップルメニュー  ＞「システム環境設定」と選択して「セキュリティとプライバシー」 をクリックし、「一般」をクリックします。
**注記**: は外しちゃいます。

2021-12-18 06:03 UTC, Hiroshiba commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
なるほど！！
cmdではなくctrlなのは、どうした方がいいですかね…ちょっとissue建ててみて意見募集してみます！

- https://github.com/VOICEVOX/voicevox/issues/604

2021-12-18 06:04 UTC, Hiroshiba commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
あ、であれば最新のビルドではcmdでショートカットキーが設定できるはずなので、この説明は混乱を生むかもしれません。

2021-12-18 06:06 UTC, Hiroshiba commented on public/howtouse.md
> +**注記**:サードパーティーアプリ「[AppCleaner](https://freemacsoft.net/appcleaner/) 」で関連ファイルごと（隠しフォルダ内のものも含む）完全削除することもできます。
あ、注記のとこだけ選んでたつもりでしたが範囲間違えました！
アンインストール方法は案内すべきだと思うので、良さそうです。

2021-12-18 06:10 UTC, Hiroshiba commented on public/howtouse.md
> +**警告**: そのアプリケーションは、次に手動で「ゴミ箱」を空にしたとき、またはFinderによって「ゴミ箱」が空にされたときに、Macから恒久的に削除されます。「VOICEVOX」で作成したファイルがある場合は、それらを開くことができなくなることがあります。「VOICEVOX」を残すことにした場合は、「ゴミ箱」を空にする前に戻してください。「ゴミ箱」でアプリケーションを選択し、「ファイル」＞
うーん、前例に倣うのは良い時と悪い時があって、真似する理由が特にない時は真似しない方が良いかなと考えています。
消したら消える、というのはそりゃそうなので、わざわざ案内しなくても良いかなと感じています。

意図としては、そもそもアンインストールとはなんなのかがわからない人のために、アンインストールとはアプリを消すことだよと教えたい、という感じでしょうか？

2021-12-18 06:12 UTC, Hiroshiba commented on public/howtouse.md
> +  ダウンロードした「VOICEVOX」を手動で「アプリケーション」フォルダーにコピーします。
おお、なるほどです。
であればパスは書かず、文章をちょっと修正でしょうか。
```suggestion
  ダウンロードした「VOICEVOX」を手動でコピーした「アプリケーション」フォルダーにあります。
```

2021-12-18 06:14 UTC, Hiroshiba commented on public/howtouse.md
> +
なるほど！！
であれば記載すべきだと感じました。
macを使っている人に伝われば良いので、太字はなくても良いかなと思いました。

2021-12-18 06:16 UTC, Hiroshiba commented on public/howtouse.md
> +
こちらはgpuではなくcpuを使ってください、という案内なので、winでもmacでも共通そうです。
なのでこちらの注意書きは例外とならないので、なくても良いかなと思います。

2021-12-18 07:37 UTC, Apple-Yuki commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
でも最新ビルドでも⌘ + Sとかは、再設定しないと機能しないですね。

2021-12-18 07:48 UTC, Hiroshiba commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
はい。ただ初期状態でショートカットキーは設定されているので、説明は無くても良いかなと思います。
cmdにすべきかはこちらで議論しましょう！

- https://github.com/VOICEVOX/voicevox/issues/604

2021-12-18 08:15 UTC, Apple-Yuki commented on public/howtouse.md
> +お手数ですが手動で設定をお願いいたします。
一旦決まるまでショートカットのところは一旦削除しました。

2021-12-18 08:15 UTC, Apple-Yuki commented on public/howtouse.md
> +**警告**: そのアプリケーションは、次に手動で「ゴミ箱」を空にしたとき、またはFinderによって「ゴミ箱」が空にされたときに、Macから恒久的に削除されます。「VOICEVOX」で作成したファイルがある場合は、それらを開くことができなくなることがあります。「VOICEVOX」を残すことにした場合は、「ゴミ箱」を空にする前に戻してください。「ゴミ箱」でアプリケーションを選択し、「ファイル」＞
以下を削除しました。

警告: そのアプリケーションは、次に手動で「ゴミ箱」を空にしたとき、またはFinderによって「ゴミ箱」が空にされたときに、Macから恒久的に削除されます。「VOICEVOX」を残すことにした場合は、「ゴミ箱」を空にする前に戻してください。「ゴミ箱」でアプリケーションを選択し、「ファイル」＞「戻す」と選択します。なお、「VOICEVOX」を再インストールすることで作成したプロジェクトファイルは引き続きご利用頂けます。

2021-12-18 08:16 UTC, Apple-Yuki commented on public/howtouse.md
> +  ダウンロードした「VOICEVOX」を手動で「アプリケーション」フォルダーにコピーします。
**ダウンロードした「VOICEVOX」を手動でコピーした「アプリケーション」フォルダーにあります。**へ変更しました。

2021-12-18 08:16 UTC, Apple-Yuki commented on public/howtouse.md
> +
太字は削除しました

2021-12-18 08:16 UTC, Apple-Yuki commented on public/howtouse.md
> +
該当文言は削除しました。

2021-12-18 08:41 UTC, Hiroshiba commented on public/howtouse.md
> +**※Mac版ではGPU モードはご利用頂けません。**
macとnvidia gpuの組み合わせは存在しないと勘違いしていたのでこのようにコメントしていました。
この組み合わせがあり得るとのことだったので、注意書きはあった方が良いなと感じました！

2021-12-18 08:47 UTC, Apple-Yuki commented on public/howtouse.md
> +**注記**:サードパーティーアプリ「[AppCleaner](https://freemacsoft.net/appcleaner/) 」で関連ファイルごと（隠しフォルダ内のものも含む）完全削除することもできます。
1. Macで、DockのFinderアイコンをクリックし、Finderのサイドバーで「アプリケーション」をクリックします。
2. アプリケーションを「アプリケーション」フォルダから「VOICEVOX」を「ゴミ箱」（Dockの端にあります）にドラッグします。

の部分は残してあります

2021-12-18 12:41 UTC, Hiroshiba commented on public/howtouse.md
> +**Windows：**
強調表示を使わないようにしてください。
本当に強調したいことが現れたときに難しくなるためです。

2021-12-18 12:42 UTC, Hiroshiba commented on public/howtouse.md
> +設定ファイルのパス：`/Users/(UserName)/Library/Saved\ Application\ State/jp.hiroshiba.voicevox.savedState`
設定ファイルのパスが２つありそうですが、違いは何ですか👀

2021-12-18 12:42 UTC, Hiroshiba commented on public/howtouse.md
> +  `/Users/(UserNames)/Applications`
表記ゆれをなくしたいので、文頭のスペースは外してください。

2021-12-18 12:44 UTC, Hiroshiba commented on public/howtouse.md
> +  `/Users/(UserNames)/Applications`
改行したい場合は<br>でも良いのですが、markdown記法の「半角スペース２つつける」方の方法でお願いします

2021-12-18 12:54 UTC, Apple-Yuki commented on public/howtouse.md
> +設定ファイルのパス：`/Users/(UserName)/Library/Saved\ Application\ State/jp.hiroshiba.voicevox.savedState`
前者のパスは主にアプリケーションの設定パスで
<img width="988" alt="スクリーンショット 2021-12-18 21 51 08" src="https://user-images.githubusercontent.com/91584669/146641777-bda8845c-ed44-46d2-8597-91d660aaeed2.png">

後者のパスは、ウインドウサイズなどを管理している設定データ保存パスですね。
<img width="1032" alt="スクリーンショット 2021-12-18 21 51 04" src="https://user-images.githubusercontent.com/91584669/146641806-a820e9ef-3eab-4f3c-a0b4-8352a4ba41b6.png">

どちらにもvoicevoxの設定データが保存されているパスになります。

2021-12-18 13:05 UTC, Apple-Yuki commented on public/howtouse.md
> +  `/Users/(UserNames)/Applications`
修正しました

2021-12-19 10:17 UTC, PickledChair commented on public/howtouse.md
> +設定ファイルのパス：`/Users/(UserName)/Library/Saved\ Application\ State/jp.hiroshiba.voicevox.savedState`
VOICEVOX 側で能動的に使用している設定は前者のパス `/Users/(UserName)/Library/Application\ Support/voicevox-cpu` にあります（config.json などが保存されています）。一方、後者は Apple のフレームワークが利用している設定が記録されているのだと考えられます（公式のドキュメントは見つけられなかったのですが、[この英語記事](https://osxdaily.com/2011/07/17/delete-specific-application-saved-states-from-mac-os-x-10-7-lion-resume/)や[この日本語記事](http://battleformac.blog.jp/archives/52367917.html)によると、一度閉じたアプリを再び開く時に、閉じた時と同じ状態に復帰させるための情報を記録しているようです。VOICEVOX ではそのような機能はないため、ここの設定情報は使っていないと思いますが……）。

後者のディレクトリは、アプリケーションの挙動がおかしくなった時によく削除を勧められていたりする印象です（例：[楽譜作成ソフトの Finale の場合](https://www.finalemusic.jp/faq/faq.cgi?v=2012022218045950&s=&r=&l=&h=&p=5)）。削除してもしなくても構わなそうですが、万全を期すなら後者のパスも書いてあって良さそうです。

個人的には両者の先頭の項目名を「設定ファイルのパス１」「設定ファイルのパス２」などとすると良さそうな気がしていますが、どうでしょうか……？

2021-12-19 10:35 UTC, PickledChair commented on public/howtouse.md
> +**Windows：**
@Apple-Yuki  文の中の特定の部分を強調するのではなく、段落のタイトルを太字にしたい場合は、以下の部分を参考にして、`**` で囲う代わりに `####` を先頭に書くと良いと思います。

https://github.com/VOICEVOX/voicevox/blob/8bf3a989d485075d1e2b8fd6d12fc6f34dbfb7b1/public/howtouse.md?plain=1#L186-L199

2021-12-21 08:21 UTC, Apple-Yuki commented on public/howtouse.md
> +設定ファイルのパス：`/Users/(UserName)/Library/Saved\ Application\ State/jp.hiroshiba.voicevox.savedState`
@PickledChair 最新のアップデートで①、②と表記を変えました。
また各種のパスの簡単な説明も記載しました。

2021-12-21 08:22 UTC, Apple-Yuki commented on public/howtouse.md
> +**Windows：**
手順分岐するものの案内を全て`****`から`####`へ変更しました。

2021-12-21 09:26 UTC, PickledChair requested changes
もう一息で行けそうな感じになってきたと思います。
気になったところをチェックしました（細かすぎるところもあるかもしれません……）。特に、見出しの `#` の数には意味がある（ html タグの `<h1>, <h2>, ...` と対応しており、基本的には下の階層に移るごとに一個ずつ増やす）ので、数を調整していただければと思います。よろしくお願いします。

2021-12-21 09:26 UTC, PickledChair commented on public/howtouse.md
> +#### Apple Silicon搭載のMacユーザー向け
細かくて申し訳ないのですが、「Apple Silicon搭載のMacユーザー向け」よりも「Apple Silicon搭載のMacをお使いの場合」などの方が印象が柔らかくなり良いと思います。

2021-12-21 09:26 UTC, PickledChair commented on public/howtouse.md
> +<img src="res/gatekeeper.png" style="max-height: 16rem" />
この部分は文章末尾の後ろに画像がそのまま並んでしまいます（下画像参照）。文章の下に画像が配置されるように、文章と画像の間に以下のように空の１行を入れてください：

```
初回起動時はAppleに登録されていないアプリケーションとして警告ダイアログが表示されます。

<img src="res/gatekeeper.png" style="max-height: 16rem" />
```

<img width="562" alt="img_inline" src="https://user-images.githubusercontent.com/41382894/146903997-01ce74f8-bb26-4a9f-9fdf-ac7e18cad32f.png">

2021-12-21 09:26 UTC, PickledChair commented on public/howtouse.md
> +Mac版ではGPUモードに対応してないためGPUモードでは起動しません。
「してない」は口語的な言い回しなので、「していない」の方が適切かもです。

2021-12-22 05:00 UTC, PickledChair requested changes
変更の必要のない部分が変更されてしまっていたので、元に戻していただければと思います（[255行目](https://github.com/VOICEVOX/voicevox/pull/602/commits/df226f5e0e046955a0f49f323e74ba8792223aa9#diff-36ff69cd0f0bd89813dfa04264b93db5eea87569b4337e67b3b9f0671563875cR255)と[259行目](https://github.com/VOICEVOX/voicevox/pull/602/commits/df226f5e0e046955a0f49f323e74ba8792223aa9#diff-36ff69cd0f0bd89813dfa04264b93db5eea87569b4337e67b3b9f0671563875cR259)の `#` の数を４つに戻してください）。よろしくお願いします。

2021-12-22 05:00 UTC, PickledChair commented on public/howtouse.md
> +### Windows版
ここの `#` の数の調整をお願いしていなかったと思うのですが、それは `#` が４つのままで良かったからです。４つに戻していただければと思います。

2021-12-22 05:00 UTC, PickledChair commented on public/howtouse.md
> +### Mac版
ここの `#` の数の調整をお願いしていなかったと思うのですが、それは `#` が４つのままで良かったからです。４つに戻していただければと思います。

2021-12-22 08:45 UTC, Apple-Yuki commented on public/howtouse.md
> +### Mac版
@PickledChair 
置換で修正したので、合わせて変わっちゃったようです。
先ほど修正しましたのでご確認ください。

2021-12-22 09:04 UTC, PickledChair approved these changes
LGTM!

細かい部分の修正・調整が大変だったと思います。お疲れ様でした。対応ありがとうございました。

2021-12-22 09:10 UTC, Hiroshiba approved these changes
LGTM！！

細かいとこ（〜版の統一）だけこちら側で修正させて頂いてからマージしたいと思います！

2021-12-22 09:10 UTC, Hiroshiba commented on public/howtouse.md
> +#### Mac：
```suggestion
#### Mac版
```

2021-12-22 09:10 UTC, Hiroshiba commented on public/howtouse.md
> +#### Windows：
```suggestion
#### Windows版
```

2021-12-22 09:10 UTC, Hiroshiba commented on public/howtouse.md
> +#### Mac版：
```suggestion
#### Mac版版
```

2021-12-22 09:11 UTC, merged