プロジェクト保存ダイアログにデフォルトファイル名を設定
VOICEVOX/voicevox pull request #606
Opened 2021-12-18 21:43 UTC by aoirint

## 内容

#574 への対応として、プロジェクト保存ダイアログでデフォルトファイル名を設定するようにします。

デフォルトファイル名に拡張子を付けておくことで、プロジェクトが拡張子なしで保存されにくくすることを目的にしています。

#574 に書きましたが、ダイアログの仕様がOSによって違うので、OSごとに処理を分けてもいいかもしれないです。Linuxではダイアログの仕様がインストールされているデスクトップ環境にも依存しそうですが、ひとまずUbuntu標準のGNOMEを想定しています。

- ファイル名の仕様は以下に合わせています
    - #549
- ただし、なにもテキストが入力されていないときは`Untitled.vvproj`にしています
    - プロジェクトのデフォルトファイル名を空欄にしないようにするPRです
    - 日本語環境的には、`無題.vvproj`でもいいかもです
    - ファイル名のstem部分にスペースを入れると、拡張子だけを残してファイル名を変えにくくなるので、スペースは入れない方がいいと思っています
- 保存済みのプロジェクトを「名前を付けて保存」した場合、デフォルトファイル名として、もとのプロジェクトのパスを使用するようにしてみました
    - もとの挙動の方がよさそうであれば、自動生成ファイル名を使うように変えます
- ユーザがダイアログ中でファイル名から拡張子を削除した場合、拡張子が付くかどうかはOS依存です
    - Ubuntu：拡張子なしのファイルになる（これは仕様＝ユーザの選択と考える）
    - Windows, macOS：拡張子が自動で追加される
- 将来的には、 #569 のようにデフォルト名を設定できてもいいかもです

プロジェクトを開くときには拡張子でフィルタされるので、拡張子を強制的に追加する実装方法もありそうですが、ファイル名はユーザに委ねる方向にしています。

## 関連 Issue

- ref #574 

## スクリーンショット・動画など

## その他

2021-12-22 10:53 UTC, y-chan approved these changes
LGTM!

デフォルトファイル名指定は良い判断だと思いました...!
その他の点も特に問題なさそうだと個人的には思いました。

2021-12-27 06:45 UTC, Hiroshiba requested changes

2021-12-27 06:45 UTC, Hiroshiba commented on src/store/project.ts
> +                : headItemText;
考えすぎかもですが、`/`などの文字が入っていると怖いかもです。
このあたりの除外処理をutilityなどに移してこちらでも使う、とかを思いつきました。

https://github.com/VOICEVOX/voicevox/blob/f1a5a0049d58b191e573dd9be69adc1f7287efd9/src/store/audio.ts#L113

2021-12-28 01:48 UTC, aoirint commented on src/store/project.ts
> +                : headItemText;
ファイル名のsanitize処理・デフォルトプロジェクトファイル名の生成処理を`utility/file`に切り出してみました。

ファイルのsanitize処理`sanitizeFileName`は、音声書き出し、音声を繋げて書き出し（`store/audio`）、プロジェクト保存（`store/project`）で使っています。

デフォルトプロジェクトファイル名の生成処理`buildProjectFileName`は、音声を繋げて書き出し（`store/audio`）、プロジェクト保存（`store/project`）で使っています。

修正箇所の周りで、以下のような追加の修正をしました。

- 音声書き出し
    - 音声ファイル保存時のstyleNameのsanitizeを追加
- 音声を繋げて書き出し
   - 音声ファイル保存先が固定されているとき、出力される音声ファイルの拡張子がなかったので追加
   - 音声ファイル保存先選択ダイアログのデフォルトファイル名に拡張子を追加

2021-12-28 15:19 UTC, Hiroshiba approved these changes
LGTM！！

このままマージでも大丈夫そうに感じました！
が、ちょっと何となくコメントなのですが、今回のutilityは`src/store/*.ts`から参照されているので、その共通の親である`src/store/`の下にutility.tsを作ると、誰から使われそうなスコープなのかがわかって良いかなと思いました。

まあ正直どちらでも良さそうなので、忙しければセルフマージして頂ければ！

2021-12-28 19:52 UTC, aoirint commented
`utility/file.ts`を`store/utility.ts`にリネームしました。
関数が増えたときなどに切り分けを考える形かなと思います。

2021-12-29 07:16 UTC, Hiroshiba commented
LGTM！！

2021-12-29 07:16 UTC, merged