feat: 疑問文自動調整設定機能追加
VOICEVOX/voicevox pull request #610
Opened 2021-12-19 16:22 UTC by qwerty2501

## 内容

Engineに疑問文自動調整機能が追加されたので、front側でその有効無効を調整できるようにする

## 関連 Issue
refs #608

## スクリーンショット・動画など

TODO

## その他

2021-12-19 18:19 UTC, qwerty2501 commented
openapiのコード生成について、以前生成したときから定義が変わっていないところについても生成されたコードが変わってるのでちょっと気になります

2021-12-20 04:12 UTC, y-chan commented on src/openapi/models/AccentPhrase.ts
> +    pauseMora?: Mora | null;
> openapiのコード生成について、以前生成したときから定義が変わっていないところについても生成されたコードが変わってる

ここのことでしょうか？
OpenAPI Generatorのバージョンによって何か変更が加わっているのかもしれません。
ただ、具体的に何が変わったのかはちょっとわからないです....
`openapi-generator-cli`ライブラリのバージョンは弄ってないはずですが、もしかしたら`cli`が取得する`openapi-generator`のバージョンが生成するたびに違っていて、新しいバージョンになっていることでこうなっているのかもと思いました(本当にそうかまでは調べてないです、すみません...)

2021-12-20 05:56 UTC, qwerty2501 commented on src/openapi/models/AccentPhrase.ts
> +    pauseMora?: Mora | null;
はい、気になったのはそこですね。
一度観点を分けるためにOpenAPIからのコード生成のみのPRを作ります

2021-12-20 05:58 UTC, y-chan commented on src/openapi/models/AccentPhrase.ts
> +    pauseMora?: Mora | null;
はい、その方が良いと思います…!

2021-12-22 11:20 UTC, qwerty2501 reviewed
設定フィールド一つ増やすのにここまで変更が必要なのかやや疑問なのですが、こういうものなのでしょうか。

ExperimentalSettingという型を作りネストさせてenableInterrogativeフィールドをもたせましたが余計だったかもしれません。
ただ将来的に疑問文が正式対応されたときにデフォルト値をtrueにしたかった場合、アップデート後既存ユーザーに疑問文が有効な状態で提供したほうが良いかなとおもってこうしました。
違ったら直します。

2021-12-22 11:20 UTC, qwerty2501 commented on tests/unit/store/Vuex.spec.ts
> +    assert.equal(store.state.experimentalSetting.enableInterrogative, false);
テストコードらしいものがこれしかなかったがこれでよいのか？

2021-12-23 01:18 UTC, y-chan commented on tests/unit/store/Vuex.spec.ts
> +    assert.equal(store.state.experimentalSetting.enableInterrogative, false);
現状、テストはしっかり整備されている状況ではないので、とりあえずこれで良いと思います...!

2021-12-27 05:55 UTC, Hiroshiba reviewed
レビュワーは @Hiroshiba と @y-chan でいってみますか！

2021-12-27 06:10 UTC, Hiroshiba requested changes
コメントの有無など、コードの意図を汲み取って書いて頂けていてすごく読みやすかったです！！

> 設定フィールド一つ増やすのにここまで変更が必要なのかやや疑問なのですが、こういうものなのでしょうか。

typescriptを極めるとおそらく半分くらい省けそうなのですが、間に合わずこうなっている感じです。

2021-12-27 06:10 UTC, Hiroshiba commented on src/background.ts
> +
`savingSetting`と同じく、`experimentalSetting`を全部取得したりsetしたりできると他の値も簡単に足せて嬉しいかもです

2021-12-27 06:10 UTC, Hiroshiba commented on src/store/audio.ts
> +        enableInterrogative,
`FETCH_ACCENT_PHRASES`はこのaudio.ts内の至るところから呼ばれていて、それぞれで`enableInterrogative`を取得して渡すのはいつか漏れが発生しそうと感じました。
この関数内で`state`から`enableInterrogative`を取得してしまうのはどうでしょう。

2021-12-27 06:10 UTC, Hiroshiba commented on src/store/audio.ts
> +        enableInterrogative,
こちらも同じくstateから取ってしまうとミスが防げそうだなと感じました！

2021-12-27 06:42 UTC, Hiroshiba requested changes

2021-12-27 06:42 UTC, Hiroshiba commented on src/components/SettingDialog.vue
> +                >
初回起動時、なぜか値が中途半端な箇所で止まっているのが気になりました。
![image](https://user-images.githubusercontent.com/4987327/147442129-7ab88067-f416-4414-a3fa-4d94982d3623.png)

（`%appdata%/voicevox-dev`のにあるconfig.jsonを消すことで試せると思います。）

`enableInterrogative`がfalseでもtrueでもない、おそらくundefinedになっているからかもしれません。

2021-12-27 15:53 UTC, qwerty2501 commented on src/background.ts
> +
ExperimentalSettingとしてまとめて保存、取得できるようにしました。
メンテ性考えると将来的にはもうぜんぶまとめちゃいたいですね。なんか分けないといけない理由あるんですかね？

> typescriptを極めるとおそらく半分くらい省けそうなのですが、間に合わずこうなっている感じです。

言語の問題には感じなかったのですが、言語機能のコンテキスト何でしょうか？

2021-12-27 16:20 UTC, qwerty2501 commented on src/store/audio.ts
> +        enableInterrogative,
ここstate受け取れたんですね。
直してみました

2021-12-27 16:21 UTC, qwerty2501 commented on src/store/audio.ts
> +        enableInterrogative,
DONE

2021-12-27 16:22 UTC, qwerty2501 commented on src/components/SettingDialog.vue
> +                >
ここも多分直せたと思います

2021-12-28 15:06 UTC, Hiroshiba commented on src/background.ts
> +
settingがまとまっていない理由はとくになさそうです。

型の定義が必要になっていてコピーが多くなっているのが半分くらいあります。
typescriptは型を実装から抽出することもできるはずで、そうすると減るのかなと思っています

2021-12-28 15:11 UTC, Hiroshiba approved these changes
LGTM！！

@y-chan さんもお時間あるときに見て頂けると！

2021-12-28 15:11 UTC, Hiroshiba commented on src/background.ts
> -          default: false,
ちょっと良く覚えてないのですが、たしかこっちのdefault値も必要だった記憶がぼんやりあります。
下のdefaultはdictがなかったときに追加されて、こっちのdefaultはdictの要素がなかったときに使われる感じです。

ということで次のコメントのsuggestを適用して頂けると！

2021-12-28 15:11 UTC, Hiroshiba commented on src/background.ts
>          },
```suggestion
          default: false,
        },
```

2021-12-28 15:21 UTC, y-chan approved these changes
LGTM！

特に大きく問題はないと思いました！
次のバージョンで疑問文が使えるようになるのが楽しみです....!

2021-12-28 15:23 UTC, merged