お問い合わせ画面の増設（#615）
VOICEVOX/voicevox pull request #620
Opened 2021-12-25 18:56 UTC by Apple-Yuki

## 内容

[ディスカッション：使い方の一番下にあるお問い合わせに関して #615 ](https://github.com/VOICEVOX/voicevox/issues/615)でしているお問い合わせ画面の追加のプルリクです。

## 関連 Issue

close #615

## その他
`src/components/ContactInfo.vue`の`Contact.value = md.render(await store.dispatch("GET_Coninfo_TEXT"));`がうまくビルド通らなくて悩み中。

2021-12-27 05:53 UTC, Hiroshiba requested changes
良いですね！！！
文字ケースと名前だけちょっと直して頂けると！

2021-12-27 05:53 UTC, Hiroshiba commented on src/store/index.ts
> +    async GET_Coninfo_TEXT() {
基本的に文字のケース（大文字小文字など）は周囲と揃えて頂ければ！
（自由度が下がって議論の手間を省けるので）

`Coninfo`はCONTACT INFOMATIONの略語でしょうか。
文脈を知らなくても誰にでも意味が通じるよう、`GET_CONTACT_TEXT`にしておくのはどうでしょう？

2021-12-27 05:53 UTC, Hiroshiba commented on src/type/preload.d.ts
> +  getConinfo_Text(): Promise<string>;
同じくケースを揃えちゃって `getContactText`だと綺麗そうです

2021-12-27 06:39 UTC, Apple-Yuki commented on src/store/index.ts
> +    async GET_Coninfo_TEXT() {
@Hiroshiba 
ConinfoはCONTACT INFOMATIONの略語です。

単にテスト書いて入れてるだけなので、後のコミットで修正します。

2021-12-27 06:51 UTC, Hiroshiba commented on src/store/index.ts
> +    async GET_Coninfo_TEXT() {
テスト用、なるほどです！

githubはプルリクエストが未完成であることを示せるように、draft機能があるのでちょっとdraftにしちゃいますね。
完成したらこちらの方法でdraftを外して頂けると！！

https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review

2022-01-02 12:30 UTC, Apple-Yuki commented
@Hiroshiba
一応組みこんだ感じなんですけど、こういうのはエンジン側から取得してるんですかね？

<img width="912" alt="スクリーンショット 2022-01-02 21 27 27" src="https://user-images.githubusercontent.com/91584669/147875700-d9103aea-2301-478b-84ff-e924db1db6ae.png">

2022-01-02 14:17 UTC, Hiroshiba commented
お問い合わせは使い方などと同じく、エンジンからではなく組み込みでいいかなと思いました。
ただエンジンへのお問合せとかもあるかもなので、将来的にはエンジンからも取得できてもいいかもです。

2022-01-03 09:24 UTC, Apple-Yuki commented
@Hiroshiba ビルド成功しても真っ白なので、どこから読んでるんだろうと思いまして。

（ほぼ、使い方のコピペなんですが。）

2022-01-03 09:50 UTC, Hiroshiba commented
それはコードを読んで頂ければ…！

2022-01-25 17:13 UTC, Hiroshiba approved these changes
LGTM！！

2022-01-25 17:13 UTC, merged