feat: アクセント句単位でまとめてモーラ設定値を変更できるようにした
VOICEVOX/voicevox pull request #623
Opened 2021-12-29 08:26 UTC by qwerty2501

## 内容

Altを押してる間は一緒に上がるように修正した

## 関連 Issue
refs #551

## スクリーンショット・動画など
![accent_phrase-evidence](https://user-images.githubusercontent.com/939468/147641913-3fe15a87-1c60-465a-91dc-f7bd2952c422.gif)

## その他

2021-12-29 16:26 UTC, Hiroshiba commented
良いですね！！！

プレビュー中の値も一緒に変動するとより最高かもと思いました。
ただpreview valueの実装周りはデータ構造の都合上かなり大変だと思うので、やるにしても別PRが良いのかなと感じました。

１点だけ、無声化（pitchの値が0）部分だけ変動しないように修正をお願いしたいです･･･！
（pitch==0は特別な値になっているので変動させたくない感じです）

2021-12-29 18:35 UTC, qwerty2501 commented
pitch0の場合は動かさないように変更しました

2022-01-11 19:36 UTC, Hiroshiba requested changes
良いですね！！！！！！！
実際使ってみたらなかなか便利に感じました。ぜひ実装したいです！！

2022-01-11 19:36 UTC, Hiroshiba commented on public/howtouse.md
> +  - 増減させた値分、同じアクセントの値を増減します
マージする直前に文章をこう変えさせて頂きたいと思ったのでメモ

```suggestion
  - Alt キーを押しながらイントネーションや長さを調整することで、同じアクセント区間内を同時に調整できます
```

2022-01-11 19:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +      if (altKeyFlag.value) {
すごく細かいことなのですが、altが押されていないときのほうが一般っぽいので、そちらが上になるように書くと可読性がちょびっとだけ上がるかもとちょっと思いました！

2022-01-11 19:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +        if (accentPhrases.value !== undefined) {
ここは`accentPhrases.value === undefined`が来ることは無いけど、Optionalを外したいという意図でしょうか👀
もしかしたら派閥なのかもですが、例外であることをコードで伝えるために
```js
if (accentPhrases.value === undefined) raise Error("accentPhrases.value === undefined")
```
とすると良いのかなとちょっと思いました。

2022-01-11 19:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +                  });
なるほど！！

この実装だと、コマンドが複数登録されてしまうので、ctrl+zで一気にやり直すことができなそうです。
一括変更する新しいCOMMAND関数を作ってそちらで修正するのが、一番良い解決だと思います。

が、それはCOMMANDの実装などを把握する必要があって結構大変かもしれません。
実装が難しそうであれば、一旦experimental機能にする手もありそうです。

お手数おかけしちゃいますが、どちらか実装をお願いしたいです･･･！
（個人的には、まあ適当なCOMMANDをコピペして、この処理を移動すれば実装完了な気がしているので、実装しちゃっても良いのかなとちょっと思っています。）

2022-01-11 19:36 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> -
こうすると同時押ししたときに片方が認識されないかもです

2022-01-12 00:45 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> -
shiftで思い出したんですが、スクロール止めることができて何がうれしいんですかね。
shiftでスクロール止めれることはhelpにも書いてないですし、修飾キーが足りないので今の仕様を変更してAlt+Shiftでその文章のすべてのアクセントフレーズの値調整をできるようにしても良いかもと思いました。

2022-01-12 02:52 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> +        if (accentPhrases.value !== undefined) {
確かコンパイルエラーになるから入れた判定だったと思います。
valueがあることが絶対に求められるのでここは確かに例外にしたほうがよさそうですね

2022-01-12 02:53 UTC, qwerty2501 commented
shiftで思い出したんですが、スクロール止めることができて何がうれしいんですかね。
shiftでスクロール止めれることはhelpにも書いてないですし、修飾キーが足りないので今の仕様を変更してAlt+Shiftでその文章のすべてのアクセントフレーズの値調整をできるようにしても良いかもと思いました。

2022-01-12 02:54 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> -
そうなんですか？KeyboardEventの仕様なんですかね。

2022-01-12 08:05 UTC, Hiroshiba commented
実はElectronはデフォルトで、shiftキーを押しながらスクロールすると横方向にスクロールするという操作があります。
shift＋スクロールで横方向にスクロールしているときにスライダーとマウスが重なると、スライダー操作に変わっちゃうんですよね。
なのでshift押してるときはスライダー操作を無視するようになっています。

これたしかに知らないと絶対わからないのでコメント追加しときます。

2022-01-12 08:05 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> -
あ、両方認識されそうだったらこちらでも大丈夫です！！

2022-01-12 14:01 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> -
consoleで出力しつつ確認してみましたが問題なさそうでした

2022-01-12 15:04 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> +                  });
COMMAND内部でaccentPhraseを取得してるところが見当たらなかったのですが、COMMANDの引数としてaccentPhraseを渡しても問題ないでしょうか？
ここでの作法がよくわからずどう実装してよいか迷っています

2022-01-12 15:06 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> +        if (accentPhrases.value !== undefined) {
例外にしました

2022-01-12 15:07 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> +      if (altKeyFlag.value) {
alt押されていないときの方を上に持ってきました

2022-01-12 16:43 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> -
なるほどです、であれば問題ないと思います！

2022-01-13 13:55 UTC, qwerty2501 commented on src/components/AudioDetail.vue
> +                  });
とりあえずコピペしてCOMMAND化しました

2022-01-13 19:57 UTC, Hiroshiba requested changes
良いですね！！！

１つコードの修正のお願いと、１つバグっぽい挙動を見つけたので報告です。

長さ調整する時、母音を操作すると母音だけが調整され、子音を操作すると全部の音素が調整されそうです。
https://user-images.githubusercontent.com/4987327/149400122-5ae8fa96-3ad6-422d-9772-04f589a61a28.mp4
挙動としては、母音でも子音でも全体が調整されるのが良いのかなと感じました。

2022-01-13 19:57 UTC, Hiroshiba commented on src/store/audio.ts
> +        accentPhrase: AccentPhrase;
`audioKey`と`accentPhraseIndex`（とdraft）があれば`accentPhrase`を取得できそうです。
（`draft.audioItems[audioKey].query.accentPhrases[accentPhraseIndex]`でしょうか）

2022-01-14 02:30 UTC, qwerty2501 commented
一緒に上がるようにしてたはずですが、移動させる際におかしくなったかもしれません。修正します

2022-01-14 13:42 UTC, qwerty2501 commented on src/store/audio.ts
> +        accentPhrase: AccentPhrase;
draftから取得するようにしました

2022-01-14 13:42 UTC, qwerty2501 commented
子音が増減しないバグを修正したので今度こそ大丈夫なはずです

2022-01-14 15:03 UTC, Hiroshiba approved these changes
LGTM！！

2022-01-16 15:05 UTC, Hiroshiba commented
マーシしちゃいます！
プレビュー表示する件に関してissueを作成してみました。もしよければぜひ･･･！

- https://github.com/VOICEVOX/voicevox/issues/646

2022-01-16 15:05 UTC, merged