zipファイルをreleaseにアップロードする
VOICEVOX/voicevox pull request #656
Opened 2022-01-22 16:32 UTC by Hiroshiba

## 内容

今までzip版は、artifactからダウンロードしてからgoogle driveにアップロードしていました。
結構煩雑で時間がかかっていたので、zipファイルが2GB未満になったのもあって、releasesにアップロードすることにしたいです。

## 関連 Issue

close #636 
close #638 

## その他

zipファイルの容量は大体1.8GBで、github releasesの制限の2GBギリギリです。
electronのアップデートなどでいつかこの制限を越してしまう可能性はあります。
超してしまったら悲しみつつgoogle driveにアップロードする運用に戻すことにして、2GB未満の間はreleasesにアップロードとしたいと思います。

2022-01-22 16:35 UTC, Hiroshiba commented
テスト用のrelease https://github.com/VOICEVOX/voicevox/releases/tag/check-656

2022-01-23 00:17 UTC, aoirint requested changes
ビルドのテスト実行CIが落ちています。
`upload-distributable-to-release`の`matrix.artifact_name`の項目が不足しています。
新しく追加した`*-zip`を追加する必要があります。

おそらく冗長なので`matrix.os`や`matrix.artifact_name`を消してしまってもいいかもです（includeだけにする）。

2022-01-23 08:15 UTC, Hiroshiba commented
@aoirint 修正しました！！　とりあえずコード量が最小になりそうな方法にしてみました。

それと https://github.com/VOICEVOX/voicevox/issues/638#issuecomment-1019434846 にもあるように、linuxはtargzのが良さそうなのでそうするように修正したいと思います！

2022-01-23 08:35 UTC, Hiroshiba commented
linuxはtargzを作るようにし、actionsを回し始めてみました
https://github.com/VOICEVOX/voicevox/releases/tag/check-b9b46fc7fa43973ea4f565431318aaefc565175d

2022-01-23 10:38 UTC, aoirint approved these changes
LGTM！
targzの対応もありがとうございます！

2022-01-23 11:03 UTC, PickledChair approved these changes
LGTM!

2022-01-23 11:58 UTC, merged