利用規約への同意を
VOICEVOX/voicevox pull request #668
Opened 2022-01-27 10:22 UTC by gobosan

## 内容

## スクリーンショット・動画など
![スクリーンショット](https://user-images.githubusercontent.com/53455523/151338874-2d2adf63-736a-4235-8c72-4b490ccd6ddd.png)

2022-01-27 20:55 UTC, Hiroshiba commented
PRありがとうございます！！
利用規約の同意はインストーラーの方が良いかなと思ったのですが、zip版もあるので初回起動時も良いなと思いました…！

2022-02-01 13:58 UTC, Hiroshiba requested changes
@gobosan お待たせしました！！
だいたい良さそうなのですが、１点お聞きしてみました。

2022-02-01 13:58 UTC, Hiroshiba commented on src/views/Home.vue
> +    });
一番最初に表示されたほうが良いかもと思いました

2022-02-01 13:58 UTC, Hiroshiba commented on src/components/AcceptTermsDialog.vue
> +            />
同意しないボタンは表示しないほうが良いのかなと思いました。
この辺りちょっとよく知らないので、どう思われるか伺いたいかもです･･･！

2022-02-01 14:42 UTC, gobosan commented on src/views/Home.vue
> +    });
利用規約 → デフォルトスタイル → GTM の順番に表示されるようにしました

2022-02-01 16:13 UTC, gobosan commented on src/components/AcceptTermsDialog.vue
> +            />
同意しないボタンの必要性は利用規約の内容によって変わってきます。

多くのソフトウェアでは、利用規約に同意しないとソフトウェアを利用できないことになっているので、ユーザーには同意の選択を求める必要があり、同意しないボタンは必要です。

現状の利用規約にはそのような記述がないので、ユーザーに同意の選択を求める必要もなく、同意しないボタンは必要ありません。

個人的には利用規約に同意したとみなす条件についての条項を追加して、同意しないボタンを表示することをお勧めしますが、いかがでしょうか。（少し調べてみましたが、現状の利用規約は定型約款[*]として有効ではないので法的効力を持たないと解釈することもできると思います。どのみち法的効力があるか疑わしいのは良くないです。）

> 同意しないボタンは表示しないほうが良いのかなと思いました。

必要ありませんが表示したほうが良いと思います。

[*][定型約款の解説](https://masslaw.jp/columns/19)

（ [民法](https://elaws.e-gov.go.jp/document?lawid=129AC0000000089) ref 第五百四十八条の二 ~ 第五百四十八条の四 )

2022-02-01 22:08 UTC, Hiroshiba commented on src/components/AcceptTermsDialog.vue
> +            />
なるほどです！！

法律のことはよくわからないのですが、必要であれば付け足したいと思います。
どのような文面であれば問題なさそうか、ご存知でしたらお伺いしたいです（法律に詳しくなく･･･。）

現状だと、同意しないボタンを押してもソフトウェアが利用できてしまいます。
これはさすがに良くなさそうなので、同意しなければソフトウェアを閉じる挙動を考えましたが、これはOS依存やエンジンまわりもあってちょっと面倒かもしれません。
だったら同意しないボタンを表示しないのが手っ取り早いのかなーと思って提案した感じです。

2022-02-02 09:34 UTC, gobosan commented on src/components/AcceptTermsDialog.vue
> +            />
「ユーザーは、本規約の定めに従って VOICEVOX を使用しなければなりません。ユーザーは、本規約に同意をしない限り VOICEVOX を使用できません。」
などと書くと利用規約の「みなし合意」が取れるのではないでしょうか。

上記のように書くと、同意しないボタンを押した状態でも VOICEVOX の利用により規約に合意したとみなすことができるので、同意しないボタンを押してもソフトウェアが利用できることに問題はありません。

2022-02-02 18:14 UTC, Hiroshiba commented on src/components/AcceptTermsDialog.vue
> +            />
なるほどです！！イメージが湧いてきました。

利用規約周りに関していろいろ調べてみました。あらためて、一番最初に表示すべきだなと感じました。
そして訴訟の件数がそもそも少なく、まあ考えすぎなくてもいいのかなと思いました。

みなし合意に関してですが、そもそも表示していれば良さそうでした。
https://www.businesslawyers.jp/practices/1159

↓引用です。

> 以下のいずれか要件を満たせば
> 定型約款準備者があらかじめその定型約款を契約の内容とする旨を相手方に表示していたとき（2号表示）

また、利用規約をみてなくても合意したとみなすものは逆にやめたほうが良いという意見も見かけました。
https://www.businesslawyers.jp/articles/940

↓引用です。

> ユーザーの利用開始をもって利用規約に同意したものとみなす趣旨の条項は、削除しておいたほうが無難である。

たぶん、頂いたプルリクエストの実装のように、一番最初に利用規約を表示するのが最も大事で、それ以外のことはどちらでも良いのかなと感じました。

同意しないボタンUIは、同意を迂回して利用しているとユーザーに誤解を与える設計になってしまいそうです。
法律の面というよりUI的な面で、間違いうる設計は避けた方が良さそうですが、どうでしょうか。

ただまあ、「同意する」ボタンだけが表示されるのもなんか微妙な気がします。
法律的には多分「次へ」ボタンで十分だと思いますが、どうでしょう。
もしくは「同意して次へ」だと少しだけハードル下がるかもですが、うーん。。

2022-02-03 08:58 UTC, gobosan commented on src/components/AcceptTermsDialog.vue
> +            />
UI を改善しました。「同意せずに終了」で Window をクローズします。

![](https://user-images.githubusercontent.com/53455523/152307658-a48675e4-70ed-4268-acf7-eda76a1d2233.png)

2号表示について、現状の利用規約に、定型約款を契約の内容とする記述がないので、表示のみでは不十分かと思いました。

> また、利用規約をみてなくても合意したとみなすものは逆にやめたほうが良いという意見も見かけました。
> https://www.businesslawyers.jp/articles/940

この記事は Web上の特殊な事例を挙げているので、参考にならないと思います…

2022-02-05 09:36 UTC, Hiroshiba commented on src/components/AcceptTermsDialog.vue
> +            />
ありがとうございます！！

法律のことを考えるなら、「同意して閉じる」ボタンを押したとき必ず閉じられる挙動をしないと法律の穴ができてしまいそうなのですが、このボタンが押されると必ず閉じられることがわかるテストを書くのが大変なのでコスパが良くないのかなと思っています。

正直なところ、VOICEVOXは裁判を起こせるようなしっかりした体制は現状なく、利用規約の表示はどちらかというとユーザーに規約を知ってもらうのが主目的になると思っています。
マージさせて頂いたあとで、総合的に判断して最も良さそうなUIにできればと思います･･･！

2022-02-05 09:37 UTC, Hiroshiba commented
コンフリクトを解消してみました。
テストが通り次第マージの予定です

2022-02-05 09:37 UTC, Hiroshiba approved these changes

2022-02-05 09:56 UTC, gobosan commented on src/components/AcceptTermsDialog.vue
> +            />
わかりました。長い時間お付き合い頂きありがとうございました！

2022-02-05 10:19 UTC, Hiroshiba commented on src/components/AcceptTermsDialog.vue
> +            />
こちらこそありがとうございます！！
またよければプルリクエストお待ちしています…！

2022-02-05 10:19 UTC, Hiroshiba approved these changes
LGTM！！

2022-02-05 10:20 UTC, merged