ヘルプでアップデートを確認できるようにする
VOICEVOX/voicevox pull request #690
Opened 2022-02-06 08:36 UTC by gobosan

## 内容

ソフトウェアのバージョン と GitHub の Release の最新バージョンを比較して、ヘルプでアップデートを確認します。

要望？がありました ↓

https://twitter.com/teruteru129/status/1459078104693886978

## 関連 PR

https://github.com/VOICEVOX/voicevox/pull/543#issuecomment-1013681536

## スクリーンショット

最新版を使っているとき

![](https://user-images.githubusercontent.com/53455523/152673244-8a8e56f9-8202-45bd-acae-f7f9eb5847a2.png)

古いバージョンを使っているとき

![](https://user-images.githubusercontent.com/53455523/152673251-cd458444-2941-4eca-b593-7041ac77551c.png)

2022-02-06 11:09 UTC, Hiroshiba commented on src/components/UpdateInfo.vue
> +        obj.map((item: { prerelease: boolean; tag_name: string }) => {
obj.findを使うと綺麗に書けるかもです…！

2022-02-06 11:27 UTC, gobosan commented on src/components/UpdateInfo.vue
> +        obj.map((item: { prerelease: boolean; tag_name: string }) => {
修正しました…！

2022-02-06 17:28 UTC, Hiroshiba requested changes
修正をお願いしたい箇所がありました・・・！

（メモです）
内容的に↓とかぶりそうですが、どちらもあって良い機能だなと思うので、どちらもマージできればと思っています

- https://github.com/VOICEVOX/voicevox/pull/543

2022-02-06 17:28 UTC, Hiroshiba commented on src/components/UpdateInfo.vue
> +        });
`{}`で囲うとdictが返ってしまうので、なしにしないとバグりそうです･･･！
```suggestion
        obj.find((item: { prerelease: boolean }) => 
          item.prerelease === false;
        );
```

2022-02-06 17:28 UTC, Hiroshiba commented on src/components/UpdateInfo.vue
> +      const isUpdateAvailable = currentVersion.value !== latestVersion.value;
2.0.0をインストールしているときに1.3.1がリリースされた、みたいなことが起こりそうです。
（メジャーバージョンアップ後に、過去のバージョンにバグフィックスを入れたときとか）

一旦それを許容しつつFIXMEコメントを残すか、別で作られている`baseVersionIsLow`関数を使い回すのをお願いできれば･･･！
https://github.com/VOICEVOX/voicevox/blob/0023b8d7291b94c363cd79bdcd6f263809a3d3da/src/store/project.ts#L415

2022-02-07 08:18 UTC, raa0121 commented
#543 と被る機能になりますね
@Hiroshiba 私の手が遅いせいなんですが、どうしましょう。

2022-02-07 10:20 UTC, Hiroshiba commented
@raa0121 上のコメントにある通り、どちらもマージできればと思っています…！
（アプデ通知は一度見たら再度見れないので）

2022-02-07 12:59 UTC, gobosan commented on src/components/UpdateInfo.vue
> +        });
修正しました！

2022-02-07 13:00 UTC, gobosan commented on src/components/UpdateInfo.vue
> +      const isUpdateAvailable = currentVersion.value !== latestVersion.value;
`baseVersionIsLow`関数を使い回してバージョンの比較をするようにしました！

2022-02-07 13:08 UTC, gobosan commented
@raa0121 
https://github.com/VOICEVOX/voicevox/pull/543#issuecomment-1013681536 の機能と被ってしまっているのは私の確認不足でした。
ご迷惑をおかけして申し訳ありません。

2022-02-07 17:23 UTC, y-chan approved these changes
LGTMです！
コード的に問題は見受けられませんでした
ただ、我々としては全てのバイナリのビルドが完了し、HPの更新をするまではPre Releaseにし、HPの更新等のリリース作業が完了してからReleaseに変更するという手順に変わる(変えなければならない)点に留意する必要はありそうです。

2022-02-07 18:42 UTC, Hiroshiba approved these changes
LGTM！！

リリースは気をつけなきゃですね･･･！
リリース手順書かねば。。。

2022-02-07 18:42 UTC, Hiroshiba commented on src/components/UpdateInfo.vue
> +        currentVersion.value = obj.version;
あ、ここエラーをthrowしたほうが良いかもです･･･！
（まあどちらにせよ下にundefinedが渡ってエラーにはなるのですが、きれいかなーと）

2022-02-08 09:42 UTC, gobosan commented on src/components/UpdateInfo.vue
> +        currentVersion.value = obj.version;
修正しました！

2022-02-08 23:59 UTC, Hiroshiba approved these changes

2022-02-08 23:59 UTC, Hiroshiba commented
マージします･･･！

2022-02-08 23:59 UTC, merged

2022-02-09 00:22 UTC, Hiroshiba commented
@gobosan さん
ユーザーさんから要望の多い機能をまとめてみました！参考になりますと幸いです･･･！

- https://github.com/VOICEVOX/voicevox_project/issues/8