読点を含んだ読み仮名修正に対応
VOICEVOX/voicevox pull request #692
Opened 2022-02-06 12:24 UTC by Yosshi999

## 内容
読み仮名の修正に「、」や「？、」を含んでいるときでも `is_kana=true` としての修正を可能にする

## 関連 Issue
close #691

2022-02-06 18:10 UTC, Hiroshiba requested changes
良さそうです！
１点エラーを見つけました･･･！

2022-02-06 18:10 UTC, Hiroshiba commented on src/store/audio.ts
> +        );
ここで、１文字だったときに`'は`みたいになって後続の`FETCH_ACCENT_PHRASES`がエラーになりました

2022-02-06 23:18 UTC, Yosshi999 commented on src/store/audio.ts
> +        );
あー `[^？、]$` がちょっとおかしいですね
後読みにへんこうします

2022-02-07 17:09 UTC, Hiroshiba commented
@Segu-g さん、 @y-chan さん、よかったらレビュー頂けると･･･！

2022-02-07 17:17 UTC, y-chan approved these changes
LGTMです!
特に問題は見受けられませんでした...!

2022-02-12 19:30 UTC, Segu-g approved these changes
レビューが遅くなってしまい申し訳ありません！
LGTM!

2022-02-13 05:42 UTC, merged