辞書優先度UIのために
VOICEVOX/voicevox pull request #846
Opened 2022-06-26 10:47 UTC by y-chan

## 内容

## 関連 Issue

## スクリーンショット・動画など

## その他

2022-06-26 15:34 UTC, Hiroshiba commented
比較してみた感じ、結構変わってるなと感じました！
![image](https://user-images.githubusercontent.com/4987327/175820673-41c5062c-337a-408b-b140-0304e16b8da5.png)

判断が難しいですが、見た目の変動はソフトウェアの違和感につながって、ものづくりに影響を及ぼしかねないなと思いました。
なので、極力見た目は振動させないでおきたい感じがあります。

見て目で大きく変わっているのはスライダー幅と、アクセント句のとこのスライダーの下の隙間かなぁ･･･

2022-06-26 15:51 UTC, Hiroshiba commented
いろいろ調べたけど、少なくとも気になったのはそこだけでした･･･！

2022-06-26 16:27 UTC, Hiroshiba requested changes
あ、たぶんこうです！

2022-06-26 16:27 UTC, Hiroshiba commented on src/components/AudioParameter.vue
> +      trackSize="3px"
```suggestion
      trackSize="2.5px"
```

2022-07-16 16:30 UTC, y-chan commented
遅くなりました、Suggestionをコミットしました
レビューよろしくお願いします！

2022-07-16 16:48 UTC, Hiroshiba commented
ありがとうございます！！あとアクセントスライダーの下のとこですね！
･･･まあ正直修正めんどくさいと思うので、いろいろ試してプルリクエスト出してみました！

- https://github.com/y-chan/voicevox/pull/2

2022-07-16 16:53 UTC, y-chan commented
おっと、忘れていました...マージしました、ありがとうございます！

2022-07-16 17:02 UTC, Hiroshiba approved these changes
LGTM！！

マージします！

2022-07-16 17:03 UTC, merged