複数エンジン対応: すべてのエンジンからキャラクター情報を取得する
VOICEVOX/voicevox pull request #883
Opened 2022-08-03 16:22 UTC by Hiroshiba

## 内容

このPRでは、エディタ起動時にすべてのエンジンからキャラクター情報を取得するようにします。

その影響で変更される箇所の一覧です。

- AudioCellのキャラクター一覧
  - アイコン・キャラクター名の表示
  - 音声合成
  - 立ち絵・キャラクター名の表示
- デフォルトスタイル
- キャラクター並び替え・試聴
- キャラクターライセンスの表示
- プロジェクトファイルのマイグレーション

### 動作確認手順

[COEIROINK 1.0.1のwindowsビルド](https://github.com/shirowanisan/voicevox_engine/releases/tag/c1.0.1+v0.10.4)をダウンロードした後、`.env`をこんな感じにして起動してください。
```ini
NODE_ENV=development
DEFAULT_ENGINE_INFOS=`[
    {
        "uuid": "074fc39e-678b-4c13-8916-ffca8d505d1d",
        "executionEnabled": true,
        "executionFilePath": "C:/path/to/voicevox_engine/run.exe",
        "host": "http://127.0.0.1:50021"
    },
    {
        "uuid": "d9212658-962f-4918-80b2-310b7de70c41",
        "executionEnabled": true,
        "executionFilePath": "C:/path/to/coeiroink_engine/run.exe",
        "host": "http://127.0.0.1:50031"
    }
]`
VUE_APP_GTM_CONTAINER_ID=GTM-DUMMY
```

## 関連 Issue

## スクリーンショット・動画など

## その他

このPRは、[こちらのPR](https://github.com/VOICEVOX/voicevox/pull/743)の置き換えになります。
相当な修正範囲にもかかわらず良い感じに動いているのは、僕ではなく @aoirint さんの努力によるものです。本当にありがとうございます。

2022-08-03 16:31 UTC, Hiroshiba commented
このPRがマージできれば、いろんなタスクがパラレルに実行できるのではと考えています。
タスクはこちらで一覧にしてみました。 https://github.com/VOICEVOX/voicevox_project/issues/2#issuecomment-1204194876

かなりいろんな箇所に変更があるPRですが、@Segu-g さん・ @y-chan さん・@shirowanisan さん辺りの方にレビューをお願いできるととても心強いです･･･！！
（僕自身もレビューしたいと思います）

2022-08-03 17:03 UTC, Hiroshiba reviewed
かなり読みやすかった！！

レビュワーの方向けメモ：Hide whitespaceおすすめです
![image](https://user-images.githubusercontent.com/4987327/182667020-18e23125-5c60-4b9d-bdef-2a8815e5be17.png)

2022-08-03 17:03 UTC, Hiroshiba commented on src/views/Home.vue
> +          throw new Error(`CharacterInfos not loaded for engine ${engineId}`);
flattenEngineInfosで良いかも

2022-08-04 16:14 UTC, Hiroshiba commented on src/store/audio.ts
> +      );
すみません！こちら中に入っているのはblobだったので超軽量でした･･･！！

2022-08-04 16:18 UTC, Hiroshiba commented on src/store/audio.ts
> +        throw new Error("assert engineId !== undefined");
エンジン起動前に作られるaudio itemはundefinedになるので、必要そう。

2022-08-04 16:29 UTC, Hiroshiba commented on src/store/audio.ts
> +    throw new Error("assert styleName !== undefined");
しました！

2022-08-04 16:44 UTC, Hiroshiba commented on src/store/audio.ts
> +        // select default style if (engineId, styleId) === (undefined, undefined)
修正！

2022-08-04 16:44 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +      );
ここ以外複雑なとこはなかったので多分大丈夫！

2022-08-04 16:48 UTC, Hiroshiba commented
気になったところは修正してみました。よろしくお願いします･･････！！！！

2022-08-15 16:38 UTC, Hiroshiba commented
@aoirint さん・@Segu-g さん・@shirowanisan さん
すみません、レビューをお願いできると･････！！
approveとまではいかなくても、ざっと操作してみて問題がなさそうだったみたいな報告でも大丈夫なので･･･！！

2022-08-16 13:38 UTC, shirowanisan commented
レビュー遅れていてすみません。ざくっと自分のMacでローカルで動かしてみた感じでは、問題なさそうでした。
もうちょっとだけコードも見たいと思っているので、少しお時間いただけると幸いです。

2022-08-17 11:02 UTC, Hiroshiba commented
ありがとうございます、とても助かります！！！

2022-08-20 16:21 UTC, Segu-g requested changes
コードが大きいので全部見れているか不安ですが一応見てみました。
`userOrderedCharacterInfos`や`defaultStyleIDs`などにおけるキャラクター重複時の操作が怪しくなりそうに感じました。恐らくまだCharacterが複数のエンジンで重複した際のUIもないので、そうであれば別PRで作成するのも手だと思います。

2022-08-20 16:21 UTC, Segu-g commented on src/components/AudioCell.vue
> +                    characterInfo.metas.speakerUuid,
SpeakerUuidの指定だとあるキャラクターが複数のエンジンで使われている時、順番が先のエンジンが必ず選択されるようになります。

2022-08-21 02:52 UTC, shirowanisan commented
仕様なら問題ないですが、過去プロジェクトファイルが`Every audioItem should have a "engineId" attribute.`により、互換がなくなりそうです。
また、互換をなくすならば、これを機にプロジェクトファイルにキャラクターUUIDを含めた方が良いように思いました
```
{"appVersion":"999.999.999","audioKeys":["7aec337d-3e3d-4bc1-b816-c0bf7b36fac7"],"audioItems":{"7aec337d-3e3d-4bc1-b816-c0bf7b36fac7":{"text":"今日はいい天気ですね","engineId":"d9212658-962f-4918-80b2-310b7de70c41","styleId":30,"query":{"accentPhrases":[{"moras":[{"text":"キョ","consonant":"ky","consonantLength":0,"vowel":"o","vowelLength":0,"pitch":0},{"text":"オ","vowel":"o","vowelLength":0,"pitch":0},{"text":"ワ","consonant":"w","consonantLength":0,"vowel":"a","vowelLength":0,"pitch":0}],"accent":1,"isInterrogative":false},{"moras":[{"text":"イ","vowel":"i","vowelLength":0,"pitch":0},{"text":"イ","vowel":"i","vowelLength":0,"pitch":0}],"accent":1,"isInterrogative":false},{"moras":[{"text":"テ","consonant":"t","consonantLength":0,"vowel":"e","vowelLength":0,"pitch":0},{"text":"ン","vowel":"N","vowelLength":0,"pitch":0},{"text":"キ","consonant":"k","consonantLength":0,"vowel":"i","vowelLength":0,"pitch":0},{"text":"デ","consonant":"d","consonantLength":0,"vowel":"e","vowelLength":0,"pitch":0},{"text":"ス","consonant":"s","consonantLength":0,"vowel":"U","vowelLength":0,"pitch":0},{"text":"ネ","consonant":"n","consonantLength":0,"vowel":"e","vowelLength":0,"pitch":0}],"accent":1,"isInterrogative":false}],"speedScale":1,"pitchScale":0,"intonationScale":1,"volumeScale":1,"prePhonemeLength":0.1,"postPhonemeLength":0.1,"outputSamplingRate":44100,"outputStereo":false,"kana":""}}}}
```

2022-08-21 02:53 UTC, shirowanisan commented
起動しての動作確認は、一通りの操作を行いましたが、問題なさそうでした。

コードは全体を見ましたが、type script初心者の自分には、少しちゃんとしたレビューは難しそうでした。
すみませんが「ざっくり見た形では問題なさそう」という形のレビューとさせていただければ幸いです。

2022-08-21 03:13 UTC, Segu-g commented on src/store/project.ts
> +
0.14かも

2022-08-21 03:17 UTC, Segu-g commented
> 仕様なら問題ないですが、過去プロジェクトファイルが`Every audioItem should have a "engineId" attribute.`により、互換がなくなりそうです。 また、互換をなくすならば、これを機にプロジェクトファイルにキャラクターUUIDを含めた方が良いように思いました
> 
> ```
> {"appVersion":"999.999.999","audioKeys":["7aec337d-3e3d-4bc1-b816-c0bf7b36fac7"],"audioItems":{"7aec337d-3e3d-4bc1-b816-c0bf7b36fac7":{"text":"今日はいい天気ですね","engineId":"d9212658-962f-4918-80b2-310b7de70c41","styleId":30,"query":{"accentPhrases":[{"moras":[{"text":"キョ","consonant":"ky","consonantLength":0,"vowel":"o","vowelLength":0,"pitch":0},{"text":"オ","vowel":"o","vowelLength":0,"pitch":0},{"text":"ワ","consonant":"w","consonantLength":0,"vowel":"a","vowelLength":0,"pitch":0}],"accent":1,"isInterrogative":false},{"moras":[{"text":"イ","vowel":"i","vowelLength":0,"pitch":0},{"text":"イ","vowel":"i","vowelLength":0,"pitch":0}],"accent":1,"isInterrogative":false},{"moras":[{"text":"テ","consonant":"t","consonantLength":0,"vowel":"e","vowelLength":0,"pitch":0},{"text":"ン","vowel":"N","vowelLength":0,"pitch":0},{"text":"キ","consonant":"k","consonantLength":0,"vowel":"i","vowelLength":0,"pitch":0},{"text":"デ","consonant":"d","consonantLength":0,"vowel":"e","vowelLength":0,"pitch":0},{"text":"ス","consonant":"s","consonantLength":0,"vowel":"U","vowelLength":0,"pitch":0},{"text":"ネ","consonant":"n","consonantLength":0,"vowel":"e","vowelLength":0,"pitch":0}],"accent":1,"isInterrogative":false}],"speedScale":1,"pitchScale":0,"intonationScale":1,"volumeScale":1,"prePhonemeLength":0.1,"postPhonemeLength":0.1,"outputSamplingRate":44100,"outputStereo":false,"kana":""}}}}
> ```

このプロジェクトファイルは開発版で`appVersion: 999.999.999`になっていますが実際の製品版のプロジェクトファイルでは`appVersion`が`0.14`未満となるはずなので上のマイグレーション処理でエンジンがVOICEVOX版のものに変更されるはずです。

2022-08-21 05:21 UTC, shirowanisan commented
> 実際の製品版のプロジェクトファイルではappVersionが0.14未満となるはずなので上のマイグレーション処理でエンジンがVOICEVOX版のものに変更されるはずです。

すみません、試してみたら確かにそうでした！ありがとうございます...!!!

2022-08-21 16:16 UTC, Hiroshiba commented on src/store/audio.ts
> +        engineId?: string;
ありがとうございます、修正しました！

2022-08-21 16:29 UTC, Hiroshiba commented on src/components/AudioCell.vue
> +                    characterInfo.metas.speakerUuid,
本当ですね･･･
とりあえずこのPRではいったんスルーすることにして、FIXMEコメントを残しつつ、タスクリストに`同一キャラが複数エンジンにまたがる場合のFIXME解消`を追加しました！

2022-08-21 16:30 UTC, Hiroshiba commented on src/store/project.ts
> +
たしかに！！　ありがとうございます！！

2022-08-21 16:55 UTC, Hiroshiba commented
@shirowanisan 

> また、互換をなくすならば、これを機にプロジェクトファイルにキャラクターUUIDを含めた方が良いように思いました

なるほどです！！たしかに、speakerIdを保存しておくようにすると、将来的に良い気がしました。
いったんこのPRではFIXMEコメントを残すだけにしても良いでしょうか。
また、タスクリストに`AudioItemにSpeakerIdを追加する`を追加し、[engineId, speakerId, styleIdで声を一意に定めようとする方針](https://github.com/VOICEVOX/voicevox/pull/883/files#diff-1c71ebca7224819a09af1749674e6d111d399deb61105fba821366d7718352e7R13-R14)を追記しました！

いったんこんな感じでどうでしょうか 👀

2022-08-21 16:57 UTC, Hiroshiba commented
レビューありがとうございます、とても助かります！！
指摘いただいた箇所を修正or FIXME コメントを追記してみました。
また見て頂けるととても心強いです 🙇‍♂️

2022-08-22 02:59 UTC, shirowanisan commented
@Hiroshiba 
> なるほどです！！たしかに、speakerIdを保存しておくようにすると、将来的に良い気がしました。

設計方針確認しました。自分からはLGTMです…!!!

2022-08-22 19:14 UTC, Hiroshiba commented
@Segu-g 
styleUuidが良い旨、おっしゃるとおりだと思います。
方針としては、Uuidがあるべき姿ということにして、そこを目指せると嬉しそうです。
（ということを設計方針.mdに追記しました!
）

2022-08-22 19:15 UTC, Hiroshiba commented
@aoirint さん
おふたりからLGTM頂いたのでマージしたいなと考えているのですが、今レビュー中だったりされますか･･･？
（いったんマージしても大丈夫でしょうか👀）

2022-08-22 23:07 UTC, aoirint commented
コード量が多いのでレビューコメント保留のままレビュー中でしたが、

- 複数のエンジンに同一のspeakerUuidを持つキャラクターがいる場合の検索処理・assertionメッセージ内容と処理の不一致
    - https://github.com/VOICEVOX/voicevox/pull/883#discussion_r950712965
- プロジェクトファイルマイグレーションのバージョンを`0.14`に変更
    - https://github.com/VOICEVOX/voicevox/pull/883#discussion_r950779877

の点についてはすでに指摘と方針が決まったようなのでよさそうです！

2022-08-22 23:07 UTC, aoirint commented
> [engineId, speakerId, styleIdで声を一意に定めようとする方針](https://github.com/VOICEVOX/voicevox/pull/883/files#diff-1c71ebca7224819a09af1749674e6d111d399deb61105fba821366d7718352e7R13-R14)

おおむね同意ですが、プロジェクトファイルが声を一意に定める上で、コアのバージョンによる音声の違いも考慮できるとうれしいです。
https://github.com/VOICEVOX/voicevox/pull/883#pullrequestreview-1080686479 の`{ engineId, speakerUUID, styleUUID, styleVersion?}`と`styleVersion`を（オプショナルでも）保持しておく方法に同意です（styleVersionが現状のVOICEVOXにおいてコアのバージョンという意味であれば）。
古いコアのバージョンを持つプロジェクトファイルが新しいエディタで開かれたときにどうするか、古いコアを新しいエディタでも使えるように整備するのか、というような問題が発生して難しそうですが、少しずつ機能追加する形でも考慮できないかなと思いました！

2022-08-22 23:26 UTC, aoirint commented
キャラクター並び替えUIについて、現状でも、設定ファイルを維持したままVOICEVOXをダウングレードした場合に、キャラクター並び替えUIにエラーが表示されるという現象があります。

- （同じ原因かはわからないけれど）このようなエラーの見た目：<https://twitter.com/k896951/status/1546175242111856641>

並び替えリストに登録済みのキャラクターをエディタが認識していない場合にエラーになる点、処理を追加するタスクを設けておくとよさそうです！

- <https://github.com/VOICEVOX/voicevox_project/issues/2#issuecomment-1204194876>

あまり互換性面で想定していない操作のダウングレードより、カジュアルにキャラクターの増減が起き得るようになりそうなので、問題になることを予想しています。

ちょっと古いログなので行数がずれていそうですが、このようなエラー：

```
[01:14:09.781] [error] TypeError: Cannot read properties of undefined (reading 'metas')
    at http://localhost:8080/js/webpack:/src/components/CharacterOrderDialog.vue?5229:106:39
    at Proxy.find (<anonymous>)
    at http://localhost:8080/js/webpack:/src/components/CharacterOrderDialog.vue?5229:104:37
    at Proxy.filter (<anonymous>)
    at _callee$ (http://localhost:8080/js/webpack:/src/components/CharacterOrderDialog.vue?5229:102:66)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:293:1)
    at Generator.next (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:118:1)
    at fulfilled (http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:71:42)
```

2022-08-22 23:31 UTC, aoirint approved these changes
LGTM！！　PR引き継いでいただいてありがとうございます！

2022-08-22 23:31 UTC, aoirint commented on src/views/Home.vue
> +  CharacterInfo,
未使用importかも？

2022-08-22 23:34 UTC, aoirint commented on src/views/Home.vue
> +  CharacterInfo,
```suggestion
```

2022-08-23 16:36 UTC, Hiroshiba commented
> styleVersion

僕もバージョンを持たせるのは賛成です！
複数エンジン対応時はマストじゃないなと思っていますが、せっかくなのでタスクリストに追加してみようと思います！

名称をどうすべきかちょっと悩みそうです。
ほしいのは音声バージョンであり、実装がstyleのバージョンになっている形で、「version」として持つのも良いのかなとか･･･。
（なんのバージョンかわかりづらいのが難しいですが･･･。）

2022-08-23 16:44 UTC, Hiroshiba commented on src/views/Home.vue
> +  CharacterInfo,
修正しました！！

2022-08-23 16:45 UTC, Hiroshiba commented
> 並び替えリストに登録済みのキャラクターをエディタが認識していない場合にエラーになる

こちら、↓にissueを作成し、それをタスクリストからも参照する感じにしてみました！

- https://github.com/VOICEVOX/voicevox/issues/912

2022-08-23 16:57 UTC, Hiroshiba commented
マージします！！　レビューありがとうございました！！！
そして複数エンジンの大量のタスクを解禁し、実装PRを大量に募集し始めたいと思います･･･！！！

2022-08-23 16:57 UTC, merged