複数エンジン対応：Engine manifestによるUI無効化
VOICEVOX/voicevox pull request #919
Opened 2022-09-03 10:18 UTC by sevenc-nanashi

## 内容

Engine manifestのsupported_featuresによって一部UI（音高やイントネーションなど）を無効化するようにします。

## 関連 Issue

- ref: voicevox/voicevox_project#2 ：エンジンの機能による違い
- ref: VOICEVOX/voicevox_engine#362

## スクリーンショット・動画など

（なし）

## その他

（なし）

2022-09-03 12:05 UTC, sevenc-nanashi commented
openapi.jsonが古くて動けない状況です、更新PRは更新PRで作った方がよさそう。
（更新方法は判ってない）

2022-09-03 12:05 UTC, Hiroshiba commented
あ！　ちょうど今そのPRを作っているところです･･･！

2022-09-03 12:08 UTC, Hiroshiba commented
@sevenc-nanashi openapi更新しました！

2022-09-03 14:29 UTC, sevenc-nanashi commented
![image](https://user-images.githubusercontent.com/59691627/188274876-9adc1b3e-981b-4293-a255-497f6ad566d5.png)

現在の進捗です

2022-09-03 21:03 UTC, sevenc-nanashi commented
![image](https://user-images.githubusercontent.com/59691627/188287514-6d42fb24-8d60-4f99-ba3c-73930a39d225.png)

イントネーション、長さの無効化も実装できました。
項目内のコンポーネントのdisableをいじってもよかったんですけど、それだとどこかでの腰が発生しそうだったので項目ごと無効化しています。
項目の選択中にその機能をサポートしていない別のエンジンに切り替わった場合（例：イントネーション選択中にadjust_mora_pitchをサポートしていないエンジンに切り替わる）は自動的にアクセントに移動するようになっているはずですが、supported_featuresを実装したエンジンがまだVoicevox Engine以外に存在していないためまだデバッグできていないです。

2022-09-03 21:09 UTC, sevenc-nanashi commented
`interrogative_upspeak`はまだUI側に何もなさそうだったので飛ばします。

2022-09-04 04:59 UTC, Hiroshiba commented
> upported_featuresを実装したエンジンがまだVoicevox Engine以外に存在していないためまだデバッグできていないです。

あ、ちょっと面倒かもなのですが、エンジンをディレクトリごとコピーしちゃって、片方のエンジンの`engine_manifest.json`を書き換えちゃうという手があるかもです！

2022-09-04 06:56 UTC, sevenc-nanashi commented
それやろうとしたんですけど、キャラがかぶるんですよね…
uuid、フォルダ名を変えて試したんですけど、多分埋め込まれてるmetas.jsonのデータが残って500返されました

2022-09-04 06:59 UTC, Hiroshiba commented
あーーーそうか････。ちょっとCOEIROINKさんにお願いしてみます！

2022-09-04 07:03 UTC, Hiroshiba commented
いや、COEIROINK側にもある機能だとデバッグできないか･･･。

2022-09-04 09:38 UTC, sevenc-nanashi commented
coeiroink側を全有効、開発版ボイボエンジン側を無効にすればよさそう。

2022-09-06 17:32 UTC, Hiroshiba commented
すみません、もしかしてこちらのPRはすでに完成されてたりしますか･･･？

2022-09-06 21:24 UTC, sevenc-nanashi commented
あーっと、Coeiroinkで試そうとしたら/engine_manifestがなくて困ってる感じです。
今朝、間にflaskか何かで中継鯖立ててengine_manifestだけ拾うというのを思いついたのでやってます

2022-09-07 02:48 UTC, Hiroshiba commented
あ、なるほどです！もう完了してたらレビューおまたせしちゃってるなと思ったので確認した次第でした！
ふと思ったのですが、愚直ですが、VOICEVOX側のmanifest.jsonを変えて起動したらデバッグできるかも･･･？

2022-09-07 07:36 UTC, sevenc-nanashi commented
デバッグできてないのは「イントネーション欄表示中にイントネーションをサポートしていないエンジンに切り替わった時の自動タブ切り替え」なので（AudioDetailの370行目あたり）、それ以外はほとんど完成してます（学校があって上の中継の案がまだ試せてない）

2022-09-07 08:21 UTC, Hiroshiba commented
> イントネーション欄表示中にイントネーションをサポートしていないエンジンに切り替わった時の自動タブ切り替え

あーなるほど！！！

2022-09-07 11:59 UTC, sevenc-nanashi commented
https://user-images.githubusercontent.com/59691627/188873190-f8366fcf-a2fa-4bc5-96f2-852909a4c27e.mp4


確認出来ました！

2022-09-07 15:23 UTC, Hiroshiba commented
@raa0121 さんもよかったらレビューお願いできると･･･！

2022-09-07 21:38 UTC, sevenc-nanashi commented
> 動画をみてるとキャラクターしてぐるぐるが表示し終わってから「アクセント」に移動するまでちょっとタイムラグがありそうなのですが、こちらの理由はなんでしょう 👀

アクセント計算に時間がかかってるっぽいです。
適当に立てた中継鯖なのでその分のオーバーヘッドもあるのかな

2022-09-08 05:41 UTC, Hiroshiba commented
おお、なるほどです！であれば仕方ないですね…！

2022-09-08 14:05 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +    );
`engineManifest`は使わないので、２つ一緒にして`supportedFeatures`だけ返す、みたいなコードもありかも。
（今のままでも全く問題ないです！）

2022-09-08 14:05 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +          opacity: `${speedScaleSlider.qSliderProps.disable.value ? 0.5 : 1}`,
spanに対して有効なのかわからないのですが、quasarに`disabled`クラスがあるのでもしかしたら使えるかもです。
https://quasar.dev/style/visibility

2022-09-08 14:11 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +    );
ちなみになのですが、この場合って連続再生で非対応なものが来たとき、アクセントに移動しますか･･･？ 👀
まあ別にいいかなと思いつつ、ユーザーにとっては予想外かもとちょっと思いました。

タブを移動させず、表示が全てdisabledになるのが挙動としては優しそうです。
が、今の機構だとかなり大規模な改修が必要で大変だと思います。

エンジンloading中に出てくる半透明のdivを被せてしまう、とかが割と良い対策なのかなと思いました。
が、PRの内容とだいぶ変わってしまうので、いったんTODOコメントを書いていただく感じでも大丈夫です･･･！

2022-09-08 14:13 UTC, sevenc-nanashi commented on src/components/AudioInfo.vue
> +          opacity: `${speedScaleSlider.qSliderProps.disable.value ? 0.5 : 1}`,
![image](https://user-images.githubusercontent.com/59691627/189144834-bb258b97-c0d0-4add-9589-fd0b7109b89d.png)

`disabled`クラス動きました。カーソルのアイコンも変わるのでこっちにします

2022-09-08 14:16 UTC, sevenc-nanashi commented on src/components/AudioDetail.vue
> +    );
> アクセントに移動しますか･･･？ 

アクセントに移動しましたね。
連続再生でイントネーション/長さを見ることは殆ど無いと思いますが、一応TODO置いておきます

2022-09-08 14:19 UTC, Hiroshiba commented on src/store/ui.ts
> +      async LOAD_ENGINE_MANIFESTS({ state, commit }) {
名前、難しいですね･･･やってることはFETCH_AND_SETなのですが、良い言葉が見つかりません。
このままでも大丈夫ですが、もし気が向いたら`FETCH_AND_SET`とかにして頂けると 🙇

2022-09-08 14:20 UTC, Hiroshiba requested changes
いくつかコメントを書きましたが、概ねLGTMの気持ちです！

2022-09-08 14:20 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +    );
> 連続再生でイントネーション/長さを見ることは殆ど無いと思いますが

たしかに･･･！

2022-09-08 14:21 UTC, sevenc-nanashi commented on src/components/AudioDetail.vue
> +    );
返すようにしてみました。

2022-09-08 14:24 UTC, sevenc-nanashi commented on src/store/ui.ts
> +      async LOAD_ENGINE_MANIFESTS({ state, commit }) {
FETCH_AND_SET_ENGINE_MANIFESTSにしてみました。

2022-09-08 14:27 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +          opacity: `${speedScaleSlider.qSliderProps.disable.value ? 0.5 : 1}`,
おー！良いですね！！

2022-09-08 14:29 UTC, sevenc-nanashi commented on src/components/AudioInfo.vue
> +        }"
無効化されてることが判りやすかったのでこうなってます。
（完全に個人の感想）

2022-09-08 14:30 UTC, sevenc-nanashi commented on src/components/AudioInfo.vue
> +    );
まとめました

2022-09-09 14:38 UTC, Hiroshiba approved these changes
LGTM！！

2022-09-09 14:57 UTC, raa0121 commented
このブランチに main を再度マージして、試してみましたが、エラーが出ました。
COELINK 側には、 #922 に貼られてた engine_manifest.json を設置済みです。
```
[23:52:17.942] [error] Failed to read icon file: C:\Users\raa0121\AppData\Roaming\voicevox-dev\engines\COEIROINK-CPU-c0.2.0+v0.10.preview.0\icon.png
[23:52:18.497] [error] Failed to read icon file: C:\Users\raa0121\AppData\Roaming\voicevox-dev\engines\COEIROINK-CPU-c0.2.0+v0.10.preview.0\icon.png
[23:52:18.498] [info]  Starting 2 engine/s...
[23:52:18.499] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Start launching
[23:52:18.499] [error] Failed to read icon file: C:\Users\raa0121\AppData\Roaming\voicevox-dev\engines\COEIROINK-CPU-c0.2.0+v0.10.preview.0\icon.png
[23:52:18.500] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d: Starting process
[23:52:18.500] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d mode: GPU
[23:52:18.501] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d path: D:\Program\VOICEVOX\run.exe
[23:52:18.501] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d args: ["--use_gpu"]
[23:52:18.558] [info]  ENGINE d9212658-962f-4918-80b2-310b7de70c41: Start launching
[23:52:18.559] [error] Failed to read icon file: C:\Users\raa0121\AppData\Roaming\voicevox-dev\engines\COEIROINK-CPU-c0.2.0+v0.10.preview.0\icon.png
[23:52:18.559] [info]  ENGINE d9212658-962f-4918-80b2-310b7de70c41: Starting process
[23:52:18.560] [info]  ENGINE d9212658-962f-4918-80b2-310b7de70c41 mode: GPU
[23:52:18.560] [info]  ENGINE d9212658-962f-4918-80b2-310b7de70c41 path: C:\Users\raa0121\AppData\Roaming\voicevox-dev\engines\COEIROINK-CPU-c0.2.0+v0.10.preview.0\run
[23:52:18.560] [info]  ENGINE d9212658-962f-4918-80b2-310b7de70c41 args: ["--use_gpu"]
[31188:0909/235219.056:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[31188:0909/235219.057:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[23:52:20.614] [error] TypeError: Failed to fetch
    at DefaultApi._callee$ (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:89:30)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:293:1)
    at Generator.next (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:118:1)
    at http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:70:1)
    at DefaultApi.BaseAPI.fetchApi (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:79:65)
    at DefaultApi._callee2$ (http://localhost:8080/js/webpack:/src/openapi/runtime.ts:49:37)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
[23:52:22.144] [error] ENGINE d9212658-962f-4918-80b2-310b7de70c41 STDERR: Warning: Failed to read the user dictionary.
Traceback (most recent call last):
  File "voicevox_engine\synthesis_engine\make_synthesis_engine.py", line 39, in make_synthesis_engine
ModuleNotFoundError: No module named 'core'
Notice: mock-library will be used. Try re-run with valid --voicevox_dir

[23:52:22.153] [error] ENGINE d9212658-962f-4918-80b2-310b7de70c41 STDERR: INFO:     Started server process [18632]
INFO:uvicorn.error:Started server process [18632]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.

[23:52:22.154] [error] ENGINE d9212658-962f-4918-80b2-310b7de70c41 STDERR: INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50031 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:50031 (Press CTRL+C to quit)

[23:52:26.358] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )

[23:52:26.365] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Started server process [18760]
INFO:     Waiting for application startup.

[23:52:26.415] [info]  ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDOUT: reading D:\Program\VOICEVOX\default.csv ... 42
emitting double-array:  35% |###############                            | 
emitting double-array: 100% |###########################################|  emitting double-array:  38% |################                           | 

[23:52:26.460] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Application startup complete.

[23:52:26.461] [error] ENGINE 074fc39e-678b-4c13-8916-ffca8d505d1d STDERR: INFO:     Uvicorn running on http://127.0.0.1:50021 (Press CTRL+C to quit)

[17600:0909/235417.307:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is 
```

2022-09-09 15:01 UTC, sevenc-nanashi commented
update_infosあたりで死んだのでそれかもしれません。
```json
{
  "command": "run",
  "default_sampling_rate": 24000,
  "dependency_licenses": [
    {
      "license": "dummy license",
      "name": "dummy library",
      "text": "dummy license text",
      "version": "0.0.1"
    }
  ],
  "downloadable_libraries_path": null,
  "downloadable_libraries_url": null,
  "icon": "icon.png",
  "manifest_version": "0.13.0",
  "name": "COEIROINK ENGINE",
  "port": 50031,
  "supported_features": {
    "adjust_intonation_scale": false,
    "adjust_mora_pitch": false,
    "adjust_phoneme_length": false,
    "adjust_pitch_scale": false,
    "adjust_speed_scale": false,
    "adjust_volume_scale": false,
    "interrogative_upspeak": false
  },
  "terms_of_service": "dummy teams of service",
  "update_infos": [
    {
      "contributors": [
        "dummy contributor"
      ],
      "descriptions": [
        "dummy descriptions"
      ],
      "version": "0.0.1"
    }
  ],
  "url": "https://github.com/shirowanisan/voicevox",
  "uuid": "d9212658-962f-4918-80b2-310b7de70c41",
  "version": "999.999.999"
}

```
これでやってみてください

2022-09-09 15:17 UTC, sevenc-nanashi commented
```py
import flask
import requests
import json
from flask_cors import CORS

app = flask.Flask(__name__)
CORS(app)
initialized = set()
session = requests.Session()


@app.route("/engine_manifest")
def engine_manifest():
    with open("../coeiroink/engine_manifest.json") as f:
        d = json.load(f)
    for k in ("update_infos", "dependency_licenses"):
        with open("../coeiroink/" + d[k]) as f:
            d[k] = json.load(f)
    with open("../coeiroink/" + d["terms_of_service"]) as f:
        d["terms_of_service"] = f.read()
    d["supported_features"] = {k: v["value"] for k, v in d["supported_features"].items()}
    r = flask.jsonify(d)
    r.access_control_allow_origin = "*"
    return r


@app.route("/", defaults={"path": ""})
@app.route("/<path:path>", methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"])
def proxy(path):
    resp = session.request(
        method=flask.request.method,
        url=flask.request.url.replace(flask.request.host_url, "http://localhost:50031/"),
        headers={
            key: value
            for (key, value) in flask.request.headers
            if key != "Host" and key != "Access-Control-Allow-Origin"
        },
        data=flask.request.get_data(),
        cookies=flask.request.cookies,
    )
    # print("Done:", time.time() - before)
    if path == "initialize_speaker":
        initialized.add(flask.request.args["speaker"])
    return flask.Response(
        response=resp.content,
        status=resp.status_code,
        headers={key: value for (key, value) in resp.raw.headers.items()},
    )


app.run(port=50030, debug=True)
```
自分が使ってたプロキシ（？）です、こっちを登録すれば動くかも？

2022-09-09 16:12 UTC, Hiroshiba commented
@raa0121 プロキシ挟むか、もしくはとりあえずUI無効化を試すなら、ボイボのengine_manifest.jsonのfeaturesを全部falseにして起動すればOKだと思います！

2022-09-12 07:13 UTC, raa0121 commented
すいません、手元でちゃんと動かせてないんですが、コード的には問題ないと思います。

2022-09-12 14:29 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +        ]?.supportedFeatures || ({} as EngineManifest["supportedFeatures"])
テキスト欄を追加した後消去するとここでエラーになりました！
消去する直前にaudioItem.valueがundefinedになるっぽいです。。
こうすると動きそう？

```suggestion
        store.state.engineManifests[
          audioItem.value?.engineId ?? store.state.engineIds[0]
        ]?.supportedFeatures || ({} as EngineManifest["supportedFeatures"])
```

2022-09-12 14:35 UTC, Hiroshiba commented on src/components/AudioInfo.vue
> +        ]?.supportedFeatures || ({} as EngineManifest["supportedFeatures"])
こちらもエラーになるかも。

`audioItem.value.engineId ?? store.state.engineIds[0]`と想定外の挙動を握りつぶすと謎の挙動が起きたときに原因箇所の特定が大変になりそうに思いました。（いろんな考え方があると思うので、意見あればお伺いしたいです 🙏 ）
warningを出すか、undefinedを返すようにするのはどうでしょう。

それと`{} as EngineManifest["supportedFeatures"]`を返すと型が謎なことになり（keyがあったりなかったりする）、他の方がコードを触るときのメンテナンス性が下がりそうです。
素直にundefinedを返して、`supportedFeatures`をundefinableにするのはどうでしょう。

2022-09-12 14:35 UTC, Hiroshiba requested changes
実際に触ってみるとちょっと変な挙動があったので`Request changes`にしました！

2022-09-12 21:13 UTC, sevenc-nanashi commented on src/components/AudioDetail.vue
> +        ]?.supportedFeatures || ({} as EngineManifest["supportedFeatures"])
修正しました。

2022-09-12 21:13 UTC, sevenc-nanashi commented on src/components/AudioInfo.vue
> +        ]?.supportedFeatures || ({} as EngineManifest["supportedFeatures"])
素直にundefinedを返すようにしました。

2022-09-13 15:08 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +              :disable="!supportedFeatures?.adjustPhonemeLength"
```suggestion
              :disable="
                !(supportedFeatures && supportedFeatures.adjustPhonemeLength)
              "
```

2022-09-13 15:08 UTC, Hiroshiba commented on src/components/AudioDetail.vue
> +              :disable="!supportedFeatures?.adjustMoraPitch"
（もうLGTMだと思うので勝手にマージしちゃいます！）

2022-09-13 15:10 UTC, merged