複数エンジン対応：アイコン情報をengine manifestから取得するように
VOICEVOX/voicevox pull request #953
Opened 2022-09-24 01:47 UTC by sevenc-nanashi

## 内容

MenuBarやAudioCellのアイコンをengine manifestから取得するようにします。

## 関連 Issue

- ref: voicevox/voicevox_project#2： envではなくengine_manifest.jsonから情報を得るようにする

## スクリーンショット・動画など

正常に動作しているのが確認出来ました。
![image](https://user-images.githubusercontent.com/59691627/192074909-486fe3e3-d37d-4dd2-919f-db9700fe7b09.png)
![image](https://user-images.githubusercontent.com/59691627/192074911-ad47270e-e5ae-49f7-a753-b73f080efc88.png)

## その他

（なし）

2022-09-24 13:54 UTC, Hiroshiba approved these changes
LGTM！！
いつもありがとうございます！！

2022-09-24 13:54 UTC, Hiroshiba commented on src/helpers/imageHelper.ts
> +export function detectImageTypeFromBase64(data: string): string {
こっちはexportいらないかも

2022-09-24 13:54 UTC, Hiroshiba commented on src/helpers/imageHelper.ts
> +export function base64ImageToUri(image: string): string {
この関数良いですね！

store/audio.tsで何箇所か同じことをしているので、こちらも`base64ImageToUri`に変えるのお願いしてもいいですか 🙇 
https://github.com/VOICEVOX/voicevox/blob/951165928d40723e6191d510efb77f597ac0b3a1/src/store/audio.ts#L623

2022-09-24 13:54 UTC, Hiroshiba commented on src/components/MenuBar.vue
> +    watch([engineInfos, engineManifests], updateEngines, { immediate: true }); // engineInfos、engineManifestsを見て動的に更新できるようにする
👍

2022-09-24 13:56 UTC, Hiroshiba commented
@raa0121 さん、もしよかったらレビューお願いできると心強いです･･･！ 🙏

2022-09-24 22:05 UTC, sevenc-nanashi commented on src/helpers/imageHelper.ts
> +export function detectImageTypeFromBase64(data: string): string {
確かに。消しました。

2022-09-24 22:05 UTC, sevenc-nanashi commented on src/helpers/imageHelper.ts
> +export function base64ImageToUri(image: string): string {
変えてきました。１カ所audio/wavのがあったのでそこは残してます。

2022-09-25 06:29 UTC, raa0121 requested changes

2022-09-25 06:29 UTC, raa0121 commented on src/helpers/imageHelper.ts
> +  const rawBytes = atob(image);
手元だと、atob が無いって怒られます

 ```
 [23:14:22.113] [error] Error: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at base64ImageToUri (http://localhost:8080/js/webpack:/src/helpers/imageHelper.ts:18:20)
    at http://localhost:8080/js/webpack:/src/components/MenuBar.vue:411:35
    at Array.map (<anonymous>)
    at _callee6$ (http://localhost:8080/js/webpack:/src/components/MenuBar.vue:404:47)
    at tryCatch (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:63:15)
    at Generator.invoke [as _invoke] (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:293:1)
    at Generator.next (http://localhost:8080/js/webpack:/node_modules/regenerator-runtime/runtime.js:118:1)
    at http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:74:1
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:8080/js/webpack:/node_modules/tslib/tslib.es6.js:70:1)
```

```js
export function base64ImageToUri(image: string): string {
  const mimeType = detectImageTypeFromBase64(image);
  const buffer = Buffer.from(image, "base64");
  return URL.createObjectURL(
    new Blob([buffer.buffer], {
      type: mimeType,
    })
  );
}
```
これが簡潔だと思います。

2022-09-25 06:30 UTC, raa0121 approved these changes
問題ないと思います。

2022-09-25 10:36 UTC, sevenc-nanashi commented
rebase mainしましたー。conflict無くマージできるはずです

2022-09-25 16:58 UTC, Hiroshiba reviewed
大丈夫そうなのでマージします！！ありがとうございました！！

2022-09-25 16:58 UTC, merged

2022-09-25 17:00 UTC, Hiroshiba commented
@raa0121 さんもレビューありがとうございます！